### ISSUE TITLE
0.92 installation?

### ISSUE THREAD

**Issue by haakonstorm** [MindrustUK/Heatmiser-for-home-assistant#10]
What is the new way to install on latest home assistant, with `manifest.json` etcetera?
Keep up the great work!

**Comment by MindrustUK** [comment]
Hi @haakonstorm 

For hass.io you can do the following:

```
cd /config/custom_components/heatmiserneo/
wget https://raw.githubusercontent.com/MindrustUK/Heatmiser-for-home-assistant/master/manifest.json
```
Or just remove the component and repeat the installation as per the docs.

I'd restart HASS in both cases to make sure everything loads in as expected.

Any problems drop a note back in the ticket.
