### ISSUE TITLE
Questions about Floor Temperatures

### ISSUE THREAD

**Issue by PhillyGilly** [MindrustUK/Heatmiser-for-home-assistant#101]
At the conclusion of #72 I was seeing floor temperatures reported to one decimal place e.g. 14.8 C.
I'm still seeing them reported to one decimal place but only in whole numbers e.g. 25.0 C or 26.0 C.
![image](https://user-images.githubusercontent.com/56273663/148522119-c828c839-982b-4af6-9422-8766b3bbbf4d.png)
Also I noticed that the temperatures being reported for Bathrooms that are in stand-by appear to be flat/constant.
Is this expected behaviour?

**Comment by ribbal** [comment]
@PhillyGilly, are you able to create some debug logs, then do a search for 'current_floor_temperature='?  Do you see any temperatures that display the decimal value (ignore any with a value of 127.5)?  If not, then I believe that the issue lies with the neohub api.

**Comment by ribbal** [comment]
Regarding the flat-line temperatures for the stats that are in stand-by mode, please can you check what is in the logs for 'current_floor_temperature' for a stat that is in both stand-by mode and in active mode?

**Comment by PhillyGilly** [comment]
This is a neostat-E in standby "Bathroom 1":
simple_attrs=('active_level', 'active_profile', 'available_modes', 'away', 'cool_on', 'cool_temp', 'current_floor_temperature', 'date', 'device_id', 'fan_control', 'fan_speed', 'floor_limit', 'hc_mode', 'heat_mode', 'heat_on', 'hold_cool', 'fan_control', 'fan_speed', 'hc_mode', 'heat_mode', 'heat_on', 'hold_cool', 'hold_off', 'hold_on', 'hold_temp', 'hold_time', 'holiday', 'lock', 'low_battery', 'manual_off', 'modelock', 'modulation_level', 'offline', 'pin_number', 'preheat_active', 'prg_temp', 'prg_timer', 'standby', 'switch_delay_left', 'temporary_set_flag', 'time', 'timer_on', 'window_open', 'write_count'), active_level=2, active_profile=5, available_modes=['heat'], away=False, cool_on=False, cool_temp=0, current_floor_temperature=127.5, date='friday', device_id=6, fan_control='Automatic', fan_speed='Off', floor_limit='Bedroom 1', hc_mode='VENT', heat_mode=True, heat_on=True, hold_cool=0, hold_off=True, hold_on=False, hold_temp=16, hold_time=datetime.timedelta(0), holiday=False, lock=False, low_battery=False, manual_off=True, modelock=False, modulation_level=0, offline=False, pin_number=0, preheat_active=0, prg_temp=0, prg_timer=False, standby=False, switch_delay_left=datetime.timedelta(0), temporary_set_flag=False, time=datetime.timedelta(seconds=52800), timer_on=False, window_open=False, write_count=0, name='Bedroom 1', target_temperature='19.0', temperature='16.8', weekday=<Weekday.FRIDAY: 'friday'>), NeoStat(_logger=<HassLogger neohub (CRITICAL)>, _data_=namespace(ACTIVE_LEVEL=2, ACTIVE_PROFILE=4, ACTUAL_TEMP='17.1', AVAILABLE_MODES=['heat'], AWAY=False, COOL_MODE=False, COOL_ON=False, COOL_TEMP=0, CURRENT_FLOOR_TEMPERATURE=14, DATE='friday', DEVICE_ID=7, FAN_CONTROL='Automatic', FAN_SPEED='Off', FLOOR_LIMIT=False, HC_MODE='VENT', HEAT_MODE=True, HEAT_ON=False, HOLD_COOL=0, HOLD_OFF=True, HOLD_ON=False, HOLD_TEMP=21, HOLD_TIME='0:00', HOLIDAY=False, LOCK=False, LOW_BATTERY=False, MANUAL_OFF=True, MODELOCK=False, MODULATION_LEVEL=0, OFFLINE=False, PIN_NUMBER='0000', PREHEAT_ACTIVE=False, PRG_TEMP=0, PRG_TIMER=False, RECENT_TEMPS=['16.4', '16.2', '16.2', '16.2', '16.2', '16.2', '16.3', '16.3', '16.3', '16.4', '16.4', '16.4', '16.4', '16.4', '16.4', '16.5', '16.5', '16.5', '16.5', '16.5', '16.5', '16.5', '16.5', '16.6', '16.6', '16.6', '16.6', '16.6', '16.7', '16.7', '16.8', '16.7', '16.7', '16.7', '16.8', '16.7', '16.7', '16.7', '16.7', '16.6', '16.6', '16.6', '16.5', '16.5', '16.4', '16.4', '16.3', '16.3', '16.2', '16.2', '16.2', '16.1', '16.0', '16.0', '15.9', '15.9', '15.9', '15.8', '15.8', '15.7', '15.7', '15.6', '15.6', '15.5', '15.5', '15.4', '15.4', '15.4', '15.4', '15.5', '15.5', '15.6', '15.7', '15.8', '15.9', '16.0', '16.1', '16.2', '16.3', '16.3', '16.3', '16.4', '16.5', '16.5', '16.5', '16.6', '16.7', '16.7', '16.8', '16.8', '16.9', '16.9', '17.0', '17.0', '17.1', '17.1'], RELATIVE_HUMIDITY=0, SET_TEMP='12.0', STANDBY=True, SWITCH_DELAY_LEFT='0:00', TEMPORARY_SET_FLAG=False, THERMOSTAT=True, TIME='14:40', TIMER_ON=False, WINDOW_OPEN=False, WRITE_COUNT=48, ZONE_NAME='Bathroom 1'), 
This is a neostat-E that is active "Bathroom-3" 
 _simple_attrs=('active_level', 'active_profile', 'available_modes', 'away', 'cool_on', 'cool_temp', 'current_floor_temperature', 'date', 'device_id', 'fan_control', 'fan_speed', 'floor_limit', 'hc_mode', 'heat_mode', 'heat_on', 'hold_cool', 'fan_control', 'fan_speed', 'hc_mode', 'heat_mode', 'heat_on', 'hold_cool', 'hold_off', 'hold_on', 'hold_temp', 'hold_time', 'holiday', 'lock', 'low_battery', 'manual_off', 'modelock', 'modulation_level', 'offline', 'pin_number', 'preheat_active', 'prg_temp', 'prg_timer', 'standby', 'switch_delay_left', 'temporary_set_flag', 'time', 'timer_on', 'window_open', 'write_count'), active_level=2, active_profile=5, available_modes=['heat'], away=False, cool_on=False, cool_temp=0, current_floor_temperature=127.5, date='friday', device_id=10, fan_control='Automatic', fan_speed='Off', floor_limit='Bedroom 2', hc_mode='VENT', heat_mode=True, heat_on=True, hold_cool=0, hold_off=True, hold_on=False, hold_temp=19, hold_time=datetime.timedelta(0), holiday=False, lock=False, low_battery=False, manual_off=True, modelock=False, modulation_level=0, offline=False, pin_number=0, preheat_active=0, prg_temp=0, prg_timer=False, standby=False, switch_delay_left=datetime.timedelta(0), temporary_set_flag=False, time=datetime.timedelta(seconds=52860), timer_on=False, window_open=False, write_count=0, name='Bedroom 2', target_temperature='19.0', temperature='17.9', weekday=<Weekday.FRIDAY: 'friday'>), NeoStat(_logger=<HassLogger neohub (CRITICAL)>, _data_=namespace(ACTIVE_LEVEL=2, ACTIVE_PROFILE=4, ACTUAL_TEMP='17.1', AVAILABLE_MODES=['heat'], AWAY=False, COOL_MODE=False, COOL_ON=False, COOL_TEMP=0, CURRENT_FLOOR_TEMPERATURE=22, DATE='friday', DEVICE_ID=11, FAN_CONTROL='Automatic', FAN_SPEED='Off', FLOOR_LIMIT=False, HC_MODE='VENT', HEAT_MODE=True, HEAT_ON=False, HOLD_COOL=0, HOLD_OFF=True, HOLD_ON=False, HOLD_TEMP=16, HOLD_TIME='0:00', HOLIDAY=False, LOCK=False, LOW_BATTERY=False, MANUAL_OFF=True, MODELOCK=False, MODULATION_LEVEL=0, OFFLINE=False, PIN_NUMBER='0000', PREHEAT_ACTIVE=False, PRG_TEMP=0, PRG_TIMER=False, RECENT_TEMPS=['14.9', '15.0', '15.1', '15.2', '15.1', '15.1', '15.2', '15.3', '15.3', '15.4', '15.3', '15.4', '15.3', '15.3', '15.3', '15.4', '15.4', '15.4', '15.4', '15.4', '15.4', '15.5', '15.5', '15.6', '15.8', '15.9', '15.9', '15.7', '15.7', '15.8', '15.9', '15.9', '15.9', '15.8', '15.8', '15.8', '16.0', '16.0', '15.8', '15.7', '15.6', '15.5', '15.5', '15.4', '15.4', '15.3', '15.2', '15.2', '15.1', '15.0', '14.9', '14.9', '14.8', '14.7', '14.7', '14.6', '14.6', '14.5', '14.4', '14.3', '14.3', '14.2', '14.2', '14.2', '14.1', '14.1', '14.2', '14.2', '14.2', '14.3', '14.3', '14.4', '14.7', '14.8', '14.8', '14.5', '14.4', '14.2', '14.3', '14.4', '15.1', '15.6', '16.2', '16.7', '16.8', '17.2', '17.4', '17.6', '17.9', '17.8', '17.7', '17.5', '17.4', '17.3', '17.2', '17.1'], RELATIVE_HUMIDITY=0, SET_TEMP='17.0', STANDBY=False, SWITCH_DELAY_LEFT='0:00', TEMPORARY_SET_FLAG=False, THERMOSTAT=True, TIME='14:41', TIMER_ON=False, WINDOW_OPEN=False, WRITE_COUNT=24, ZONE_NAME='Bathroom 3'), 
Finally here is Bathroom 3 in stand-by:
_hub=<neohubapi.neohub.NeoHub object at 0x7f71eb5eb0>, _simple_attrs=('active_level', 'active_profile', 'available_modes', 'away', 'cool_on', 'cool_temp', 'current_floor_temperature', 'date', 'device_id', 'fan_control', 'fan_speed', 'floor_limit', 'hc_mode', 'heat_mode', 'heat_on', 'hold_cool', 'fan_control', 'fan_speed', 'hc_mode', 'heat_mode', 'heat_on', 'hold_cool', 'hold_off', 'hold_on', 'hold_temp', 'hold_time', 'holiday', 'lock', 'low_battery', 'manual_off', 'modelock', 'modulation_level', 'offline', 'pin_number', 'preheat_active', 'prg_temp', 'prg_timer', 'standby', 'switch_delay_left', 'temporary_set_flag', 'time', 'timer_on', 'window_open', 'write_count'), active_level=2, active_profile=5, available_modes=['heat'], away=False, cool_on=False, cool_temp=0, current_floor_temperature=127.5, date='friday', device_id=10, fan_control='Automatic', fan_speed='Off', floor_limit='Bedroom 2', hc_mode='VENT', heat_mode=True, heat_on=True, hold_cool=0, hold_off=True, hold_on=False, hold_temp=19, hold_time=datetime.timedelta(0), holiday=False, lock=False, low_battery=False, manual_off=True, modelock=False, modulation_level=0, offline=False, pin_number=0, preheat_active=0, prg_temp=0, prg_timer=False, standby=False, switch_delay_left=datetime.timedelta(0), temporary_set_flag=False, time=datetime.timedelta(seconds=53580), timer_on=False, window_open=False, write_count=0, name='Bedroom 2', target_temperature='19.0', temperature='17.9', weekday=<Weekday.FRIDAY: 'friday'>), NeoStat(_logger=<HassLogger neohub (CRITICAL)>, _data_=namespace(ACTIVE_LEVEL=2, ACTIVE_PROFILE=4, ACTUAL_TEMP='17.0', AVAILABLE_MODES=['heat'], AWAY=False, COOL_MODE=False, COOL_ON=False, COOL_TEMP=0, CURRENT_FLOOR_TEMPERATURE=22, DATE='friday', DEVICE_ID=11, FAN_CONTROL='Automatic', FAN_SPEED='Off', FLOOR_LIMIT=False, HC_MODE='VENT', HEAT_MODE=True, HEAT_ON=False, HOLD_COOL=0, HOLD_OFF=True, HOLD_ON=False, HOLD_TEMP=16, HOLD_TIME='0:00', HOLIDAY=False, LOCK=False, LOW_BATTERY=False, MANUAL_OFF=True, MODELOCK=False, MODULATION_LEVEL=0, OFFLINE=False, PIN_NUMBER='0000', PREHEAT_ACTIVE=False, PRG_TEMP=0, PRG_TIMER=False, RECENT_TEMPS=['15.0', '15.1', '15.2', '15.1', '15.1', '15.2', '15.3', '15.3', '15.4', '15.3', '15.4', '15.3', '15.3', '15.3', '15.4', '15.4', '15.4', '15.4', '15.4', '15.4', '15.5', '15.5', '15.6', '15.8', '15.9', '15.9', '15.7', '15.7', '15.8', '15.9', '15.9', '15.9', '15.8', '15.8', '15.8', '16.0', '16.0', '15.8', '15.7', '15.6', '15.5', '15.5', '15.4', '15.4', '15.3', '15.2', '15.2', '15.1', '15.0', '14.9', '14.9', '14.8', '14.7', '14.7', '14.6', '14.6', '14.5', '14.4', '14.3', '14.3', '14.2', '14.2', '14.2', '14.1', '14.1', '14.2', '14.2', '14.2', '14.3', '14.3', '14.4', '14.7', '14.8', '14.8', '14.5', '14.4', '14.2', '14.3', '14.4', '15.1', '15.6', '16.2', '16.7', '16.8', '17.2', '17.4', '17.6', '17.9', '17.8', '17.7', '17.5', '17.4', '17.3', '17.2', '17.1', '17.0'], RELATIVE_HUMIDITY=0, SET_TEMP='12.0', STANDBY=True, SWITCH_DELAY_LEFT='0:00', TEMPORARY_SET_FLAG=False, THERMOSTAT=True, TIME='14:57', TIMER_ON=False, WINDOW_OPEN=False, WRITE_COUNT=25, ZONE_NAME='Bathroom 3'),

**Comment by ribbal** [comment]
Thanks.  I can see that the floor temperature doesn't appear to be related to the stand-by status.  For Bathroom 3, this shows as 22 for both stand-by and active modes.  I'm not sure why Bathroom 1 would show a static value of 14 (in stand-by mode).

**Comment by PhillyGilly** [comment]
Bathroom 1 is cold if there is no heating!
![image](https://user-images.githubusercontent.com/56273663/148567383-c7b82c6d-dfdc-4181-a0bc-18f3525d835f.png)
What made me suspicious is that it is constant when I would expect it to get colder at night and then warmer in the day. However this trace shows it is moving (maybe its reached rock bottom?) but I suppose the changes maybe less than 1C so won't be observable in day without better granularity.

**Comment by ribbal** [comment]
Yeah, I'm inclined to agree with you that it's probably hovering around 14C, and given a 1C granularity you can't see any fluctuations.  So, no 'flatline' issue then?

**Comment by PhillyGilly** [comment]
Agreed no flat-line. If we can get the granularity it should show it's not flat despite appearances.

**Comment by MindrustUK** [comment]
CURRENT_FLOOR_TEMPERATURE always appears to be an integer, not sure why. I'd suggest raising it with Heatmiser as an API bug as I would think it should be reported as a float.

**Comment by MindrustUK** [comment]
Closing, stale.
