### ISSUE TITLE
Updating to latest homeassistant 2021.12.9 integration no longer found

### ISSUE THREAD

**Issue by iandarbey** [MindrustUK/Heatmiser-for-home-assistant#106]
Hi not sure if it's down to updating the repository changes that were pushed today at the same time as updating to HA 2021.12.9 but I got an error on boot that the integration couldn't be found.

Disabling and re-enabling had no effect.

Uninstall / delete and reinstall is the same.

Of note, instegration no longer available in integration list after clicking add integration.

Other HACS Integrations unaffected by HA update.

**Comment by timknowlden** [comment]
Also the same issue. Could roll back but unsure if this will make a difference.

The info on this repo says to enable legacy support in the Neo app. But that’s not an option I can find.

**Comment by timknowlden** [comment]
I can confirm rolling back to 2021.12.8 does not fix the issue

**Comment by timknowlden** [comment]
Redownload or repo worked

**Comment by iandarbey** [comment]
That worked for me now although I swear I tried that before posting the issue.
