### ISSUE TITLE
Integration not in list

### ISSUE THREAD

**Issue by davidbakeriom** [MindrustUK/Heatmiser-for-home-assistant#108]
Hi,

I've followed the instructions, and can confirm the repository is loaded (I see an error warning me of custom components being loaded - HACS and heatmiserneo).

When I visit the integrations panel, and click the blue 'Add Integrations'  I can't find the integration in the list to add.

I've also tried the legacy method, but get errors saying installation in this manner are no longer supported (as documented in the issues in this site).

I've removed the repository as well (a number of times) + restarted via the gui and a full 'reboot'.

I'm running Home Assistant 2022.2.9.

Only thing in the logs are -

> 2022-02-21 23:13:20 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-02-21 23:13:20 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration heatmiserneo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Thanks

**Comment by PhillyGilly** [comment]
So nothing like this showing:

![image](https://user-images.githubusercontent.com/56273663/156745893-eb268268-f659-4d67-8041-cd910e3e137d.png)

**Comment by davidbakeriom** [comment]
Hi,

Bizarrely, a couple of days after fiddling, installing and rebooting - that option did indeed appear - and all is working well.

Thanks for coming back to me - no idea what it was!
