### ISSUE TITLE
Floor probe missing

### ISSUE THREAD

**Issue by rEs-84** [MindrustUK/Heatmiser-for-home-assistant#112]
Hi,
all was well with this integration occe i got my heatmister.
A little while ago my HACs/this integration got un happy.

I had to remove and re add the integration. Now the floor sensor wont come back
![image](https://user-images.githubusercontent.com/34245082/195433196-84de94f1-15b0-46ae-adb7-ebcf0ca6d545.png)

![image](https://user-images.githubusercontent.com/34245082/195433260-50c09e80-2ee8-4832-b648-9866a1957b7d.png)

I used to have 2 devices, maybe the stat and the zone or the stat and the hub.

![image](https://user-images.githubusercontent.com/34245082/195433410-3540f776-29ff-4dc9-8537-693e9e8b5388.png)

![image](https://user-images.githubusercontent.com/34245082/195433536-71cfe07e-891e-4ca0-9916-63bb1bcd4b02.png)

what's the first things to set? Legacy api is enabled on the cloud app.
Thanks in advance

**Comment by PhillyGilly** [comment]
My floor probes are still working.
![image](https://user-images.githubusercontent.com/56273663/195577666-876ada08-e42b-4f9e-9004-12ae0ac05dd6.png)
You may need to remove everything and re-add.

**Comment by ribbal** [comment]
Hi @rEs-84, IIRC, the initial implementation for floor probes was to duplicate the main climate device (i.e. the room thermostat) and massage the output of the duplicate to report the floor temperature.  This was inefficient, and was amended to remove the duplicate device and add a new 'attribute' to the main climate entity to report the floor temperature.

Can you check to see if your entity has an additional 'floor temperature' attribute?

**Comment by rEs-84** [comment]
Although actually, how do i show that on a graph? i used to be able to see the heating come on / the floor temp rise, then the room temp rise

![image](https://user-images.githubusercontent.com/34245082/195679267-b6a0bbf4-ba48-483e-b739-a1a3a949fe14.png)

**Comment by DrTree** [comment]
You can use a template sensor to expose the attribute as a sensor value that can be charted etc.

**Comment by PhillyGilly** [comment]
I haven't these to the template format yet, but here is a line from my sensor.yaml file:
```
- platform: template
  sensors:
    bathroom_1_floor_temperature:
      friendly_name: "Temp Bathroom 1 Floor"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.bathroom_1', 'floor_temperature') }}"
```

**Comment by MindrustUK** [comment]
Closing, Stale ticket.
