### ISSUE TITLE
pros and cons of this integration versus adding as homekit device

### ISSUE THREAD

**Issue by 170bgrd** [MindrustUK/Heatmiser-for-home-assistant#120]
Hi

Sorry if I'm posting in the wrong place. 

I'm setting up home assistant for the first time. And setting up home assistant in my new home. I'm incredibly lucky and have got a fair bit of stuff that can be added. I want a supportable implementation so looking at how best to integrate everything.

I see I can add the neohub as either a homekit device or using your integration. Can I ask what the motivation was to create this integration versus using home kit integration? What are the other benefits?

I have 15 thermostats and so far one heatmiser socket.
4 of the thermostats have remote air sensors.

https://www.home-assistant.io/integrations/homekit_controller/

**Comment by nickcj931** [comment]
Hi @170bgrd - I responded to you in the community forums as I feel these type of questions/discussions are better suited there. Where GitHub Issues is to help the developer track issues/requests etc. 

For anyone else who comes across this link to discussion is here [https://community.home-assistant.io/t/heatmiser-neo-hub-support-ugly-and-work-in-progress/48/84?u=nickcj](url)

I suggest this gets closed to clear the Issues list @MindrustUK

**Comment by MindrustUK** [comment]
Thanks for replying on the projects behalf @nickcj931 closing issue.
