### ISSUE TITLE
Feature: Add specific device type for HeatMiser Wireless Air Sensors

### ISSUE THREAD

**Issue by liamfoneill** [MindrustUK/Heatmiser-for-home-assistant#121]
When I add the integration, I'm pleased to see each of the [Wireless Sensors ](https://www.heatmiser.com/en/download/211/english/10207/wireless-air-sensor-datasheet.pdf)  (PDF link to product datasheet) are added (something you don't get with the official homekit integration). However they appear as the same type of entity as the thermostats (climate) (with the ability to set a desired temperature etc) which naturally doesn't apply to a sensor only device. Are there any plans to create specific device types for these sensors that only show the temperature readouts?

![image](https://user-images.githubusercontent.com/1243172/214568725-4d47c4e0-1c71-466b-959b-a660d6daa22c.png)

**Comment by MindrustUK** [comment]
Interesting... I don't have one of these yet... it will be a few weeks before I personally have any time to investigate this but it looks like it should be simple enough to add support for.

**Comment by MindrustUK** [comment]
Just had two of these arrive today, I'll see if I get some dev time in the next two weeks to tweak support.

**Comment by MindrustUK** [comment]
Had a quick look into this while I've had 10 minutes today, it appears as though devices are being returned as a whole, not sure if this is the pypi module maintained by @stikonas or I need to set some filtering up within the code I wrote.

Either way we should discriminate on "device_type" to separate true Thermostats (i.e. devices where you can set values to control heating) and remote temperature probes such as these devices (Device type 14) that should appear as sensors. 

Probably worth trying to expand this whole plugin to cover everything in the current eco system. Device type currently 01-17. I'll do some more poking at this when I next get time.

**Comment by stikonas** [comment]
In principle we can do it in pypi module but I have no HeatMiser Wireless Air Sensors, so it would be good if somebody who has them would do merge request.

**Comment by MindrustUK** [comment]
Looked a bit further into this, thanks for the reply @stikonas I'll have to prepare an MR against your module to return "sensors" and "climate" devices separately, And I'll need to cook up a class to handle sensors within this integration. Added to the 'todo' list.

**Comment by MindrustUK** [comment]
I've done some work on this today. There's now an open Pull request with @stikonas to review and feedback on.

**Comment by MindrustUK** [comment]
This pull was merged and  neohubapi 1.1 released. This caused problems for some users so I've set the requirement to 1.0 until I figure out why this is causing trouble. I've been unable to replicate reported issues in my own testing.

**Comment by MindrustUK** [comment]
Ticket for issues reported with neohubapi 1.1: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/132

**Comment by MindrustUK** [comment]
neohubapi 2.0 has been released with fixes and support for this along with an in development version 2 of this integration which should add support for this, please test here: https://github.com/MindrustUK/Heatmiser-for-home-assistant/tree/dev and provide feedback.

**Comment by MindrustUK** [comment]
Closed, support for air sensor added.
