### ISSUE TITLE
HomeKit discovery for Heatmiser neoHub (Bridge) - disable or remove option

### ISSUE THREAD

**Issue by rosscullen** [MindrustUK/Heatmiser-for-home-assistant#123]
Thanks for great integration. I notice it is also discovered in "integrations" as "Heatmiser neoHub (Bridge)" _HomeKit Controller_. 

When I click "configure" on it, I get error "Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble". 

I would prefer to disable it anyways (as I have the HACS integration) but when I click on the 3 dots to do so, I don't get the option to "Ignore" (i only see the "documentation" option).

Any suggestions on how to stop it being discovered, repaired or an option to ignore would be greatly appreciated. Thanks.

**Comment by MindrustUK** [comment]
I'm afraid I can't offer any guidance on this, the HomeKit integration is provided out of Home Assistant it's self. If it has any problems you'd need to seek support via Home Assistant directly: community.home-assistant.io/ I personally have this ignored. I can only suggest maybe trying to update your Home Assistant install. I'm not aware of any ability to disable presentation of the NeoHub as a Home Kit device.
