### ISSUE TITLE
Unable to connect to Neo Hub

### ISSUE THREAD

**Issue by hollytreecook** [MindrustUK/Heatmiser-for-home-assistant#124]
Hi all, sorry I am a bit dumb at this.
I have got HA up and running with PV and battery.
I want to get my Neo system "on board"
HACS is running, the Heatmiser Neo Integration repository installed.
When I try to add the Heatmiser Neo Climate integration I get this pop-up.
I have tried everything.  I know my Neo IP etc 

What do I have to type in please

Thanks
Steve
![Screenshot 2023-04-25 100321](https://user-images.githubusercontent.com/131459314/234231066-d971f862-a4d1-41be-bd92-12c94794e5bd.png)

**Comment by Trouble-51** [comment]
The IP of you heatmiser hub

**Comment by hollytreecook** [comment]
I have typed in 192.168.1.99 so many times. but nothing.
It just snaps straight back
![Screenshot 2023-04-25 102308](https://user-images.githubusercontent.com/131459314/234233713-bd0450ff-3219-431c-bca9-5922f522327b.png)
![Screenshot 2023-04-25 102428](https://user-images.githubusercontent.com/131459314/234234035-a7072c08-2c46-45f9-9f50-848a42cc02fc.png)

**Comment by Trouble-51** [comment]
You could try putting this in your configuration.yaml:

 

climate:

  - platform: heatmiserneo

    host: <Insert IP Address

    port: 4242

 

 

From: hollytreecook ***@***.***>
Reply to: MindrustUK/Heatmiser-for-home-assistant ***@***.***>
Date: Tuesday, 25 April 2023 at 10:25
To: MindrustUK/Heatmiser-for-home-assistant ***@***.***>
Cc: Trouble-51 ***@***.***>, Comment ***@***.***>
Subject: Re: [MindrustUK/Heatmiser-for-home-assistant] Unable to connect to Neo Hub (Issue #124)

 

I have typed in 192.168.1.99 so many times. but nothing.
It just snaps straight back

**Comment by MindrustUK** [comment]
Also make sure the legacy API is enabled in the Heatmiser App as a suggestion.

**Comment by hollytreecook** [comment]
I looked in the Neo app on my laptop and there is nothing about API.
I looked on phone app and there is a Legacy API button. I slid that to enable and typed IP into HA and it connected straight away.
Thanks all
