### ISSUE TITLE
Bug: Changes in Neohubapi v1.1 breaks addon for some users.

### ISSUE THREAD

**Issue by funks81** [MindrustUK/Heatmiser-for-home-assistant#132]
I’m unable to load the Heatmiser integration this morning. Have restarted HA and still getting the same error. 

Retrying setup: 'types.SimpleNamespace' object has no attribute 'DEVICE_ID'

When I select configure on heatmiser i get:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by MindrustUK** [comment]
I made some changes to the https://gitlab.com/neohubapi/neohubapi which are now live which could cause this. However I've not been able to replicate the issue myself. Can you confirm what version of the NeoHub you have?

**Comment by MindrustUK** [comment]
Just run up a fresh install and installed the Heat-miser component without issue.

**Comment by funks81** [comment]
It’s a second generation Neo hun

**Comment by MindrustUK** [comment]
Hmmm very odd, what firmware version are you running?

**Comment by funks81** [comment]
Version 2187Sent from my iPhoneOn 15 May 2023, at 10:28, MindrustUK ***@***.***> wrote:﻿
Hmmm very odd, what firmware version are you running?

**Comment by MindrustUK** [comment]
Can you enable debug logging, then from settings, logs, paste the output for the Heatmiser plugin here. I'm expecting something like: ```2023-05-15 10:57:29.562 DEBUG (MainThread) [custom_components.heatmiserneo] devices_data: {'thermostats': [NeoStat(_logger=<HassLogger neohub (``` please obfuscate / redact any personal information from the logs.

**Comment by tbutcher365** [comment]
Just to confirm I have the same issue.

**Comment by MindrustUK** [comment]
@tbutcher365 can you provide logs?

**Comment by MindrustUK** [comment]
A thought and question to both, do you have any thermostats / devices attached to your hubs? And if so how many?

**Comment by tbutcher365** [comment]
Logger: custom_components.heatmiserneo
Source: custom_components/heatmiserneo/__init__.py:41
Integration: Heatmiser Neo Climate ([documentation](https://github.com/MindrustUK/Heatmiser-for-home-assistant))
First occurred: 11:43:33 (4 occurrences)
Last logged: 11:44:17

Unexpected error fetching neostat data: 'types.SimpleNamespace' object has no attribute 'DEVICE_ID'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
    _, devices_data = await hub.get_live_data()
  File "/usr/local/lib/python3.10/site-packages/neohubapi/neohub.py", line 453, in get_live_data
    if device.DEVICE_ID == value.DEVICE_ID:
AttributeError: 'types.SimpleNamespace' object has no attribute 'DEVICE_ID'

**Comment by MindrustUK** [comment]
Can you provide me the output of:

(Replace NEO_HUB_IP with your hubs IP address).

`printf '{"GET_LIVE_DATA": 0}\0' | nc NEO_HUB_IP 4242`
`printf '{"GET_ENGINEERS": 0}\0' | nc NEO_HUB_IP 4242`

You can run this from Home-Assistant terminal.

**Comment by tbutcher365** [comment]
![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/10322022/e0e98ff5-be5c-432a-93af-51e3d93edf2e)

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/10322022/0708dc31-5243-4e18-b88e-499f18c6a689)

**Comment by funks81** [comment]
This error originated from a custom integration.

Logger: custom_components.heatmiserneo
Source: custom_components/heatmiserneo/__init__.py:41 
Integration: Heatmiser Neo Climate (documentation) 
First occurred: 10:29:35 (76 occurrences) 
Last logged: 12:14:28

Unexpected error fetching neostat data: 'types.SimpleNamespace' object has no attribute 'DEVICE_ID'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
    _, devices_data = await hub.get_live_data()
  File "/usr/local/lib/python3.10/site-packages/neohubapi/neohub.py", line 453, in get_live_data
    if device.DEVICE_ID == value.DEVICE_ID:
AttributeError: 'types.SimpleNamespace' object has no attribute 'DEVICE_ID'

**Comment by funks81** [comment]
I have approximately 10 thermostats and a plug attached to the hub.

**Comment by funks81** [comment]
Sorry struggling to get this. Running HA from virtual box and get an unknown command error for printfSent from my iPhoneOn 15 May 2023, at 11:59, MindrustUK ***@***.***> wrote:﻿
Can you provide me the output of:
(Replace NEO_HUB_IP with your hubs IP address).
printf '{"GET_LIVE_DATA": 0}\0' | nc NEO_HUB_IP 4242
printf '{"GET_ENGINEERS": 0}\0' | nc NEO_HUB_IP 4242
You can run this from Home-Assistant terminal.

**Comment by MindrustUK** [comment]
Thanks @tbutcher365 if you can paste text it will make things easier for me to parse.

Have you tried removing and reinstalling the addon @funks81 @tbutcher365 ? As all the ID's appear to be in place I'm wondering is there some stale cached data somewhere. It looks like (for whatever reason) either the engineering or live data command isn't returning device_id, at least as far as the namespace is concerned. Not sure why this would be ...

**Comment by tbutcher365** [comment]
Yes tried reinstalling but still the same issue. I presume it is related to the latest HA release.

**Comment by tbutcher365** [comment]
{"CLOSE_DELAY":0,"COOL_INPUT":false,"HOLIDAY_END":0,"HUB_AWAY":false,"HUB_HOLIDAY":false,"HUB_TIME":1684162152,"OPEN_DELAY":0,"TIMESTAMP_DEVICE_LISTS":1683887287,"TIMESTAMP_ENGINEERS":1683920367,"TIMESTAMP_PROFILE_0":1683887482,"TIMESTAMP_PROFILE_COMFORT_LEVELS":0,"TIMESTAMP_PROFILE_TIMERS":0,"TIMESTAMP_PROFILE_TIMERS_0":1683887546,"TIMESTAMP_RECIPES":0,"TIMESTAMP_SYSTEM":0,"devices":[{"ACTIVE_LEVEL":3,"ACTIVE_PROFILE":2,"ACTUAL_TEMP":"18.1","AVAILABLE_MODES":["heat"],"AWAY":false,"COOL_MODE":false,"COOL_ON":false,"COOL_TEMP":0,"CURRENT_FLOOR_TEMPERATURE":127.50,"DATE":"monday","DEVICE_ID":1,"FAN_CONTROL":"Automatic","FAN_SPEED":"Off","FLOOR_LIMIT":false,"HC_MODE":"VENT","HEAT_MODE":true,"HEAT_ON":false,"HOLD_COOL":0,"HOLD_OFF":true,"HOLD_ON":false,"HOLD_TEMP":16,"HOLD_TIME":"0:00","HOLIDAY":false,"LOCK":false,"LOW_BATTERY":false,"MANUAL_OFF":true,"MODELOCK":false,"MODULATION_LEVEL":0,"OFFLINE":false,"PIN_NUMBER":"0000","PREHEAT_ACTIVE":false,"PRG_TEMP":18,"PRG_TIMER":true,"RECENT_TEMPS":["18.1","18.4","18.7","19.0","19.2","19.1","19.1","18.9","18.9","19.0","18.8","18.8","18.9","19.0","18.9","19.1","18.9","18.9","18.8","18.6","18.5","18.3","18.1","18.1","18.0","17.9","17.8","17.6","17.7","17.8","17.7","17.8","17.9","17.6","17.7","17.5","17.5","17.6","17.5","17.4","17.4","17.3","17.3","17.2","17.2","17.1","17.1","17.1","17.0","17.0","17.0","16.9","16.9","16.9","16.8","16.7","16.7","16.8","16.7","16.7","16.8","16.7","16.6","16.5","16.5","16.6","16.6","16.6","16.6","16.6","16.6","16.5","16.6","16.6","16.6","16.5","16.7","16.8","16.7","16.9","17.0","16.9","17.0","17.0","17.1","17.2","17.1","17.1","17.2","17.3","17.1","17.3","17.2","17.4","17.5","17.9"],"RELATIVE_HUMIDITY":0,"SET_TEMP":"12.0","STANDBY":true,"SWITCH_DELAY_LEFT":"0:00","TEMPORARY_SET_FLAG":false,"THERMOSTAT":true,"TIME":"14:00","TIMER_ON":false,"WINDOW_OPEN":false,"WRITE_COUNT":5,"ZONE_NAME":"Lounge"},{"ACTIVE_LEVEL":3,"ACTIVE_PROFILE":2,"ACTUAL_TEMP":"16.3","AVAILABLE_MODES":["heat"],"AWAY":false,"COOL_MODE":false,"COOL_ON":false,"COOL_TEMP":0,"CURRENT_FLOOR_TEMPERATURE":127.50,"DATE":"monday","DEVICE_ID":3,"FAN_CONTROL":"Automatic","FAN_SPEED":"Off","FLOOR_LIMIT":false,"HC_MODE":"VENT","HEAT_MODE":true,"HEAT_ON":false,"HOLD_COOL":0,"HOLD_OFF":true,"HOLD_ON":false,"HOLD_TEMP":18,"HOLD_TIME":"0:00","HOLIDAY":false,"LOCK":false,"LOW_BATTERY":false,"MANUAL_OFF":true,"MODELOCK":false,"MODULATION_LEVEL":0,"OFFLINE":false,"PIN_NUMBER":"0000","PREHEAT_ACTIVE":false,"PRG_TEMP":18,"PRG_TIMER":false,"RECENT_TEMPS":["15.1","15.1","15.2","15.2","15.4","15.2","15.4","15.4","15.3","15.5","15.6","15.7","15.9","15.9","16.0","16.1","16.2","16.2","16.2","16.1","16.2","16.1","16.2","16.0","16.0","16.1","16.2","16.0","16.2","16.1","16.0","16.0","15.9","16.0","16.0","15.9","16.0","15.9","16.0","15.9","15.8","16.0","15.9","16.0","16.0","15.8","16.0","15.8","15.9","15.8","15.8","15.8","15.8","15.8","15.8","15.8","15.8","15.8","15.7","15.7","15.6","15.8","15.7","15.8","15.8","15.7","15.7","15.7","15.7","15.7","15.8","16.0","16.0","15.9","16.1","16.0","16.0","15.9","16.2","16.1","16.0","16.2","16.2","16.1","16.0","16.2","16.2","16.2","16.2","16.2","16.1","16.2","16.2","16.3","16.4","16.3"],"RELATIVE_HUMIDITY":0,"SET_TEMP":"12.0","STANDBY":true,"SWITCH_DELAY_LEFT":"0:00","TEMPORARY_SET_FLAG":false,"THERMOSTAT":true,"TIME":"14:01","TIMER_ON":false,"WINDOW_OPEN":false,"WRITE_COUNT":31,"ZONE_NAME":"Hallway"},{"ACTIVE_LEVEL":3,"ACTIVE_PROFILE":2,"ACTUAL_TEMP":"19.9","AVAILABLE_MODES":["heat"],"AWAY":false,"COOL_MODE":false,"COOL_ON":false,"COOL_TEMP":0,"CURRENT_FLOOR_TEMPERATURE":127.50,"DATE":"monday","DEVICE_ID":5,"FAN_CONTROL":"Automatic","FAN_SPEED":"Off","FLOOR_LIMIT":false,"HC_MODE":"VENT","HEAT_MODE":true,"HEAT_ON":false,"HOLD_COOL":0,"HOLD_OFF":true,"HOLD_ON":false,"HOLD_TEMP":16,"HOLD_TIME":"0:00","HOLIDAY":false,"LOCK":false,"LOW_BATTERY":false,"MANUAL_OFF":true,"MODELOCK":false,"MODULATION_LEVEL":0,"OFFLINE":false,"PIN_NUMBER":"0000","PREHEAT_ACTIVE":false,"PRG_TEMP":18,"PRG_TIMER":true,"RECENT_TEMPS":["18.2","18.2","18.2","18.4","18.3","18.5","18.4","18.5","18.6","18.6","18.5","18.6","18.7","18.8","18.8","18.7","18.7","18.8","18.6","18.6","18.6","18.4","18.4","18.4","18.5","18.4","18.6","19.0","19.0","19.2","18.9","18.8","18.7","18.7","18.5","18.5","18.4","18.5","18.3","18.3","18.4","18.3","18.3","18.2","18.1","18.3","18.2","18.2","18.1","18.0","18.0","18.1","18.0","18.1","18.0","18.0","17.9","17.8","17.8","18.0","17.8","17.9","17.9","17.8","17.6","17.7","17.7","17.6","17.7","17.7","17.6","17.7","18.2","18.2","18.4","18.5","18.7","18.9","18.5","18.2","18.1","18.4","18.7","19.0","18.9","18.9","19.0","19.1","19.3","19.3","19.4","19.4","19.3","18.7","19.1","19.5"],"RELATIVE_HUMIDITY":0,"SET_TEMP":"12.0","STANDBY":true,"SWITCH_DELAY_LEFT":"0:00","TEMPORARY_SET_FLAG":false,"THERMOSTAT":true,"TIME":"14:00","TIMER_ON":false,"WINDOW_OPEN":false,"WRITE_COUNT":19,"ZONE_NAME":"Office"},{"ACTIVE_LEVEL":3,"ACTIVE_PROFILE":0,"ACTUAL_TEMP":"16.1","AVAILABLE_MODES":["heat"],"AWAY":false,"COOL_MODE":false,"COOL_ON":false,"COOL_TEMP":0,"CURRENT_FLOOR_TEMPERATURE":127.50,"DATE":"monday","DEVICE_ID":7,"FAN_CONTROL":"Automatic","FAN_SPEED":"Off","FLOOR_LIMIT":false,"HC_MODE":"VENT","HEAT_MODE":true,"HEAT_ON":false,"HOLD_COOL":0,"HOLD_OFF":true,"HOLD_ON":false,"HOLD_TEMP":21,"HOLD_TIME":"0:00","HOLIDAY":false,"LOCK":false,"LOW_BATTERY":false,"MANUAL_OFF":true,"MODELOCK":false,"MODULATION_LEVEL":0,"OFFLINE":false,"PIN_NUMBER":"0000","PREHEAT_ACTIVE":false,"PRG_TEMP":18,"PRG_TIMER":false,"RECENT_TEMPS":["15.0","15.1","15.0","15.1","15.2","15.0","15.1","15.2","15.3","15.2","15.3","15.4","15.4","15.5","15.7","15.7","15.9","15.9","15.9","16.0","15.9","15.8","15.9","15.8","15.9","15.9","15.9","16.0","16.0","15.8","16.0","15.8","15.8","15.8","15.8","15.7","15.7","15.7","15.7","15.8","15.6","15.6","15.6","15.6","15.5","15.6","15.5","15.5","15.6","15.6","15.6","15.5","15.5","15.6","15.5","15.5","15.5","15.6","15.5","15.5","15.5","15.5","15.5","15.5","15.6","15.5","15.6","15.6","15.8","15.9","15.7","15.8","15.8","15.7","15.8","15.8","15.7","15.8","15.9","16.0","15.9","15.9","15.8","15.9","16.0","16.2","16.0","16.0","16.0","16.1","16.0","15.9","16.1","16.1","16.2","16.1"],"RELATIVE_HUMIDITY":0,"SET_TEMP":"12.0","STANDBY":true,"SWITCH_DELAY_LEFT":"0:00","TEMPORARY_SET_FLAG":false,"THERMOSTAT":true,"TIME":"14:04","TIMER_ON":false,"WINDOW_OPEN":false,"WRITE_COUNT":2,"ZONE_NAME":"Bathroom"},{"ACTIVE_LEVEL":3,"ACTIVE_PROFILE":2,"ACTUAL_TEMP":"16.8","AVAILABLE_MODES":["heat"],"AWAY":false,"COOL_MODE":false,"COOL_ON":false,"COOL_TEMP":0,"CURRENT_FLOOR_TEMPERATURE":127.50,"DATE":"monday","DEVICE_ID":9,"FAN_CONTROL":"Automatic","FAN_SPEED":"Off","FLOOR_LIMIT":false,"HC_MODE":"VENT","HEAT_MODE":true,"HEAT_ON":false,"HOLD_COOL":0,"HOLD_OFF":true,"HOLD_ON":false,"HOLD_TEMP":16,"HOLD_TIME":"0:00","HOLIDAY":false,"LOCK":false,"LOW_BATTERY":false,"MANUAL_OFF":true,"MODELOCK":false,"MODULATION_LEVEL":0,"OFFLINE":false,"PIN_NUMBER":"0000","PREHEAT_ACTIVE":false,"PRG_TEMP":18,"PRG_TIMER":false,"RECENT_TEMPS":["16.3","16.3","16.4","16.4","16.3","16.3","16.4","16.4","16.4","16.3","16.3","16.4","16.4","16.5","16.7","16.8","16.7","16.8","16.7","16.6","16.6","16.6","16.9","17.0","16.9","16.8","16.8","16.8","16.7","16.6","16.6","16.6","16.6","16.4","16.4","16.5","16.5","16.4","16.4","16.3","16.4","16.4","16.3","16.4","16.4","16.3","16.4","16.3","16.3","16.4","16.4","16.4","16.2","16.3","16.4","16.2","16.3","16.3","16.3","16.3","16.3","16.4","16.3","16.2","16.3","16.2","16.2","16.3","16.2","16.3","16.5","16.8","16.5","16.5","16.5","16.5","16.7","16.6","16.6","16.6","16.8","16.8","16.7","16.6","16.6","16.8","16.8","16.8","16.8","16.8","16.7","16.7","16.8","16.8","16.8","16.8"],"RELATIVE_HUMIDITY":0,"SET_TEMP":"12.0","STANDBY":true,"SWITCH_DELAY_LEFT":"0:00","TEMPORARY_SET_FLAG":false,"THERMOSTAT":true,"TIME":"14:00","TIMER_ON":false,"WINDOW_OPEN":false,"WRITE_COUNT":0,"ZONE_NAME":"Kitchen"},{"ACTIVE_LEVEL":2,"ACTIVE_PROFILE":0,"ACTUAL_TEMP":"16.9","AVAILABLE_MODES":["heat"],"AWAY":false,"COOL_MODE":false,"COOL_ON":false,"COOL_TEMP":0,"CURRENT_FLOOR_TEMPERATURE":127.50,"DATE":"monday","DEVICE_ID":11,"FAN_CONTROL":"Automatic","FAN_SPEED":"Off","FLOOR_LIMIT":false,"HC_MODE":"VENT","HEAT_MODE":true,"HEAT_ON":false,"HOLD_COOL":0,"HOLD_OFF":true,"HOLD_ON":false,"HOLD_TEMP":21,"HOLD_TIME":"0:00","HOLIDAY":false,"LOCK":false,"LOW_BATTERY":false,"MANUAL_OFF":true,"MODELOCK":false,"MODULATION_LEVEL":0,"OFFLINE":false,"PIN_NUMBER":"0000","PREHEAT_ACTIVE":false,"PRG_TEMP":16,"PRG_TIMER":false,"RECENT_TEMPS":["16.4","16.4","16.5","16.6","16.6","16.6","16.9","16.7","16.9","16.9","17.0","16.8","16.9","16.9","17.1","17.2","17.3","17.2","17.2","17.4","17.3","17.2","17.3","17.2","17.1","17.1","17.1","17.1","17.1","16.9","17.0","17.1","16.9","17.1","17.1","17.0","16.9","17.0","17.0","17.0","16.8","16.9","16.7","16.7","16.8","16.9","16.8","16.8","16.9","16.9","17.0","17.0","17.2","17.1","17.1","17.0","16.9","17.0","16.9","16.8","16.9","17.0","16.9","16.7","16.8","16.9","16.8","16.8","16.8","16.8","16.8","16.9","16.9","16.9","16.8","16.9","16.8","16.8","16.9","16.9","16.7","16.7","16.9","16.4","16.4","16.8","16.7","16.8","16.7","16.8","16.7","16.7","16.7","16.8","16.8","16.9"],"RELATIVE_HUMIDITY":0,"SET_TEMP":"12.0","STANDBY":true,"SWITCH_DELAY_LEFT":"0:00","TEMPORARY_SET_FLAG":false,"THERMOSTAT":true,"TIME":"14:00","TIMER_ON":false,"WINDOW_OPEN":false,"WRITE_COUNT":0,"ZONE_NAME":"Utility"},{"ACTIVE_LEVEL":0,"ACTIVE_PROFILE":0,"ACTUAL_TEMP":"0.0","AVAILABLE_MODES":["heat"],"AWAY":false,"COOL_MODE":false,"COOL_ON":false,"COOL_TEMP":0,"CURRENT_FLOOR_TEMPERATURE":0,"DATE":"sunday","FAN_CONTROL":"Automatic","FAN_SPEED":"Off","FLOOR_LIMIT":false,"HC_MODE":"VENT","HEAT_MODE":true,"HEAT_ON":false,"HOLD_COOL":0,"HOLD_OFF":true,"HOLD_ON":false,"HOLD_TEMP":0,"HOLD_TIME":"0:00","HOLIDAY":false,"LOCK":false,"LOW_BATTERY":false,"MANUAL_OFF":true,"MODELOCK":false,"MODULATION_LEVEL":0,"OFFLINE":true,"PIN_NUMBER":"0000","PREHEAT_ACTIVE":false,"PRG_TEMP":0,"PRG_TIMER":false,"RELATIVE_HUMIDITY":0,"SET_TEMP":"0.0","STANDBY":false,"SWITCH_DELAY_LEFT":"0:00","TEMPORARY_SET_FLAG":false,"TIME":"0:00","TIMECLOCK":true,"TIMER_ON":false,"WINDOW_OPEN":false,"WRITE_COUNT":0,"device":"repeaternode29756"}]}

{"Bathroom":{"COOL_ENABLE":false,"DEADBAND":0,"DEVICE_ID":7,"DEVICE_TYPE":7,"DEW_POINT":false,"FLOOR_LIMIT":28,"FROST_TEMP":12,"MAX_PREHEAT":0,"OUTPUT_DELAY":0,"PUMP_DELAY":0,"RF_SENSOR_MODE":"self","SENSOR_MODE":"BUILT_IN","STAT_FAILSAFE":1,"STAT_VERSION":99,"SWITCHING DIFFERENTIAL":0,"SWITCH_DELAY":0,"SYSTEM_TYPE":0,"TIMESTAMP":1683887523,"ULTRA_VERSION":0,"USER_LIMIT":0,"WINDOW_SWITCH_OPEN":false},"Hallway":{"COOL_ENABLE":false,"DEADBAND":0,"DEVICE_ID":3,"DEVICE_TYPE":7,"DEW_POINT":false,"FLOOR_LIMIT":28,"FROST_TEMP":12,"MAX_PREHEAT":0,"OUTPUT_DELAY":0,"PUMP_DELAY":0,"RF_SENSOR_MODE":"self","SENSOR_MODE":"BUILT_IN","STAT_FAILSAFE":1,"STAT_VERSION":99,"SWITCHING DIFFERENTIAL":0,"SWITCH_DELAY":0,"SYSTEM_TYPE":0,"TIMESTAMP":1683887357,"ULTRA_VERSION":0,"USER_LIMIT":0,"WINDOW_SWITCH_OPEN":false},"Kitchen":{"COOL_ENABLE":false,"DEADBAND":0,"DEVICE_ID":9,"DEVICE_TYPE":7,"DEW_POINT":false,"FLOOR_LIMIT":28,"FROST_TEMP":12,"MAX_PREHEAT":0,"OUTPUT_DELAY":0,"PUMP_DELAY":0,"RF_SENSOR_MODE":"self","SENSOR_MODE":"BUILT_IN","STAT_FAILSAFE":1,"STAT_VERSION":99,"SWITCHING DIFFERENTIAL":0,"SWITCH_DELAY":0,"SYSTEM_TYPE":0,"TIMESTAMP":1683920367,"ULTRA_VERSION":0,"USER_LIMIT":0,"WINDOW_SWITCH_OPEN":false},"Lounge":{"COOL_ENABLE":false,"DEADBAND":0,"DEVICE_ID":1,"DEVICE_TYPE":7,"DEW_POINT":false,"FLOOR_LIMIT":28,"FROST_TEMP":12,"MAX_PREHEAT":0,"OUTPUT_DELAY":0,"PUMP_DELAY":0,"RF_SENSOR_MODE":"self","SENSOR_MODE":"BUILT_IN","STAT_FAILSAFE":1,"STAT_VERSION":99,"SWITCHING DIFFERENTIAL":0,"SWITCH_DELAY":0,"SYSTEM_TYPE":0,"TIMESTAMP":1683887546,"ULTRA_VERSION":0,"USER_LIMIT":0,"WINDOW_SWITCH_OPEN":false},"Office":{"COOL_ENABLE":false,"DEADBAND":0,"DEVICE_ID":5,"DEVICE_TYPE":7,"DEW_POINT":false,"FLOOR_LIMIT":28,"FROST_TEMP":12,"MAX_PREHEAT":0,"OUTPUT_DELAY":0,"PUMP_DELAY":0,"RF_SENSOR_MODE":"self","SENSOR_MODE":"BUILT_IN","STAT_FAILSAFE":1,"STAT_VERSION":99,"SWITCHING DIFFERENTIAL":0,"SWITCH_DELAY":0,"SYSTEM_TYPE":0,"TIMESTAMP":1683887418,"ULTRA_VERSION":0,"USER_LIMIT":0,"WINDOW_SWITCH_OPEN":false},"Utility":{"COOL_ENABLE":false,"DEADBAND":0,"DEVICE_ID":11,"DEVICE_TYPE":7,"DEW_POINT":false,"FLOOR_LIMIT":28,"FROST_TEMP":12,"MAX_PREHEAT":0,"OUTPUT_DELAY":0,"PUMP_DELAY":0,"RF_SENSOR_MODE":"self","SENSOR_MODE":"REMOTE_AIR","STAT_FAILSAFE":1,"STAT_VERSION":99,"SWITCHING DIFFERENTIAL":1,"SWITCH_DELAY":0,"SYSTEM_TYPE":0,"TIMESTAMP":1683887550,"ULTRA_VERSION":0,"USER_LIMIT":0,"WINDOW_SWITCH_OPEN":false}}

**Comment by MindrustUK** [comment]
Thanks for the text output @tbutcher365 , that's really useful although unfortunately it doesn't give me a smoking gun...

As a work around while I try and work this one out, you can try and edit the /config/custom_components/heatmiserneo/manifest.json and set `"requirements": ["neohubapi"=1.0],`

This should revert to the underlying neohubapi to 1.0 and take out the behaviour I've added in 1.1 (which is where I suspect the problem lies), if you can give that a go then remove and re-add the integration, hopefully your issue will be resolved. If you can feed back and let me know it will help with fixing forward.

**Comment by tbutcher365** [comment]
Logger: homeassistant.bootstrap
Source: util/package.py:47
First occurred: 15:25:29 (1 occurrences)
Last logged: 15:25:29

Error setting up integration heatmiserneo - received exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    neohubapi=1.0
             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 40, in is_installed
    pkg_resources.get_distribution(package)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 524, in get_distribution
    dist = Requirement.parse(dist)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3211, in parse
    (req,) = parse_requirements(s)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3170, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    neohubapi=1.0
             ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 101, in async_setup_component
    return await task
  File "/usr/src/homeassistant/homeassistant/setup.py", line 204, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 389, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 284, in _async_process_requirements
    installed, failures = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 113, in _install_requirements_if_missing
    if pkg_util.is_installed(req) or _install_with_retry(req, kwargs):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 47, in is_installed
    req = pkg_resources.Requirement.parse(urlparse(package).fragment)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3211, in parse
    (req,) = parse_requirements(s)
ValueError: not enough values to unpack (expected 1, got 0)

**Comment by MindrustUK** [comment]
Sorry, my bad " in the wrong place, try: `"requirements": ["neohubapi=1.0"],`

**Comment by tbutcher365** [comment]
I think it should be "requirements": ["neohubapi==1.0"], I have updated and now working fine.

**Comment by funks81** [comment]
This seems to have worked for me as wellThanksJonathanSent from my iPhoneOn 15 May 2023, at 15:44, tbutcher365 ***@***.***> wrote:﻿
I think it should be "requirements": ["neohubapi==1.0"], I have updated and now working fine.

**Comment by MindrustUK** [comment]
I've put a sticking plaster in place until I can figure out why this is happening.

**Comment by ntompson** [comment]
This also impacted me when I upgraded from HA 2023.4.x to 2023.5.3. Upgrading to the latest Heatmiser integration with the sticking plaster got it going again.

**Comment by MindrustUK** [comment]
Thanks for the report @ntompson good to have more of a sample of impact. Strange that I can't seem to re-create the issue myself yet.

**Comment by MindrustUK** [comment]
Merging in @albarlow s long standing changes, once these are tested and merged to master. I'll for another branch to test this again.

**Comment by MindrustUK** [comment]
There's been a significant rewrite of this integration and a bump of the underlying neohubapi (Thanks to Andrius Štikonas for hosting and releasing to PyPi) please test: https://github.com/MindrustUK/Heatmiser-for-home-assistant/tree/dev and provide feedback so I can understand if this is still miss-behaving as I cannot replicate this issue myself.

**Comment by MindrustUK** [comment]
Closing, no further feedback.
