### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by elegantrampage** [MindrustUK/Heatmiser-for-home-assistant#133]
Worked flawlessly for me. Really appreciate it. Do you have a buymeacoffee account or anything like that?

**Comment by MindrustUK** [comment]
The master of procrastination that I am, I haven't gotten round to setting up any sort of donation service. I'll leave this ticket open as a reminder to myself to address this at some stage. Thanks for offering your support @elegantrampage  glad this is working well for you!

**Comment by moritonal** [comment]
+1 to this.

**Comment by jameshkm** [comment]
You are an absolute legend! Thank you so much for creating and maintaining this.

**Comment by moritonal** [comment]
Easiest option might be to join Github's [Sponsor](https://github.com/sponsors/accounts) programme

**Comment by MindrustUK** [comment]
Thanks for all the suggestions and support. I've signed up to Github's Sponsor program and will eventually complete the paperwork associated with that. I've also setup [https://ko-fi.com/MindrustUK](https://ko-fi.com/MindrustUK) and [https://liberapay.com/MindrustUK](https://liberapay.com/MindrustUK) as options for those who wish to donate.

If anyone from Heatmiser is reading some more devices to build out a complete hardware test suite to ensure coverage would really help the project, feel free to reach out if you want to help with this.
