### ISSUE TITLE
Accessing thermostat temperatures 

### ISSUE THREAD

**Issue by Winchman93** [MindrustUK/Heatmiser-for-home-assistant#140]
Great integration - solved my problems of integrating my Heatmiser Neo hub after a lot of pain with the built in integration.
 
I’m  however struggling to get access to the current temperature from any thermostat.  It’s clearly passed across but I expected to be able to reference it through sensor.xxxxx - yet no sensors appear to be defined for the temperatures.  

Appreciate any advice on how to reference the temperatures

**Comment by MindrustUK** [comment]
You'll find it under a climate entity "climate.xxxx" and attribute current_temperature.

Hope that helps.

**Comment by Winchman93** [comment]
Thanks for the feedback.
