### ISSUE TITLE
Feature: Add support for Door/window Contact

### ISSUE THREAD

**Issue by ceee5** [MindrustUK/Heatmiser-for-home-assistant#141]
Hi,

Firstly thanks for providing this application to allow me to use our Heatmiser installation alongside Home Assistant.

We have the Heatmiser Door/Window sensor paired with our neonultra.

Whilst I can see the entity appear, it doesn't appear to recognise any change in state, ie when the door is opened - albeit the Heatmiser application recognises it and turns off the heat call whilst activated.

Am I missing something?

Thanks

Jon

**Comment by MindrustUK** [comment]
Don't think you've missed anything. These are likely not handled correctly, I'll order a sensor and do some investigation into adding support. I've got an outstanding ticket to pickup around adding temperature sensor support too but I've been struggling for time to complete it.

Watch this space for updates.

M.

**Comment by ceee5** [comment]
Please let me know if I can help in anyway.
Many thanks

**Comment by MindrustUK** [comment]
Got the sensors through, I've added them as my setup and they suffer the same limitation of https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/121

I Need to revisit neohubapi 1.1 and figure out why this is breaking for some users.

We can then add the devices using "DEVICE_TYPE" and "TIMECLOCK_MODE" to get them into the right class; switches, sensors, thermostats, time clocks etc.

These should then appear as binary sensors, not switches. NB: don't forget to add some sort of "LOW_BATTERY" support as an entity or sensor.

**Comment by MindrustUK** [comment]
Support for Wireless Air Sensors and Wireless Contact Sensors have been added to: https://github.com/MindrustUK/Heatmiser-for-home-assistant/tree/dev please test and provide feedback.

**Comment by ceee5** [comment]
Thanks for the update

I have followed the instructions to install the dev branch to test this new feature, however the Wireless Contact Sensor still reports as a switch and doesn't change state when activated. 

I wonder if the dev branch is installed correctly?  Is there a way of checking - I can't see anything obvious. 

Many thanks 
Jon

**Comment by MindrustUK** [comment]
Did you restart home-assistant after installing? The big clue will be that things look quite a bit different if it's loaded correctly.

**Comment by ceee5** [comment]
Thanks for the clue! It hadn't loaded!
For some reason when pasting the script into ssh it was inserting a random ~, hence the script errored.
I'll let you know how the contact switch works!
Thanks again

**Comment by ceee5** [comment]
Basic checks all looks good with this feature request, thanks @MindrustUK 

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/50208651/eb3e3c7c-5c99-4a81-a62e-e0765e83e020)

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/50208651/6cdd340f-68e8-4929-8b91-408354c2f6ed)

Now for an automation to play a recording of "Shut the Door" on repeat when the kids go out to play in the snow and leave the door open!

**Comment by MindrustUK** [comment]
Great, thanks for the update @ceee5 I'll close this feature complete.
