### ISSUE TITLE
Help with hold feature.

### ISSUE THREAD

**Issue by jimbray2701** [MindrustUK/Heatmiser-for-home-assistant#147]
Hi, Sorry my programming skills are not great. I've got the Neo system all installed and can control the temperatures etc. but I would love to set the hold and hold time and each thermostat. Has any body integrated this on Lovelace and which would be the best way?

**Comment by MindrustUK** [comment]
Hi, Please see this thread: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/9 I'm in the process of a sizable rewrite which should surface this as an optional button on screen depending on configuration. In the mean time the linked thread should help you until this is available.
