### ISSUE TITLE
Bug: neoStat as timer stops working properly 

### ISSUE THREAD

**Issue by anarkikrzysiek** [MindrustUK/Heatmiser-for-home-assistant#148]
Hi . 

After last update I lost functionality to turn on timer (by default was turning on for 30mins). 
After update it is going on for few secs and turning off. (state readings works fine - HA knows when timer has been on/off by Heatmiser scheadule etc). I dont have thermostats so have no idea is there are some other problems 
Updated from version 6cfaaf1 to version 22898cf

I had Full HA backup, so after restore everything is working fine. 
I have no idea is that can be connected to information that I have neoHub gen 1, but it is good to mention about it :)

**Comment by JohnBenfield** [comment]
I have the same issue as well.  My hot water is triggered via a schedule helper and automations.  Basically the hot water is coming on for a few seconds and then turn straight off.  I also have a gen1 hub.

**Comment by MindrustUK** [comment]
Looks like: https://github.com/MindrustUK/Heatmiser-for-home-assistant/commit/3f14ad672c146e7e7102c502ed541dbe9e01afe3 may be responsible for this. I've reverted the behaviour for now and will revisit once I have the new release available.

**Comment by JohnBenfield** [comment]
I manually updated my local code to match your changes and this appears to have resolved the issue for me.  Thanks.

**Comment by MindrustUK** [comment]
Closing resolved.
