### ISSUE TITLE
Feature: Add Preheating status (simple solution tested)

### ISSUE THREAD

**Issue by iandarbey** [MindrustUK/Heatmiser-for-home-assistant#149]
Hi,

Currently the thermostats can only report heating or idle via the integration.

By adding
        elif bool(self.data.preheat_active) == True:
            return "preheating"
After line 230 of climate.py (I have neostat V2) the integration can correctly return preheating as opposed to just heating or idle status.

Points to note - I note the home assistant Dev documentation notes CURRENT_HVAC_HEAT and others with the prefix CURRENT*  have been deprecated but I was unable to import PREHEATING from the constants in HA (my approach may have been wrong) and use that instead of the "preheating" string (they ultimately are equivalent as an end product though.

I've tested adding this to my own setup and it has worked across each of my thermostats that have called Preheating in the last few hours. You can see preheating as a status on the climate entity and associated cards.
Unfortunately "preheating" doesn't show up in a similar fashion to the "heating" status on a climate history graph card but at the very least I can see a preheating call and understand a sudden temp rise when the set point hasn't changed. I'm going to have a look at the history graph code in HA and see if I can make a request there that would have preheating appear similar to "heating" but perhaps in a different colour.

**Comment by MindrustUK** [comment]
Hi @iandarbey Thanks for contributing this. I'm going to pass over any further work on this branch for the moment as I'm concentrating on a new release which has already addressed this issue. Hopefully I'll find the time to finish it and get the first beta released to all sooner rather than later. I'll leave the ticket open for feedback to ensure this feature is correct in the new version.

**Comment by iandarbey** [comment]
I got it working properly by importing HVACAction and then using HVACAction.PREHEATING

New to python so didn't realise I couldn't use PREHEATING without importing HVACAction first.

**Comment by iandarbeynhiu** [comment]
> This should've been addressed as part of the current dev branch: https://github.com/MindrustUK/Heatmiser-for-home-assistant/tree/dev HVACAction and HVACMode have both had an overhaul which should make them more in line with Home Assistant expects them to work. Please test and provide feedback.

It looks fine to me in terms of the HVAC mode and classes being used instead of the prior method.

**Comment by MindrustUK** [comment]
Thanks for confirming. Closing as complete.
