### ISSUE TITLE
Invalid config: heatmiserneo.switch could not be set up

### ISSUE THREAD

**Issue by PhillyGilly** [MindrustUK/Heatmiser-for-home-assistant#151]
On latest version of Heatmiser but upgrade of HA to core 2023.11.2  and/or supervisor to 2023.11.3 has knocked out my hot water and towel rail switches.
![224C48CB-07A6-422F-B8E2-E31A94A539E1](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/56273663/1f2a79b6-8fac-424e-9a83-bd0f373a39ff)
![F589AAE9-7FDF-4CC9-8C58-F5C079F5B206](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/56273663/fb388055-4569-4dad-8866-99e0559a223c)

**Comment by MindrustUK** [comment]
I can't replicate this on my side, versions are all a match.

Please post your logs.

**Comment by PhillyGilly** [comment]
I reinstalled and all is good now. Sorry.
I suspect that this was caused by corruption in switch.py a week back when I was looking at line 53
``` self._holdfor = 30 ```
I didn't change or save anything but perhaps the corruption wasn't noticed until I restarted following the recent releases?
