### ISSUE TITLE
Myson Touch2 Wifi

### ISSUE THREAD

**Issue by luke6187** [MindrustUK/Heatmiser-for-home-assistant#152]
Hello,

Thank you for creating this. Will it work with the Myson (I think rebranded Heatmiser) Touch2 Wifi hub? 

Thanks,
Luke

**Comment by MindrustUK** [comment]
Via this link it looks compatible: http://faq.heatmisershop.co.uk/3791318/Will-this-hub-work-with-rebranded-thermostats-from-Myson-They-look-exactly-the-same

I've had success using re-branded Nu-heat thermostats in my testing, I haven't tried rebranded hubs.

The easiest way to see if this will work or not is to try the add-on. If you get in trouble or it doesn't work feel free to re-open the issue and we can run through some troubleshooting and see if we can make it work.
