### ISSUE TITLE
Observation: NeoStat-HW operation in Dev Branch

### ISSUE THREAD

**Issue by ceee5** [MindrustUK/Heatmiser-for-home-assistant#153]
As part of my Heatmiser installation I have a neoStat-hw V2 - Hot Water Programmer. One  use case is to detect when the hot water is being called to initiate an automation.

I might be missing something obvious, however I thought it would be prudent to raise this initially as an observation. 

Whilst evaluating the dev branch, the automation I had working is no longer triggered as there is no trigger available.

Here is the device info reported by HA:

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/50208651/81f5b3d1-b9cd-4a99-8eb8-c0660b78d9ea)

with the available automation start criteria

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/50208651/66fab2b6-910a-4170-9314-73b709da1ddd)

Compared to the release branch 

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/50208651/8e6d2969-17d8-43ca-8eba-0be3605dd9bd)

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/50208651/04572547-d170-49dd-8945-139c3ff8baeb)

On the dev branch the Control option for  the switch is no longer available.

Looking at the available options to trigger the automation, only Hold and timer settings are rendered and nothing related to the  overall On Off status

I am not sure  what is expected in this release, however please see some observations:

1. neoStat-hw and neoStat  both report as 'Device Type: 12', the API documentation confirms there isn't a specific Device for the HW.

2. When comparing to a Neo Plug, resolving to Device Type 6 and presents the timer, hold and switch options 

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/50208651/c9f174ea-615a-4a4a-9a6d-4465b9e623e3)

along with the corresponding Automation Options

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/50208651/7244d460-7d13-47fc-b75d-d510ea75d743)

Not sure if this helps for the neoStat-hw, neo plug and neoStat

{
			"AWAY": false,
			"COOLING": false,
			"COOLING_ENABLED": false,
			"COOLING_TEMPERATURE_IN_WHOLE_DEGREES": 111,
			"COOL_INP": false,
			"COUNT_DOWN_TIME": "0:00",
			"CRADLE_PAIRED_TO_REMOTE_SENSOR": false,
			"CRADLE_PAIRED_TO_STAT": false,
			"CURRENT_FLOOR_TEMPERATURE": 127,
			"CURRENT_SET_TEMPERATURE": "239.5",
			"CURRENT_TEMPERATURE": "19.4",
			"DEMAND": false,
			"DEVICE_TYPE": 12,
			"ENABLE_BOILER": false,
			"ENABLE_COOLING": false,
			"ENABLE_PUMP": false,
			"ENABLE_VALVE": false,
			"ENABLE_ZONE": false,
			"FAILSAFE_STATE": false,
			"FAIL_SAFE_ENABLED": false,
			"FLOOR_LIMIT": false,
			"FULL/PARTIAL_LOCK_AVAILABLE": false,
			"HEAT/COOL_MODE": false,
			"HEATING": false,
			"HOLD_TEMPERATURE": 1,
			"HOLD_TIME": "0:00",
			"HOLIDAY": false,
			"HOLIDAY_DAYS": 0,
			"HUMIDITY": 0,
			"LOCK": false,
			"LOCK_PIN_NUMBER": "0000",
			"LOW_BATTERY": false,
			"MAX_TEMPERATURE": "255.255",
			"MIN_TEMPERATURE": "255.255",
			"MODULATION_LEVEL": 0,
			"NEXT_ON_TIME": "1 days 17:00",
			"OFFLINE": false,
			"OUPUT_DELAY": false,
			"OUTPUT_DELAY": 0,
			"PREHEAT": false,
			"PREHEAT_TIME": "255:255",
			"PROGRAM_MODE": "7DAY",
			"PUMP_DELAY": false,
			"RADIATORS_OR_UNDERFLOOR": false,
			"SENSOR_SELECTION": "BUILT_IN_AIR_SENSOR",
			"SET_COUNTDOWN_TIME": 0,
			"STANDBY": false,
			"STAT_MODE": {
				"4_HEAT_LEVELS": true,
				"MANUAL_OFF": true,
				"TIMECLOCK": true
			},
			"TEMPERATURE_FORMAT": false,
			"TEMP_HOLD": false,
			"TIMECLOCK_MODE": false,
			"TIMER": false,
			"TIME_CLOCK_OVERIDE_BIT": false,
			"ULTRA_VERSION": 0,
			"VERSION_NUMBER": 33,
			"WRITE_COUNT": 91,
			"ZONE_1PAIRED_TO_MULTILINK": true,
			"ZONE_1_OR_2": false,
			"ZONE_2_PAIRED_TO_MULTILINK": false,
			"device": "Hot Water"
		},
		{
			"AWAY": false,
			"COOLING": false,
			"COOLING_ENABLED": false,
			"COOLING_TEMPERATURE_IN_WHOLE_DEGREES": 0,
			"COOL_INP": false,
			"COUNT_DOWN_TIME": "0:00",
			"CRADLE_PAIRED_TO_REMOTE_SENSOR": false,
			"CRADLE_PAIRED_TO_STAT": false,
			"CURRENT_FLOOR_TEMPERATURE": 127,
			"CURRENT_SET_TEMPERATURE": "0.0",
			"CURRENT_TEMPERATURE": "255.255",
			"DEMAND": false,
			"DEVICE_TYPE": 6,
			"ENABLE_BOILER": false,
			"ENABLE_COOLING": false,
			"ENABLE_PUMP": false,
			"ENABLE_VALVE": false,
			"ENABLE_ZONE": false,
			"FAILSAFE_STATE": false,
			"FAIL_SAFE_ENABLED": false,
			"FLOOR_LIMIT": false,
			"FULL/PARTIAL_LOCK_AVAILABLE": false,
			"HEAT/COOL_MODE": false,
			"HEATING": false,
			"HOLD_TEMPERATURE": 0,
			"HOLD_TIME": "0:00",
			"HOLIDAY": false,
			"HOLIDAY_DAYS": 0,
			"HUMIDITY": 0,
			"LOCK": false,
			"LOCK_PIN_NUMBER": "0000",
			"LOW_BATTERY": false,
			"MAX_TEMPERATURE": "255.255",
			"MIN_TEMPERATURE": "255.255",
			"MODULATION_LEVEL": 0,
			"NEXT_ON_TIME": "255 days 255:255",
			"OFFLINE": false,
			"OUPUT_DELAY": false,
			"OUTPUT_DELAY": 0,
			"PREHEAT": false,
			"PREHEAT_TIME": "255:255",
			"PROGRAM_MODE": "7DAY",
			"PUMP_DELAY": false,
			"RADIATORS_OR_UNDERFLOOR": false,
			"SENSOR_SELECTION": "BUILT_IN_AIR_SENSOR",
			"SET_COUNTDOWN_TIME": 0,
			"STANDBY": false,
			"STAT_MODE": {
				"4_HEAT_LEVELS": true,
				"MANUAL_ON": true,
				"TIMECLOCK": true
			},
			"TEMPERATURE_FORMAT": false,
			"TEMP_HOLD": false,
			"TIMECLOCK_MODE": false,
			"TIMER": true,
			"TIME_CLOCK_OVERIDE_BIT": true,
			"ULTRA_VERSION": 0,
			"VERSION_NUMBER": 81,
			"WRITE_COUNT": 39,
			"ZONE_1PAIRED_TO_MULTILINK": true,
			"ZONE_1_OR_2": false,
			"ZONE_2_PAIRED_TO_MULTILINK": false,
			"device": "Hot Water Tap"
		},
		{
			"AWAY": false,
			"COOLING": false,
			"COOLING_ENABLED": false,
			"COOLING_TEMPERATURE_IN_WHOLE_DEGREES": 18,
			"COOL_INP": false,
			"COUNT_DOWN_TIME": "0:00",
			"CRADLE_PAIRED_TO_REMOTE_SENSOR": false,
			"CRADLE_PAIRED_TO_STAT": false,
			"CURRENT_FLOOR_TEMPERATURE": 127,
			"CURRENT_SET_TEMPERATURE": "17.0",
			"CURRENT_TEMPERATURE": "16.5",
			"DEMAND": false,
			"DEVICE_TYPE": 12,
			"ENABLE_BOILER": false,
			"ENABLE_COOLING": false,
			"ENABLE_PUMP": false,
			"ENABLE_VALVE": false,
			"ENABLE_ZONE": false,
			"FAILSAFE_STATE": false,
			"FAIL_SAFE_ENABLED": false,
			"FLOOR_LIMIT": false,
			"FULL/PARTIAL_LOCK_AVAILABLE": false,
			"HEAT/COOL_MODE": false,
			"HEATING": false,
			"HOLD_TEMPERATURE": 11,
			"HOLD_TIME": "0:00",
			"HOLIDAY": false,
			"HOLIDAY_DAYS": 0,
			"HUMIDITY": 0,
			"LOCK": false,
			"LOCK_PIN_NUMBER": "0000",
			"LOW_BATTERY": false,
			"MAX_TEMPERATURE": "19.0",
			"MIN_TEMPERATURE": "17.0",
			"MODULATION_LEVEL": 0,
			"NEXT_ON_TIME": "1 days 19:30",
			"OFFLINE": false,
			"OUPUT_DELAY": false,
			"OUTPUT_DELAY": 0,
			"PREHEAT": false,
			"PREHEAT_TIME": "255:255",
			"PROGRAM_MODE": "7DAY",
			"PUMP_DELAY": false,
			"RADIATORS_OR_UNDERFLOOR": false,
			"SENSOR_SELECTION": "BUILT_IN_AIR_SENSOR",
			"SET_COUNTDOWN_TIME": 0,
			"STANDBY": false,
			"STAT_MODE": {
				"4_HEAT_LEVELS": true,
				"MANUAL_OFF": true,
				"THERMOSTAT": true
			},
			"TEMPERATURE_FORMAT": false,
			"TEMP_HOLD": false,
			"TIMECLOCK_MODE": false,
			"TIMER": false,
			"TIME_CLOCK_OVERIDE_BIT": false,
			"ULTRA_VERSION": 0,
			"VERSION_NUMBER": 33,
			"WRITE_COUNT": 8,
			"ZONE_1PAIRED_TO_MULTILINK": true,
			"ZONE_1_OR_2": false,
			"ZONE_2_PAIRED_TO_MULTILINK": false,
			"device": "Front Lounge"

Many thanks 

J

**Comment by MindrustUK** [comment]
Hi @ceee5 Thanks for the feedback!

Unfortunately I don't have a neoStat-hw V2 in my arsenal to test with, but from what I can observe it's effectively a NeoStat V2 forced into timeclock mode. Please correct me if this is wrong?

With this in mind, my understanding is there's no "On / Off" mode as there would be with a NeoPlug. From what I understand of the API docs the NeoPlug device is the only device to implement a true On/Off State. Checking the Heatmiser Android app, I can see that a NeoStat V2 in Timeclock mode presents "Auto" "Override" (With a time requirement) and "Standby".

The current 'main' branch logic is to present a 'boost' style switch using the following code rather than a true on / off under manual control:

`self._holdfor = 30`
and
`if self._type == NEO_STAT:
            response = await self._timer.set_timer_hold(value, self._holdfor if value else 0)`

This is a bit of a hack as it stands, although I assume it's satisfying your use case?

I plan on adding a service to address this (Being able to call hold with a desired duration), but as it stands the easiest way to replicate the existing logic is to just hold for 30 minutes at a time from the UI.

It's entirely possible that I've missed something? but given the above I'm keen not to deviate from the intrinsic Heatmiser design, much as on a personal level I'd rather just make everything "On / Off" and delegate the logic to Home-Assistant which is where automation logic should ultimately sit.

If you can give me some further information on your use case, there maybe other ways to meet your needs?

**Comment by ceee5** [comment]
Hi @MindrustUK , thanks for your update.

In answer to my Use Case:

I want to control the flow temperature of my system boiler. 
- on the assumption that the the boiler is more efficient at a lower temp (we have UFH) 
- higher temperature prevents legionella in the HW cylinder.

My solution is simple, 
- when the hotwater is called using the neostat-hw, an automation sets the boiler flow temp to 65degC 
- when the hotwater/neostat-hw is turned off an automation sets the boiler to 55degC.
An [EMS ESP](https://emsesp.github.io/docs/)  controls the boiler
This solution makes no physical changes to the standard Heatmiser App and associated  heating controls; the system will operate without HA running.

Your  assumption that the neo-stat HW is a neoStat in Timeclock mode is my understanding too,  the back plate differs as it has changeover contacts for the Hot Water controls.

If I can help with testing, I have a Neo Ultra, NeoStats, NeoStat-E, NeoStat-HW, NeoPlug and Door/Window Sensor as part of my system.

Thanks J

**Comment by MindrustUK** [comment]
Thanks for more information @ceee5 

A very interesting setup you have there, the take away I'm getting is you're fundamentally looking to attain the state of the neostat-hw which boils down to (forgive the pun) "On | Heating" and "Off | Idle". So if the boiler is on and heating the flow temp from the system boiler should be 65 and if it's idle then the system boiler should only run at 55.

With regards to the operation as I understand it in your current setup; this really translates to the hold state active or not (Which is provided by a sensor) with one caveat: [https://dev.heatmiser.com](https://dev.heatmiser.com/t/timer-hold-on-timer-hold-off-vs-hold-on-hold-off-behavior/922) as per this forum post.

Heatmiser appear to allow configurable Hold behaviours. As the system is designed stand alone, they would expect end users to setup profiles for the stat to be on and off, and hold to override this for a set time. You can hold in multiple states. "Hold ON|Active | High" or "Hold Off | Inactive | Low", Unfortunately the API only reflects that a hold is active or not, and not the state of the hold High/Low. In your case you can assert this as always active high and report on that, as you set the hold state this means you can just report back on if hold is active or not.

By adding a service to set "Hold Active, Hold State, For Time" this should cover what you need provided you're only using the neostat-hw as a hold switch.

I'm not sure what we can do about retrieving the active state if the timer is in "normal" timer operation mode. I'll do some investigation on that, from memory this also appears as a timer, I'll investigate regardless.

**Comment by MindrustUK** [comment]
Following some investigation, it looks like "Timer_on" reflects if the output of the timer is on. I'll add this as a sensor.

Given the above this probably means your logic will look something like:

`If Hold Active or Timer On:
  # HotWaterActive
  set temperature 65
Else:
  set temperature 55`

Does this make sense?

**Comment by MindrustUK** [comment]
@ceee5 Just pushed an additional sensor "Timer Output Active" into the dev branch which should now cover your use case. Can you give this a test and let me know how you get on?

**Comment by ceee5** [comment]
Thanks @MindrustUK, have will have a look and feedback accordingly. J

**Comment by MindrustUK** [comment]
Sorry, only just noticed this reply now @ceee5 I'll take a look into the availability and try and create some uniform behaviour across the board next time I'm looking at the code for this project. Glad to hear it's working near enough as expected.

**Comment by Liam-Whiteside** [comment]
Is there a way to enable the HW from HA with the dev branch at the moment?

**Comment by MindrustUK** [comment]
Hi @Liam-Whiteside Can you expand on this? My assumption is that your asking about the Neostat-HW device? As above this is identified as device type 12 which is the same device as the neostat v2. If this is operating in time clock mode you should be able to use any of the timer functions available in the dev branch to enable the hot water relay. Please try and expand on abbreviations and be explcit to make your question easier to answer.

**Comment by Liam-Whiteside** [comment]
Yes it’s the Neostat HW device.
I can see two switches in the HA UI for the HW device, plus two fields where I can enter hold time in hours or minutes.
If I enable the “Heatmiser NeoStat V2 Hold State” switch I get a service error.
If I enable the “Heatmiser NeoStat V2 Timer Hold” switch nothing appears to happen. 
If I enter a time, it seems to then refresh and clear the field.
The HW sensor shows the correct state. But there doesn’t appear to be a way to enable the HW, either just manually turning it on, or enabling the override for a set time from the UI.

**Comment by stever29** [comment]
> With this in mind, my understanding is there's no "On / Off" mode as there would be with a NeoPlug. From what I understand of the API docs the NeoPlug device is the only device to implement a true On/Off State. Checking the Heatmiser Android app, I can see that a NeoStat V2 in Timeclock mode presents "Auto" "Override" (With a time requirement) and "Standby".

Hello, and thanks for all your hard work on this

I guess this is a slightly different use case to what's being asked above (i.e. when the water is actually switched on) but it would also be super useful to effectively have an on/off switch for the HW unit which is mapped into Auto/Standby. I've been doing this on a fork (of the main branch) and it uses the 'set_frost' function. The use case for me is being able to turn off the timer/hot water schedule entirely. I particularly do this when I'm on holiday to stop the boiler firing up constantly to heat the cylinder. Here's my fork if it's helpful: https://github.com/MindrustUK/Heatmiser-for-home-assistant/compare/master...stever29:Heatmiser-for-home-assistant:master?expand=1

Would you be able to include this functionality in the re-write?

Thanks again,

**Comment by Liam-Whiteside** [comment]
> If you enter Hours, Minutes and then toggle "Hold" (Note not hold state) this should enable the relay for the specified time. The data entry fields will clear and the "hold time remaining" should update.

Thanks. It was partly I was getting confused with the separate hours and minutes fields. I think initially the values may be null, so it's not until you set them both once that it will work. ie initially after a HA restart you get this error:

```
  File "/config/custom_components/heatmiserneo/switch.py", line 450, in async_turn_on
    total_hold_minutes = int((self._neostat.hold_hours * 60) + self._neostat.hold_mins)
                              ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

If I set values hours=0 and minutes=5, then toggle Timer Hold on. I can see the timer value appear as "Hold Time Remaining" which counts down (in minutes, the seconds value is always :00) but the output doesn't actually switch on.
It appears that you need to also have "Timer Hold State" on to enable the output while the countdown timer is running.

Using the Heatmiser app you can press "On" or "Override" at which point the output turns on and it defaults to counting down 1 hour. In the HA integration, the "Timer Hold" shows it's on and the sensors, however "Hold State" remains off.

As @stever29 has said, there's not currently any access to enable the STANDBY option to disable the scheduled switching times.

Having just restarted HA, I'm now back to getting errors all the time when I try and turn Timer Hold on.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:49:12 (13 occurrences)
Last logged: 21:57:40

[134713167649168] Unexpected exception
[134713038519120] Unexpected exception
[134713038519264] Unexpected exception
[134713051661504] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/switch.py", line 450, in async_turn_on
    total_hold_minutes = int((self._neostat.hold_hours * 60) + self._neostat.hold_mins)
                              ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by MindrustUK** [comment]
Thanks for the offer of help @stever29 I'll certainly add your request to the dev branch. I (Hopefully) fixed frost / standby mode yesterday so that's a start. I'll check out your code and see what I can port into the current re-write.

@Liam-Whiteside Thanks for the continued bug reporting / testing. I'll have to add some conditions to handle null values, in general it looks like I need to revisit hold functionality and give it a lot more attention when I get a minute.

**Comment by stever29** [comment]
Thanks very much @MindrustUK. I did just hack together the code on that fork.. it was mainly a copy/paste to achieve the functionality, so I wouldn't concentrate too much on the code itself, just looking for the same functionality. 

I'm also happy to switch to the dev branch to help test (I'm running a neo ultra, 3 neostat v2's, 4 neostat-e v2's, 2 neoPlugs, and the neostat-hw v2 so have a good spread of things to help)... what's the easiest way to switch branch without removing/re-adding everything?

**Comment by stever29** [comment]
Thanks @MindrustUK - I've tested a number of times this evening (both while the timer is on and off) and the standby functionality is working perfectly. Appreciate the super quick turnaround!

**Comment by MindrustUK** [comment]
Closing: complete.
