### ISSUE TITLE
Bug: Filter out values over 100 degrees

### ISSUE THREAD

**Issue by heisenberg2980** [MindrustUK/Heatmiser-for-home-assistant#155]
I know this is not an issue with the integration as the Heatmiser app also show these values, but every time the hub loses its connection it produce a peak of over 100 degrees (127 sometimes, 255 others) that is pretty anoying in the graph as it completely changes the scale, and I think it could be filtered out in this integration as we know temperatures over 100 degrees are imposible:

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/58039006/b0048afe-e0fa-4e24-b447-83952dff47c9)

**Comment by MindrustUK** [comment]
Are you observing this in the development branch at all? I suspect as the "offline" state is now handled correctly this may no longer be an issue. Can you test and report back, if it's still an issue I'll look into adding in some mitigation for this.

**Comment by heisenberg2980** [comment]
How can I test the development branch in Home Assistant?

**Comment by heisenberg2980** [comment]
Testing now with development branch, will keep you posted

**Comment by heisenberg2980** [comment]
Unfortunately the issue is also happening in the development branch:

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/58039006/38f93c70-f384-48af-8251-1b259fba32ce)

**Comment by w00tadude** [comment]
Also happens to me. Happy to help debug if needed.

**Comment by MindrustUK** [comment]
Have added some handling that will record the error and will not return a value should it encounter 127 or 255. @heisenberg2980 @w00tadude Could you please test and feedback?

**Comment by MindrustUK** [comment]
Hi @heisenberg2980 you can check https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/dev/README.md for installation instructions, specifically:

`mkdir -p /config/custom_components
cd /tmp/
git clone -b dev https://github.com/MindrustUK/Heatmiser-for-home-assistant /tmp/heatmiserneo
mv /tmp/heatmiserneo/custom_components/heatmiserneo /config/custom_components/
rm -rf /tmp/heatmiserneo/`

**Comment by heisenberg2980** [comment]
@MindrustUK I just tested the dev version and I´m afraid the issue is still there. I realised the temperature reads 255.3 instead of 255, could that be the reason your "if temperature = 255" doesn´t pick it up? If that is the case, could you update it to "if temperature is over 100" as any temperature over 100 degrees must be incorrect?

![image](https://github.com/user-attachments/assets/0716d980-d5c3-40d7-8e52-9c6ee4b5a180)

**Comment by MindrustUK** [comment]
Thanks @heisenberg2980 that's mildly annoying, I wanted to use those specific values to trigger error events, Oh well... I'll modify the code to treat anything above 45 deg C as an error. I believe this is the upper range for all Heatmiser products but will verify, I'll apply the same sort of idea to the lower limit and add some magic to deal with Fahrenheit. Will ping once this is added in.

**Comment by heisenberg2980** [comment]
@MindrustUK 45 degrees sounds a bit low to me, as the temperature can reach higher temperatures than that, but yeah, once you confirm the values the thermostat can report you can adjust the module accordingly.

Btw, thank you very much for your effort in fixing this issue.

**Comment by w00tadude** [comment]
In my case the spikes use to be of 127.3C

I think that capping it at a high value (don't mind if it's 50, 80 or 100) would work fine for me.

![image](https://github.com/user-attachments/assets/00848fe0-ed3c-4b17-8d86-94a0857296d3)

**Comment by MindrustUK** [comment]
Hi @heisenberg2980 @w00tadude I've updated the code with some more robust logic, it will now;

- check for < 0 Deg C or > 70 Deg C
- check for < 32 Deg F or > 158 Deg F

On these conditions it will not return a temperature and will raise an error in the logger.

Please can you test the latest version of the dev branch and let me know if it's working as expected?

**Comment by heisenberg2980** [comment]
@MindrustUK I confirm the issue is fixed in the updated version and the 255 values don´t appear in HA anymore, thank you very much!

Just a note (and I´m sorry if I am being a pain), I think we shouldn´t filter negative values, as even though it is unlikely a room reaches those values, I am pretty sure the thermostat is capable of reporting them if it happens. I´m not sure if filtering negative values is needed at all, because I have only seen issues with values over 100 degrees, but if you want to filter them maybe a value of -50 Celsius would be better?

**Comment by MindrustUK** [comment]
@heisenberg2980 It's a sensible observation. I've updated the values, we'll now handle -50 Deg C / -58 Deg F as the lower limit. I'll call this one done unless you've got any other observations?

**Comment by heisenberg2980** [comment]
Issue has been fixed in the dev branch

**Comment by heisenberg2980** [comment]
@MindrustUK the issue of the spike in temperature has happened again, has there been any change to your fix?

![image](https://github.com/user-attachments/assets/34b2f381-6721-479f-8ec2-e34485f2c148)

**Comment by MindrustUK** [comment]
Hi @heisenberg2980 How odd, no changes have been made that should affect this... Can you check your climate.py file and ensure the change is there to check for temperature validity and hasn't accidentality been over written or something odd?

**Comment by heisenberg2980** [comment]
I think I found the answer as this integration was updated 2 days ago and must have overwritten the dev version I had manually downloaded, has this fix not made it to the HACS version of the component yet?

![image](https://github.com/user-attachments/assets/518ef153-0f9a-4116-80c5-fd0f966f7ec2)

**Comment by MindrustUK** [comment]
No I've not applied this to the main branch. I've got an immediate (read within a month I hope) plan to push a "Version 1.5" branch to main. Which will bring a lot of fixes as well as enabling this for HACS users. In the interim I suggest running the dev branch and disabling the repo in HACS.
