### ISSUE TITLE
Bug: Invalid argument error when changing SET_HC_MODE from FROST.

### ISSUE THREAD

**Issue by tk200** [MindrustUK/Heatmiser-for-home-assistant#157]
Hi,

Thanks for all your continued work on this! I am getting an intermittent error when Home Assistant attempts to set the Neo thermostat back to ‘heat’ from ‘off’.

**Version**
0d4905c

**Error**

Logger: neohub Source: runner.py:188  First occurred: 12:49:43 (2 occurrences)  Last logged: 12:49:43
* [1] Unexpected reply: namespace(error='Invalid second argument to SET_HC_MODE should be a valid device or array of valid devices') for message: {'SET_HC_MODE': ['HEATING', ['Cloakroom']]}
* [1] Unexpected reply: namespace(error='Invalid argument to FROST_OFF, should be a valid device or array of valid devices') for message: {'FROST_OFF': ['Cloakroom']}

**Description**
I have Home Assistant set to track whether at home or not, and either set the Neostat to ‘off’ or ‘heat’ accordingly. Most of the time this works fine, but this error comes up regularly, although the Neostat does change to ‘heat’ - in the case of this error message 3 mins later without any further system calls or errors.

![IMG_0778](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/54744256/b682d339-f96c-4a70-9497-620ac1433807)

**Comment by MindrustUK** [comment]
Thanks for the report! I'll take a look at this when I'm next working on the project.

**Comment by MindrustUK** [comment]
@tk200 Can you also confirm is this happening on the dev of main branch?

**Comment by tk200** [comment]
> @tk200 Can you also confirm is this happening on the dev of main branch?

I’ll try and run the dev branch later and see if the error shows up.

**Comment by tk200** [comment]
> @tk200 Can you also confirm is this happening on the dev of main branch?

Sorry - just read this again… Was the query which branch am I running (I’m on the main branch) or can I try the dev branch to see if the error still exists?

**Comment by MindrustUK** [comment]
It was both, I wanted to know if you were on the main branch. If so try the dev branch and see if it still happens there. Dev has a lot of changes and fixes so I may have covered this there, if not I'll need to capture it in my todo list.

**Comment by heisenberg2980** [comment]
@MindrustUK I am getting a similar error "Unsupported hvac mode: None" in the dev branch when trying to turn off the heating, should I open a new defect or will it be fixed when you fix this one?

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/58039006/42cb3aa4-f47d-4e90-9d2c-0f364666539f)

**Comment by MindrustUK** [comment]
Thanks for the report, I'll investigate the unsupported hvac mode as part of this ticket.

**Comment by MindrustUK** [comment]
Hi @tk200 Please pull the latest version of the dev branch and let me know if this is now working for you.

**Comment by tk200** [comment]
> Hi @tk200 Please pull the latest version of the dev branch and let me know if this is now working for you.

Will do - thanks for the continued work! Can I just replace the existing custom_components/heatmiserneo directory with the dev branch version and restart? And then if I need to revert put the original files back and restart?

**Comment by MindrustUK** [comment]
Hi @tk200 Unfortunately due to the volume of changes in the dev branch this will probably cause some degree of mayhem in the short term, personally I'd say it's worth it but I'm bias for obvious reasons. I'd advise looking at it more as a migration than a drop in replacement. If you can spawning a virtual machine to test things before fully committing maybe a good way to test.

**Comment by tk200** [comment]
OK - no worries. Happy to take the leap - is it still a case of replacing all the files in the custom_components directory?

**Comment by MindrustUK** [comment]
Sorry, should've clarified that earlier. Yes it is, be sure to follow the readme in the dev branch as you need to use the `git clone -b dev https://github.com/MindrustUK/Heatmiser-for-home-assistant /tmp/heatmiserneo` to ensure you clone the right branch.

**Comment by tk200** [comment]
Have been running the dev branch for a couple of weeks now, and it seems to be behaving - nothing untoward in the logs. Many thanks!

**Comment by MindrustUK** [comment]
Closing, appears to be complete.
