### ISSUE TITLE
Battery Sensor and Model Names in Latest Dev

### ISSUE THREAD

**Issue by hirenshah** [MindrustUK/Heatmiser-for-home-assistant#159]
I have:
- 1 x neoHub
- 1 x RF-Switch
- 1 x neoPlug
- 1 x neoAir v3
- 2 x neoStat-E
- 5 x neoStat v2

I replaced Master with Dev a couple of days ago and have just synced your recent comments.  

Issues:

1.  Each device has been duplicated but that is a minor problem

2.  The Model Name now shows as a Device Type number than the previous friendly name:

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/418112/431d1d63-4ba1-4778-a348-25ac1781be80)

3.  The previous devices used to have Battery and Offline sensors, but that seems to be missing from the new ones:

Old:
![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/418112/2fa4a0b0-8b57-43ae-bb3e-732d97436e29)  

New:
![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/418112/b3860fe4-1f49-4af3-9658-f2c5d8890c80)

**Comment by MindrustUK** [comment]
1) Duplicate entries: this shouldn't happen. I suggest you remove all instances of the Heatmiser plugin and setup from fresh. It's probably an artefact of moving from master to Dev as devices now have a consistent naming scheme the entities could be doubled up.

2) The model name: This is working mostly correctly the friendly name should have never shown here as it should be the model name as per the field heading. It does looks like enumeration for device type 12 and 13 needs attention. I have fixed this locally but not pushed the changes yet. Keep an eye out for future commits which will reflect all models correctly.

3) Battery sensors will now only appear for devices that actually use a battery. Example the Device types;
- 2 - Smart Stat
- 5 - Contact Sensor
- 13 - NeoAir 2
- 14 - Wireless Air Sensor.

**Comment by hirenshah** [comment]
1) I removed and readded everything, and that has sorted the duplicate entries issue.

2) I'm watching this repo, so will test out the changes once your update has been pushed.  Just to add, my neoPlug is showing as Device Type: 6, so 6, 12 and 13 need some work.  

3) I hang my head in shame.  The majority of stats are mains powered because I didn't want the hassle of changing batteries every year.  That completely slipped my mind, and only after reading your comment did I realise that not seeing anything battery related is in fact a fix.  I see a Battery Low sensor for the neoAir, and that is the only battery powered stat I have.  Let's pretend I never said anything ;)

**Comment by MindrustUK** [comment]
Hi @hirenshah can you pull the latest dev branch and check if point 2, Device ID's being incorrectly reported is resolved for you? Thanks!

**Comment by hirenshah** [comment]
> Hi @hirenshah can you pull the latest dev branch and check if point 2, Device ID's being incorrectly reported is resolved for you? Thanks!

Removed the previous integration, made sure the folder was removed from custom_components, restarted HA, installed dev version using commands specified, restarted HA and lastly readded the integration:

![{2868B8AE-26C2-4B3F-9ABB-4AAF3062CAF8}](https://github.com/user-attachments/assets/fe18a53a-a343-45f8-9920-3ed9a7ab81ac)

**Comment by MindrustUK** [comment]
How odd... famous last words "That shouldn't happen" I'll do some more digging... Thanks for the prompt feedback, much appreciated!

**Comment by MindrustUK** [comment]
Hi @hirenshah Obvious mistake on my part, if you can grab the latest version, test again and let me know how you get on. Thanks!

**Comment by hirenshah** [comment]
> Hi @hirenshah Obvious mistake on my part, if you can grab the latest version, test again and let me know how you get on. Thanks!

:partying_face: :partying_face: :partying_face: 


![{FB55DB40-DDDD-47F5-85FC-FA4D2ED4CB0C}](https://github.com/user-attachments/assets/389cdce9-e549-4569-86f3-a704ab315aaa)

**Comment by MindrustUK** [comment]
Amazing! Closing complete.
