### ISSUE TITLE
Add support for handling "offline" devices

### ISSUE THREAD

**Issue by MindrustUK** [MindrustUK/Heatmiser-for-home-assistant#16]
Add support for handling "offline" devices, maybe useful in raising alerts / monitoring.

**Comment by ribbal** [comment]
Added 'offline' attribute, in this PR https://github.com/MindrustUK/Heatmiser-for-home-assistant/pull/102

**Comment by MindrustUK** [comment]
Closing issue thanks @ribbal for the myriad of contributions.
