### ISSUE TITLE
NeoAir V3 Hot Water Entity Missing

### ISSUE THREAD

**Issue by dtsn** [MindrustUK/Heatmiser-for-home-assistant#160]
I've just installed the repo and while I have an entity for each of my devices I don't have one for my hot water which is controlled via the NeoAir v3. Is this something you are planning on supporting?

**Comment by MindrustUK** [comment]
Hi @dtsn Interesting... is / was the device on at the time of installation? Also which branch are you running, main or dev? I don't think NeoAir v3 should be filtered for any reason, so I'd expect an entry.

**Comment by dtsn** [comment]
The NeoAir controls both my zone heating (upstairs) and the hot water via
its connection to the RF Switch 2. However, the time clock entity doesn’t
appear, only the standard zone controls.

**Comment by dtsn** [comment]
Sorry, the last reply was pretty brief. I was halfway through writing a really detailed walk through of the device etc when i noticed it's now appearing in the integration. It seems to have a delay.

I do have a follow-up question about whether it's possible to set the amount of time for the hot water switch? I only seem to have an on/off toggle and I would assume this would just set it for 1hr like the HomeKit integration.

<img width="1046" alt="Screenshot 2024-07-02 at 10 04 15" src="https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/354263/df544604-6ad2-4607-95e4-f14fd6961017">

**Comment by MindrustUK** [comment]
The logic in the main branch (from memory) is when a timer is toggled: on, it sets the on time for 30 minutes. If you use the Dev branch; I think I've made this adjustable, I can't remember if I got round to completing this, but it's on the agenda somewhere when I get a chance to look again.
