### ISSUE TITLE
current_temperature attribute is unknown

### ISSUE THREAD

**Issue by jayx0101** [MindrustUK/Heatmiser-for-home-assistant#162]
Hello,

I hope you're well!

I'm having trouble displaying a sensor value in the template editor. I'm using the following code:

`{{ states('climate.kitchen.current_temperature') }}`

However, I keep getting "Unknown" as the result [please see here](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/55571076/8866aa47-9d69-4477-9f7f-d685a41677e9).
). I've verified in the Developer Tools that the sensor "'climate.kitchen" has a value for the attribute "current_temperature" attribute [please see here](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/55571076/faa899ba-14fc-4d11-bc61-132bebd40e0a).

Please note that when I look at the sensor without any attribute I get the correct states, but cannot add any other attribute as all of them are being reported as "unknown" [please see here](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/55571076/ee04c486-473d-41d7-b373-2e25a4648916)

Is there anything I might be missing?

Thanks!

**Comment by MindrustUK** [comment]
Hi @jayx0101 

After a bit of RTFM and Google-fu you as I know nothing about templates, You can do this:

```Current Temp: "{{ state_attr('climate.bathroom', 'current_temperature') }}"```

The important thing is that the current_temperature is a attribute not a device state, see documentation here: [https://www.home-assistant.io/docs/configuration/templating/](https://www.home-assistant.io/docs/configuration/templating/) for examples and more information.

Closing issue, things like this maybe best on the Home-assistant forum as it's not really a integration related issue.

**Comment by jayx0101** [comment]
Hi @MindrustUK 

Thank you very much for your help. Your solution worked perfectly! I appreciate the time you took to guide me through this process and provide the necessary resources.

All the best & cheers!
