### ISSUE TITLE
Missing controls for NeoAir in `dev`

### ISSUE THREAD

**Issue by dtsn** [MindrustUK/Heatmiser-for-home-assistant#164]
Just switched over to `dev` to help with development, and I have lost the controls for my NeoAir units (the neoStats still have controls).

<img width="1058" alt="Screenshot 2024-08-07 at 13 13 09" src="https://github.com/user-attachments/assets/a504a752-3ff9-4014-b074-9887426d8c2a">

**Comment by MindrustUK** [comment]
@dtsn Just pushed a quick patch that should address, can you check and let me know if this works for you?

**Comment by dtsn** [comment]
We're back. However, the timer is still missing the controls.

<img width="1064" alt="Screenshot 2024-08-08 at 10 47 45" src="https://github.com/user-attachments/assets/cb8e7aa4-2ba5-4456-a1c4-e84dad5fb621">

<img width="1084" alt="Screenshot 2024-08-08 at 10 47 52" src="https://github.com/user-attachments/assets/90eb9c8b-d005-4c3e-8670-52760605ad94">

**Comment by MindrustUK** [comment]
Ok, improvement. When you say timer, do you mean you have one of these setup in "Time Clock Mode" ?

**Comment by dtsn** [comment]
Device type `13` has 2 modes both a climate mode and a hot water boost mode. In the `master` branch you are just looping through the devices and capturing it, in `dev` you are separating these out so need to code for the 'Hot Water Boost' switch.

**Comment by MindrustUK** [comment]
@dtsn  Just thrown in a few hot fixes give it another go and let me know if that's as expected.

**Comment by MindrustUK** [comment]
Hi @dtsn I'll close this complete as I haven't heard back. Feel free to re-open should you have any further issues.
