### ISSUE TITLE
Heatmiser Neo IP changed can't update

### ISSUE THREAD

**Issue by bonkersbrains** [MindrustUK/Heatmiser-for-home-assistant#166]
Hi, I recently changed my router and had to change the IP address of the Heatmiser Neo Hub. I deleted the previous entities from the integration, and have rebooted Home Assistant. 
When I try to re add the integration and either use the (static) IP address of the Neo Hub, or use its name (Neo-Hub - which is also pingable), the integration spins as if thinking about it and then nothing happens. The set up screen just goes back to how it was.
In the log I get the following:

Logger: custom_components.heatmiserneo.config_flow
Source: custom_components/heatmiserneo/config_flow.py:127
integration: heatmiserneo ([documentation](https://github.com/MindrustUK/Heatmiser-for-home-assistant))
First occurred: 9:57:39 PM (1 occurrences)
Last logged: 9:57:39 PM

Error: cannot_connect

So it appears that it can't connect. I suspect that the config of the old ip address is still stored somewhere, but I cannot find it anywhere. Any ideas?

Thanks

**Comment by MindrustUK** [comment]
Hi @bonkersbrains my knee jerk is that reconfiguring the IP address may have disabled the "Legacy API" connection.

Can you double check this is active in the Heatmiser app?

Also to test the port and API is responding try sending:  `printf '{"INFO":0}\0' | nc IP_ADDRESS_HERE 4242` this can be done from the Home-Assistant servers terminal. This should return a bunch of API info.

Let me know how you get on.

**Comment by bonkersbrains** [comment]
Thanks - it had disabled the legacy api connection option as you suggested - its working again now. 
Thanks for the super fast response :)

**Comment by MindrustUK** [comment]
Glad it's resolved. Closing.
