### ISSUE TITLE
Some NeoStats appear as NeoTimer

### ISSUE THREAD

**Issue by TheBengaBenga** [MindrustUK/Heatmiser-for-home-assistant#168]
Hi,

Amazing work, all up and running pretty damn easy, thank you muchly!

I have six NeoStat v2, all of which were picked up by the integ. However, 4 of them report in HA as "NeoTimer".

They've all the same model, same firmware etc. I also can't see a way to change it manually.

The remaining 2 report correctly in HA as "NeoStat"

**Comment by MindrustUK** [comment]
Hi, glad to hear it was so easy!

Typically, you see neostats report as "NeoTimer" when they are operating in time-clock mode.

For the NeoStatV2, The standard operational modes are;
- Thermostat, set a temperature and the contact closes until the temperature criteria is met.
- Timeclock, set a bunch of time conditions and state on or off and the contact works this way during that time specified.

Typically you'll see thermostat mode for heating a zone and time-clocks for things like towel rails or immersion hot water heating that you want on in the morning and evening. In time-clock mode the temperature isn't active as component in operation.

Can you confirm if anything you're seeing is out of line with this or if you expected some different behavior etc?

**Comment by TheBengaBenga** [comment]
Hey,

so sorry I vanished on you, I got lost down a rabbit warren of virtual devices / templates and Voice Assistants!

The plot has thicken so let me see if I can describe what I’m seeing.

3 neo’s now have two devices showing, one being Neotimer the other a Neostat. 3 neo’s have only one device, Neostat.

The timers have only a on/off, the stats have sensor data too.

In entities, not all have a “climate.” and a number have their “switch.” entities as showing ‘unavailable’ but noting this only happened ‘yesterday’

Sorry, probably about as clear as mud that, but I’m failing to find a pattern. 

Couple of thoughts I’ve got…

I wonder if the way I have the stats configured is what’s happening here. I have a schedule operating the same on all stats which sets the temp at each of the four timeslots to xx (17.5° in my case). Is it possible I’m confusing the integration somehow and I keep flip flapping between the integ seeing them as stats then timers and it’s all good a bit messed up in there.

Any thoughts?

**Comment by MindrustUK** [comment]
@TheBengaBenga the rabbit hole on home automation is real!

A very interesting case, you're not running multiple NeoHubs per chance are you? I've just pushed an update to the Dev branch which addresses some bad practices to do with unique IDs, you may wish to test the latest version of the code...

I take it there's nothing obvious in the Home Assistant system logs?

The schedule shouldn't have any effect other than the state of the climate changing from 'idle' to 'heat' for example. Or something like the 'hold active' state changing.

This sounds like a conflict, or your NeoHub is returning junk data...

If you can also post the output of the debug data from the logs that may help with things, make sure to sanitise any logs before posting them.

**Comment by TheBengaBenga** [comment]
Yeah sure, I’ll grab.

Another thought… I’ve got Alexa integration all up and running inc Media Player. I have the Neo environment direct to Alexa as well, maybe will drop that once I’ve figured out this conundrum, and will expose from HA instead rather than direct. Is it possible that some are being picked up through that, thus the double entry?

i wanted to say thanks as well, really appreciate you taking your time to help.

back shortly…

**Comment by TheBengaBenga** [comment]
Sorry, another branch thought, I seem to recall I renamed an object or two, you were one of my first installs so was still rather cavalier then.

I think I'll remove the integ and re-add fresh and from scratch. Also means I can move the hub out of my main dhcp scope before I re add it.

Any thoughts on the cleanest way to fully remove? You might just say nuke it but thought I'd check in case you had any thoughts of cleaning tips...

**Comment by MindrustUK** [comment]
A fresh start seems a good idea. The cleanest way should be to;

- Remove the integration from home assistant
- Remove the underlying code from the underlying config directory.
- Restart Home Assistant.
- Give your installation a quick visual scan for any left over entities or devices and ensure these are removed.
- Clone the latest dev branch
- Restart Home Assistant
- Configure the 'new' integration.

Hopefully everything starts working as expected. Let me know how you get on.

**Comment by TheBengaBenga** [comment]
Riiiight. So, after all that a nuke the site from orbit has totally fixed it.

I reckon must have just been a bad import when it first connected up.

There was one thing I saw that might be worth feeding back, it's _possible_ this was the issue. When at the end of the configure process, the discovered devices show up in a pop up, to assign to locations (zones / rooms). I doubt I had rooms existing on the first install so likely just clicked to victory at this point. This time I went through them and assigned to rooms. But, the default option was that HA was about to go create me a whole pile of new objects (locations) named after each stat. I wonder if this is where it went awry? Possible solution, can you configure the install to leave these fields blank by default?

And one remaining question, I now got three entities per stat 1. Stat 2. Battery indicator and 3. 'Binary sensor'. Any ideas what this last entity actually is?

Thanks again for everything!

**Comment by TheBengaBenga** [comment]
Oh, and didn't do the dev branch, this is main line

**Comment by MindrustUK** [comment]
Great! I'll close this as resolved.
