### ISSUE TITLE
cannot find on HACS

### ISSUE THREAD

**Issue by InternetOfThings272** [MindrustUK/Heatmiser-for-home-assistant#171]
Hi, had this integration recommended for home assistant and heatmiser neohub G2, but I don't think I can see it on HACS. I can see this http://homeassistant.local:8123/hacs/repository/305188358, but I don't think it is the same thing. thanks.

**Comment by MindrustUK** [comment]
Hi @InternetOfThings272 The link you posted is specific to your local instance which means no one else can see what you're referring to. I don't use HACS myself, but if you check the instructions, you need to add: https://github.com/MindrustUK/Heatmiser-for-home-assistant as a custom repository. I suspect this is why you can't find what you're looking for.

**Comment by MindrustUK** [comment]
Closing, stale.
