### ISSUE TITLE
Bug: Neo Air Sensors return non sensible times which cause "Failed setup, will retry: time data '255:00' does not match format '%H:%M'"

### ISSUE THREAD

**Issue by michaelmarconi** [MindrustUK/Heatmiser-for-home-assistant#176]
Hi @MindrustUK, I'm struggling to set up your integration.  I had to reset my Heatmiser neoHub and add back all the thermostats today and when I tried to setup the integration again, I see this error:  `Failed setup, will retry: time data '255:00' does not match format '%H:%M'`

Any idea what might be causing this?

-------------------------------------

This error originated from a custom integration.

Logger: custom_components.heatmiserneo
Source: helpers/update_coordinator.py:354
integration: Heatmiser Neo Climate (documentation)
First occurred: 17:22:04 (19 occurrences)
Last logged: 17:30:26

Unexpected error fetching neostat data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
    _, devices_data = await hub.get_live_data()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/neohubapi/neohub.py", line 449, in get_live_data
    thermostats.append(NeoStat(self, thermostat))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/neohubapi/neostat.py", line 97, in __init__
    _time = datetime.strptime(self.time, "%H:%M")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '255:00' does not match format '%H:%M'

**Comment by michaelmarconi** [comment]
Digging into the `manifest.json` file, I see that the dependency on neohub API is pinned to version 1.0:  ` "requirements": ["neohubapi==1.0"],`.  Is there a reason for that @MindrustUK or could this be bumped forward to the latest version of the API?

**Comment by MindrustUK** [comment]
Hi @michaelmarconi I forget my exact rationale, but from memory neohubapi 2+ has some breaking changes that aren't compatible with main branch. The dev branch uses this, but is still under quite a bit of work, Things like Neoplugs don't work and the hold implementation is ugly and incomplete. However you may wish to test with this. I will eventually bump dev to main, but as ever I need more time to look into it.

**Comment by MindrustUK** [comment]
@benkayuk continuing here @michaelmarconi has kindly prepared a merge request in https://gitlab.com/neohubapi/neohubapi that once available in pip, I'll be able to deploy to the current integration. What's interesting is I also have these air sensors as part of my test setup but haven't seen the issue. I can only assume newer versions, firmware or configuration is not presenting this issue to me.

**Comment by MindrustUK** [comment]
@michaelmarconi @benkayuk Manifest updated and neohubapi bumped to version 2.2. Please test and feedback.

**Comment by benkayuk** [comment]
> @michaelmarconi @benkayuk Manifest updated and neohubapi bumped to version 2.2. Please test and feedback.

Fixed! Integration initialises great, can see air sensors etc....thank you.

**Comment by michaelmarconi** [comment]
Yup, all working beautifully on my side too! 
Thanks @MindrustUK; great team effort 🙌
