### ISSUE TITLE
Add HACS support for autoupdates

### ISSUE THREAD

**Issue by haakonstorm** [MindrustUK/Heatmiser-for-home-assistant#18]
For automatic updates off heatmiserneo, add [HACS](https://community.home-assistant.io/t/custom-component-hacs/121727) support?

**Comment by MindrustUK** [comment]
Currently under investigation.

**Comment by violuke** [comment]
If this still on the cards? This would be excellent 👍

**Comment by megaturba** [comment]
Hi, MindrustUK, please add HACS support, if you got a chance ;-)

**Comment by haakonstorm** [comment]
bump

**Comment by eon123** [comment]
Yes please!

**Comment by MindrustUK** [comment]
Added by @leaskovski  under https://github.com/MindrustUK/Heatmiser-for-home-assistant/pull/47

Closing request.
