### ISSUE TITLE
Async_forward_entry_setup called in __init__.py will be deprecated in HA 2025.6

### ISSUE THREAD

**Issue by PTomlinson1** [MindrustUK/Heatmiser-for-home-assistant#180]
I have this error in my logs:

Detected that custom integration 'heatmiserneo' calls async_forward_entry_setup for integration, heatmiserneo with title: 192.168.10.111:4242 and entry_id: ad0999e84b23b32b6b3069115f3eb81c, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/heatmiserneo/__init__.py, line 81: hass.async_create_task(, please report it to the author of the 'heatmiserneo' custom integration

It is repeated for lines 85 and 89 in __init__.py

I guess it will need fixing in the next few months as HA updates continue.

Thanks for all your good work.

**Comment by MindrustUK** [comment]
Hi @PTomlinson1 Thanks for the report. I've forked a version of dev to the default branch as version 1.5 where this should already be fixed. If it's not feel free to re-open the ticket.
