### ISSUE TITLE
HVAC_MODE_HEAT, HVAC_MODE_HEAT_COOL, HVAC_MODE_OFF, SUPPORT_TARGET_TEMPERATURE are deprecated constants which will be removed in HA 2025.1

### ISSUE THREAD

**Issue by PTomlinson1** [MindrustUK/Heatmiser-for-home-assistant#181]
Also spotted these messages in the logs:

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:197
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 15 October 2024 at 23:39:27 (14 occurrences)
Last logged: 15 October 2024 at 23:39:28

HVAC_MODE_HEAT was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'heatmiserneo' custom integration
HVAC_MODE_HEAT_COOL was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT_COOL instead, please report it to the author of the 'heatmiserneo' custom integration
HVAC_MODE_OFF was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'heatmiserneo' custom integration
SUPPORT_TARGET_TEMPERATURE was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'heatmiserneo' custom integration
SUPPORT_TARGET_TEMPERATURE_RANGE was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please report it to the author of the 'heatmiserneo' custom integration

Thanks.

**Comment by MindrustUK** [comment]
Hi @PTomlinson1 Thanks for the report. I've forked a version of dev to the default branch as version 1.5 where this should already be fixed. If it's not feel free to re-open the ticket.
