### ISSUE TITLE
Hold Function not working with int

### ISSUE THREAD

**Issue by zaidbadat** [MindrustUK/Heatmiser-for-home-assistant#185]
If setting the hold temp to 21 it doesn’t work, setting it to 21.0 doesn’t work either, but setting as 21.5 works fine. 

![IMG_1219](https://github.com/user-attachments/assets/68bdeaf2-64cd-4d08-877b-f11f348f4ec6)
![IMG_1220](https://github.com/user-attachments/assets/4a5d3cbe-e64d-4e3f-ad5b-912564023b92)

**Comment by MindrustUK** [comment]
@zaidbadat  Have you tried setting 21.0 ? Does this work for you, the type was recently changed to support floats rather than int.

**Comment by MindrustUK** [comment]
@zaidbadat Sorry, just read that you tried this. Odd... I'll investigate.

**Comment by MindrustUK** [comment]
Strange, I can only assume that 22.0 is being interpreted as a int rather than a float, which makes sense but it does call into question how typing should work... I might need to add something to wrap the value to always return a float. I'll investigate further when I get some time. Thanks for reporting.

**Comment by zaidbadat** [comment]
Thank you. 
If it helps I’ve attached images of the version I’m running. 





On Friday, October 18, 2024, 12:46 pm, MindrustUK ***@***.***> wrote:




@zaidbadat Sorry, just read that you tried this. Odd... I'll investigate.

**Comment by zaidbadat** [comment]
Thank you. 

If it helps I’ve attached images of the version I’m running.

**Comment by zaidbadat** [comment]
![IMG_1221](https://github.com/user-attachments/assets/a447cb2a-4d64-438b-8449-db02b2371219)
![IMG_1222](https://github.com/user-attachments/assets/ad7a4b91-b269-416a-b439-b95ccd3e074f)

**Comment by ocrease** [comment]
@MindrustUK looks like I didn't do very good testing on #175. I think the schema for the service call needs to change:

```
platform.async_register_entity_service(
    SERVICE_HOLD_ON,
    {
        vol.Required(ATTR_HOLD_DURATION, default=1): object,
        vol.Required(ATTR_HOLD_TEMPERATURE, default=20): vol.Coerce(float),
    },
    "set_hold",
)
```

Using `vol.Coerce(float)` instead of `float` should allow int, float and strings that are numbers.

**Comment by zaidbadat** [comment]
Any idea when this fix is likely to be pushed, please. 
We rely on this extension to control our UFH, it would be appreciated. 
Thank you. 


On Friday, October 18, 2024, 3:52 pm, ocrease ***@***.***> wrote:




@MindrustUK looks like I didn't do very good testing on #175. I think the schema for the service call needs to change:
platform.async_register_entity_service(
    SERVICE_HOLD_ON,
    {
        vol.Required(ATTR_HOLD_DURATION, default=1): object,
        vol.Required(ATTR_HOLD_TEMPERATURE, default=20): vol.Coerce(float),
    },
    "set_hold",
)

Using vol.Coerce(float) instead of float should allow int, float and strings that are numbers.

**Comment by 111rdw** [comment]
I'm having hte same problem. Tried to change my config file as you reccommend but it did not work. I'm a complete amateur at this so might have got it wrong. this is what it did

  platform.async_register_entity_service(
        SERVICE_HOLD_ON,
        {
            vol.Required(ATTR_HOLD_DURATION, default=1): object,
            vol.Required(ATTR_HOLD_TEMPERATURE, default=20): vol.Coerce(float),
        },
        "set_hold",

I will change my target temp to x.1 in the interim. thanks

**Comment by MindrustUK** [comment]
@ocrease Pushed that hotfix. Looks like it's working for me. I'll leave the issue open for a few days for feedback if anyone has further issues.

**Comment by ocrease** [comment]
@MindrustUK seems to be working for me too.

@111rdw make sure you restart home assistant after updating. Also, in HACS I had to do "Update information" to get the right version (commit 7fe9630)

**Comment by zaidbadat** [comment]
Working for me now too, thank you. 

On Sunday, October 20, 2024, 3:19 pm, ocrease ***@***.***> wrote:




@MindrustUK seems to be working for me too.

@111rdw make sure you restart home assistant after updating. Also, in HACS I had to do "Update information" to get the right version (commit 7fe9630)

**Comment by 111rdw** [comment]
> @MindrustUK seems to be working for me too.
> 
> @111rdw make sure you restart home assistant after updating. Also, in HACS I had to do "Update information" to get the right version (commit [7fe9630](https://github.com/MindrustUK/Heatmiser-for-home-assistant/commit/7fe9630692390609a51ab6c904ce79f298422e76))

Many thanks. Reboot and right version fixed it. Happy days👍👍👍

**Comment by MindrustUK** [comment]
Great, thanks for the feedback. closing resolved.
