### ISSUE TITLE
Bug: Device continually becoming unavailable

### ISSUE THREAD

**Issue by tk200** [MindrustUK/Heatmiser-for-home-assistant#193]
My Neostat continually becomes unavailable in Home Assistant for periods of time before coming online again. The actual thermostat is not offline, as it is available within the Heatmiser Neo app.
Is this a polling issue somewhere - not sure how the integration gets data from the Neohub?
Running the dev branch.

![IMG_5928](https://github.com/user-attachments/assets/f1f458c0-89a5-4867-86d3-6afc750c2e69)

**Comment by MindrustUK** [comment]
Hi @tk200 Interesting, the Heatmiser integration fetches bulk information from the hub every 30 seconds. 2 Hour unavailable is weird...

Let's try a little debugging,

Can you create `check_offline.sh` using a terminal on your home assistant installation with the following content (please note update the hub IP):

```
#!/bin/bash
# Define log file location
LOG_FILE="offline_status.log"

# Generate timestamped output
OUTPUT="$(date '+%Y-%m-%d %H:%M:%S') - OFFLINE status: $(printf '{"INFO":0}\0' | nc YOURHUBIPADDRESS 4242 | jq '.devices[] | select(.device == "Cloakroom") | .OFFLINE')"

# Print to console
echo "$OUTPUT"

# Append to log file
echo "$OUTPUT" >> "$LOG_FILE"

```

Once this is in place (don't forget to `chmod +x the check_offline.sh`) then run:
```watch -n10 ./check_offline.sh```

If you run that for a bit and see if the device is continuously returning a false status, then we can take it from there.

**Comment by MindrustUK** [comment]
Also @tk200 Is this happening on a single device? And what model device is it?

**Comment by tk200** [comment]
Thanks for the quick response! It is happening on a single device - it’s the only thermostat I have. NeoStat v2.

As part of trouble-shooting, I have re-installed the main branch as I see you have updated that to v1.5. That was only a few hours ago, but it has remained online in HA since then, so I will monitor and if it re-occurs run the debug you have posted. It may have been something already resolved as I hadn’t updated the dev files for a while.

**Comment by MindrustUK** [comment]
Great, I'll leave this open for a week or so and we'll see if anything causes trouble and if not we can say it was probably resolved by one of the recent commits.

**Comment by tk200** [comment]
It is still going offline periodically still - although seems less than previously. I have tried setting up the check_offline file, but I get Permission Denied when I try to run it via the watch command. HA is on a Pi, with the check_offline.sh file in the config directory. Trying to run watch command from the HA Terminal web UI.

**Comment by MindrustUK** [comment]
Did you ensure to run `chmod +x check_offline.sh` ? do you get permission denied if you run `./check_offline.sh` ?

**Comment by tk200** [comment]
I did run chmod +x. Permission denied when trying to run the file. Do I need to change some permissions somewhere?
![IMG_5944](https://github.com/user-attachments/assets/cef091af-2d50-4565-9852-6476af90ae95)

**Comment by MindrustUK** [comment]
Looks like you ran `chmod -x check_offline.sh` this will remove the execute permission, we want to set the execute bit :) Please try again with `+` drop a screenshot again if it still doesn't work for you.

**Comment by tk200** [comment]
Ah - thanks…

Now tried that with the correct command (I think!), and get an error stating required file not found.

![IMG_5946](https://github.com/user-attachments/assets/8ab3aa31-1436-4225-81b8-7bd854840962)

**Comment by MindrustUK** [comment]
Hmmm that's an odd error can you run `cat check_offline.sh` and paste a screenshot? Please obfuscate any sensitive information such as IPs etc.

**Comment by tk200** [comment]
Thanks for the trouble-shooting. Screenshot attached. Wasn’t sure if the Neo hub IP should be 192.168.1.139 4242 or 192.168.1.139:4242 but have tried both.

![IMG_5948](https://github.com/user-attachments/assets/20265752-f032-4d9b-a064-1c0599259162)

**Comment by MindrustUK** [comment]
Try running `dos2unix check_offline.sh` I suspect there maybe some unintentional line feeds, carriage return, etc.

The format of the IP and port are fine in this example.

Let me know how that goes for you.

**Comment by tk200** [comment]
That’s worked - thanks!
Running the log now - I’ll leave it going and monitor the unavailable state. It dropped off twice yesterday.

**Comment by tk200** [comment]
Thanks for your patience with the diagnosis. I've had your log running for 3 days, and the Neostat hasn't dropped offline or become available at all. It became unavailable twice since upgrading the integration, interestingly for exactly 30 seconds and then 60 seconds (presumably the integration missed a couple of updates from the Neohub for some reason) and those 2 occasions were within a couple of hrs of the upgrade. It has behaved since so can't see the need to keep the bug report open unless you want any further logging for anything?

**Comment by MindrustUK** [comment]
@tk200 let's close it. If it starts giving trouble again we'll re-investigate. I wonder if it's something like CPU contention or system load...

Feel free to re-open should you need anything further.
