### ISSUE TITLE
Bug: NeoPlug functionality is broken in Dev and Version 1.5

### ISSUE THREAD

**Issue by MindrustUK** [MindrustUK/Heatmiser-for-home-assistant#194]
Need to fix functionality for the Heatmiser NeoPlug devices that became broken in Dev and down streamed to Version 1.5 on release.

This is likely to leverage "Hold Functionality" currently under development in task: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/182 It probably makes sense to complete this issue first before attempting to address the NeoPlugs to avoid duplication of effort.

**Comment by ocrease** [comment]
@MindrustUK this is one of the things you should check when reviewing #201. I think it will work or be very close to working

**Comment by MindrustUK** [comment]
Tested, and can happily report it's broadly working... sometimes... I've left feedback on the PR. I got some errors as follows:

`Failed to perform the action select/select_option. 'NeoStat' object has no attribute 'data'`

**Comment by MindrustUK** [comment]
Issue resolved by @ocrease in update to PR. Calling NeoPlug support complete.
