### ISSUE TITLE
Feature: Add support for repeaters

### ISSUE THREAD

**Issue by MindrustUK** [MindrustUK/Heatmiser-for-home-assistant#196]
Continued conversation from: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/182

@PhillyGilly There's also a lot of moving parts to what you've raised in the previous thread.

I think the TL;DR is there's no 'real' support for any of the Heatmiser Repeaters. I.e. the following products: NeoX, Boost, or Boost V2. As per your assertion that the repeaters are neoplugs without the plugs, AFAIK this is sort of true. From memory the internal radio technology of the Heatmiser system is some sort of Zigbee implementation and it uses devices to mesh it's connectivity. The Heatmiser Neoplugs work as repeaters, this also applies to any hardwired thermostats too and by extension the repeaters just being part of the radio stack.

As per the API repeaters should be visible with a device ID: 10.

I asked @michaelmarconi about this in thread: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/176 and https://gitlab.com/neohubapi/neohubapi/-/merge_requests/31 apparently the device ID's are not reported hence the hack to ignore anything reported that doesn't match up between the engineering and info data. I did not get any sample data to verify the behaviour.

I'm pretty sure this is not intended behaviour and something that we should communicate with Heatmiser about.

I don't have any sort of repeaters in my collection to test with so we'd need further output from the hub either with the `INFO, GET_DEVICES, GET_LIVE_DATA, GET_SYSTEM` or other commands to get a better idea of what's going on. From the API docs it looks like these SHOULD report ID and availability.

All of the above aside, it seems that your particular use case is about identifying a downstream repeater that depends on another repeater being offline and how to identify the failure state / dependency. Let's further that conversation here as part of getting good repeater support rather than bleeding into other issues.

**Comment by ocrease** [comment]
@PhillyGilly It looks like you have the perfect testbed for the heatmiser neo ecosystem! You have several device types (I only have NeoStat V2s). It would be helpful if you can try out the new diagnostics functionality I added in #200 which has just been merged into the dev branch. Take a look at the file before you upload it in case I missed any fields that should have been redacted (things like host, pin numbers, serial numbers are already redacted). With the file we should be able to work out if the data is already provided by the API.

**Comment by PhillyGilly** [comment]
Happy to help. Just got to work out how to run form the dev branches. Could be later post half-term grandchildren!

**Comment by ocrease** [comment]
@PhillyGilly turns out the diagnostic functionality needs a few improvements. I'll let you know when it's ready. In the meantime, enjoy the grandkids!

**Comment by PhillyGilly** [comment]
I had a quick look at how to load the dev repository and it's not that obvious. I thought there was an option in HACs to load dev, but I can't see it. If you can point me in the right direction I should be able to do it when you have diagnostics working. Thanks.

**Comment by ocrease** [comment]
There used to be instructions on the dev branch readme, but they seem to be gone now. It's something like this:

For Hass.io:
Install and configure SSH server from the "Add-on store". Once you have shell run the following:
```
mkdir -p /config/custom_components
cd /tmp/
git clone -b dev https://github.com/MindrustUK/Heatmiser-for-home-assistant /tmp/heatmiserneo
mv /tmp/heatmiserneo/custom_components/heatmiserneo /config/custom_components/
rm -rf /tmp/heatmiserneo/
```

@MindrustUK once we have the diagnostics working well enough, it might be worth merging them into the default branch so that its available via HACS. I think it will be helpful with several tickets.

**Comment by MindrustUK** [comment]
Somehow I managed to loose the dev instructions, I re-added them to the dev branch under: https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/dev/docs/dev_installation.md This will make it's way to the default branch in time.

@ocrease Agreed, once we're happy that diagnostics are working as expected I'll push these out to the default branch. Let's focus on getting that completed and out the door and then reviewing the other PR's etc. Once the hold stuff is back in I plan on releasing 3.0.0 (as I didn't bump the manifest properly and it's currently reporting 2.0.0).

**Comment by ocrease** [comment]
@PhillyGilly I think @MindrustUK has merged the diagnostics functionality into the default branch you get from HACS, so you should be able to get it from there now. If you can attach the diagnostics output (maybe zipped) then I can see how the repeaters are reported and we can see if they can be added.

**Comment by PhillyGilly** [comment]
[config_entry-heatmiserneo-01JBFSWWRR3N11W4JBA6511WMW.zip](https://github.com/user-attachments/files/17579875/config_entry-heatmiserneo-01JBFSWWRR3N11W4JBA6511WMW.zip)
The repeater nodes are numbers 8213 and 44138. At first glance the way in which they are reported is the same as it was in the first releases of HeatmiserNeo.

**Comment by PhillyGilly** [comment]
@MindrustUK The diagnostics function in the main branch is a really helpful addition. Thanks.

**Comment by ocrease** [comment]
@PhillyGilly thats very helpful thanks. A few questions:

1. I assume the repeater names are fixed and can't be changed in the heatmiser app?
2. Other than the device being connected, is there any other useful information that you would expect to see? Are there any control / settings that can be changed in the app?

I think there will need to be a change to the neohubapi to add these back in, or at least report them separately. Also, need to get #201 done and then it should be relatively easy to add.

**Comment by ocrease** [comment]
@PhillyGilly Also, it would be useful to know if the repeaters are returned in the call that is made to retrieve serial numbers (which are used to keep a unique id). If you can, could you set the neohub logger to debug and see what is returned by the DEVICES_SN call:

in `configuration.yaml`:
```
logger:
  default: warning
  logs:
    neohub: debug
```
You then need to restart HA.

Then you should see in the logs something like this:

```
2024-10-30 23:49:55.250 DEBUG (MainThread) [neohub] Sending message: bytearray(b'{"DEVICES_SN": 0}\x00\r')
2024-10-30 23:49:55.317 DEBUG (MainThread) [neohub] Received message: {"Hallway" ..........
```

Check if the repeaters appear there. I suspect they won't.

**Comment by MindrustUK** [comment]
@PhillyGilly all credit for the diagnostics should go to @ocrease they've clearly got a lot more time to push code than I have at the minute :)

**Comment by PhillyGilly** [comment]
@ocrease I set Heatmiser to log debug using the function in the app.
Is it meant to create a separate log file?
There is a lot of Heatmiser content in the HA core log but I can't see neohub sending or receiving messages.
[HAcorelog.zip](https://github.com/user-attachments/files/17586233/HAcorelog.zip)

You can add the repeaters using the App but they don't show in the App. This is 90% of the problem! I also don't know why my door contact switches show up but the remote temperature sensors don't. Getting the battery status of the sensors is a big plus in the new versions of Heatmiser.

Back in 2020, I used a bit of code called neohubby.py to manage the repeaters providing the functions that the App doesn't.  FWIW here it is 
[listdevices.zip](https://github.com/user-attachments/files/17586379/listdevices.zip)

**Comment by ocrease** [comment]
@PhillyGilly Thanks for the logs. The repeater serial numbers are not returned, but that's fine. Reading the heatmiser docs, it sounds like the repeater nodes names are automatically generated by heatmiser and are meant to be unique, though there is a warning that if you remove them and re-add them the name will change. 

You say you were using that script to manage the repeaters. What management is there, other than adding or removing them? I think if we add repeaters back to the integration, the only useful bit of information is whether they are connected or not?

**Comment by PhillyGilly** [comment]
The "managing" was finding and deleting repeaters. I think that when I was trying to set it all up, I had some phantom repeaters that I needed to delete.

Yes. The repeater 'number' is system generated rather than being a genuine serial number. This is why I had multiple devices from one repeater.

It would be good to know that the repeater is there/working as opposed to the current negative not there approach.

**Comment by ocrease** [comment]
@PhillyGilly the latest pre release version (beta 7) has changes for repeaters. They are untested because I don't have any, let us know how it goes.

**Comment by PhillyGilly** [comment]
Good news: Two new devices have appeared! Thanks.
Here are the repeaters communicating
![image](https://github.com/user-attachments/assets/9e877f8c-6aa3-44c5-900d-074b404759df)
and now I've powered the house one down so both go off..
![image](https://github.com/user-attachments/assets/389c97d2-cb9e-46fa-8f27-7341b93107fc)
The device info looks good too...
![image](https://github.com/user-attachments/assets/f64b8b4f-fe41-473c-a09a-a0fdb77a8d58)

However in beta 7 none of the other neostats work although the neostat switches seem to  be there.
![image](https://github.com/user-attachments/assets/449d5e92-efea-4e51-9c3e-4d4369772a96)

**Comment by ocrease** [comment]
Hi @PhillyGilly glad you can see the devices, but... it doesn't look like what I was expecting:

- For some reason it is being reported as a Contact Sensor rather than a Repeater
- It shouldn't have the main "Sensor" which is reporting as closed - this is for a contact sensor
- It shouldn't have the Battery or Hold Active diagnostic sensors

I wonder if there are some old entities from previous installs that shouldn't be there anymore. Could you try these two things:

1. Delete and re-add the hub. Settings -> Devices & Services -> Integrations -> Heatmiser Neo Climate -> then delete the hub entry. Copy the hostname before you delete it if you don't know what it is. Then Add Hub to add it back in

![image](https://github.com/user-attachments/assets/4df13f34-b746-4547-a733-aaedcaf309e4)

2. Download diagnostics and post the outcome here

Regarding the neostats being Unavailable, did that happen after you turned off the repeaters? Also, just checking that you restarted HA after installing beta 7.

**Comment by MindrustUK** [comment]
@ocrease just did a fresh install of Beta7, looks like various things could be broken:

![image](https://github.com/user-attachments/assets/fd8bf0c7-a59f-47d4-883c-e3945f5625a6)

Logs attached.
[home-assistant_2024-12-15T20-18-39.342Z.zip](https://github.com/user-attachments/files/18141935/home-assistant_2024-12-15T20-18-39.342Z.zip)

Looks like downloading diagnostics is also broken.

Dropping back to Beta6 has fixed this.

**Comment by ocrease** [comment]
@MindrustUK thanks for the logs. Unfortunately without having the logs of what is returned from the hub, its  a bit tricky to work out what the problem is. I suspect your hub returns data differently to mine and the changes I did to the neohubapi itself are causing an issue. I did a fresh install on my "production" instance and it worked fine. 

Could you run with debug on. Add this to your HA configuration.yaml:

```
logger:
  default: warning
  logs:    
    custom_components.heatmiserneo: debug
    neohub: debug
```
Then restart HA, do download diagnostics (which I know fails but I'd like to see the logs for that too) and copy the logs for the first minute of startup or so. Note that pin numbers and serial numbers won't be redacted, so if you are worried about that you could replace the values with something like REDACTED.

**Comment by ocrease** [comment]
@MindrustUK forgot to mention, ideally you do those steps on the beta 7 so I can see the calls the new neohubapi is making,

@PhillyGilly tagging you in case you want to try

**Comment by MindrustUK** [comment]
@ocrease logs created running beta7, tried hitting the diagnostic button twice which you should see in the logs.

There shouldn't be anything  sensitive in the logs but I ran SED against it for good measure to redact serials and IPs.

Logs as attached.
[home-assistant_2024-12-15T22-12-32.615Z.zip](https://github.com/user-attachments/files/18142361/home-assistant_2024-12-15T22-12-32.615Z.zip)

**Comment by ocrease** [comment]
@MindrustUK thanks. I see the problem in your case. It will need fix on the neohubapi, although I could also add a protection in the integration as well.

@PhillyGilly I think your case might be different, so if you can provide our logs that would still be helpful

**Comment by ocrease** [comment]
@MindrustUK PR #224 should fix your issue

**Comment by MindrustUK** [comment]
@ocrease released this as beta8, seems to have fixed the issues. Thanks!

**Comment by PhillyGilly** [comment]
@ocrease I've created the log running Beta7 as asked in case it helps, but don't know if it needs to be anonomised(what is/was SED?) I'm going to try Beta 8 as above.

**Comment by MindrustUK** [comment]
@ocrease after a quick smoke test and it looks like repeaters have picked up a bunch of redundant controls as well as two more logged issues as follows:

![image](https://github.com/user-attachments/assets/47e1dd11-24b0-4fb7-bcb3-0d429f91d7a2)
****

Looks like there's still some errors falling out:

```2024-12-16 09:05:25.391 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 557, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/sensor.py", line 297, in native_value
    return self.entity_description.value_fn(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/heatmiserneo/sensor.py", line 224, in <lambda>
    value_fn=lambda device: _profile_current_temp(
                            ~~~~~~~~~~~~~~~~~~~~~^
        device.data.active_profile, device
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/heatmiserneo/sensor.py", line 334, in _profile_current_temp
    level = profile_level(profile_id, entity.data, entity.coordinator)
  File "/config/custom_components/heatmiserneo/helpers.py", line 174, in profile_level
    current_level = levels[0 if next else -1]
                    ~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

---

Also also, couldn't get diagnostics to download? - Associated debug for this:


```Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
First occurred: 09:04:58 (3 occurrences)
Last logged: 09:06:59
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 280, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/diagnostics.py", line 48, in async_get_config_entry_diagnostics
    zones = {device._data_.ZONE_NAME for device in neo_devices.values()}
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'ZONE_NAME'
```

**Comment by ocrease** [comment]
@MindrustUK thanks for trying that out. I think I see the problems. I'll try to fix them this evening.

@PhillyGilly no need to worry about the logs for now, I have enough with the logs from @MindrustUK. FYI, [sed](https://www.gnu.org/software/sed/manual/sed.html) is a powerful linux tool to do search and replace

**Comment by PhillyGilly** [comment]
OK. I've got them or can run more if required. I can't actually see too much embarrassing in there relating to Heatmiser, so I can run new ones if you want any time I can escape from pre-Xmas mayhem for ten minutes :-)

**Comment by ocrease** [comment]
@MindrustUK I have created a PR to (hopefully) fix these issues. It depends on a new neohubapi version so its not quite ready yet. After you've merged, if you are still having issues, please provide fresh debug logs.

**Comment by ocrease** [comment]
@MindrustUK PR updated.

BTW, a couple of your devices are reported with device type 0 (NeoStatHC and TestTimer). Both are also offline so maybe they report incorrectly when they are offline. Looks like your "Den" is also offline, but that reported a real device type 6 (NeoPlug?).

**Comment by MindrustUK** [comment]
Hi @ocrease Yes these devices are both offline. They will not report their type unless they are online at the time data is fetched from the Neohub. Once it's been retrieved the values are effectively cached, these are lost on a restart of the Home Assistant instance and will be retrieved again once the devices are online and available. Very much expected behavior. It's a shame there's nothing internally that holds the type value on pairing devices to the NeoHub so it is always available.

**Comment by MindrustUK** [comment]
@ocrease looks like it's fixed the major issues. Diagnostics download is back to working.

Diagnostics: [config_entry-heatmiserneo-01JF9XYCHK8RMN54846HHAZHNR.zip](https://github.com/user-attachments/files/18162928/config_entry-heatmiserneo-01JF9XYCHK8RMN54846HHAZHNR.zip)

Still a few error log messages:

```
Logger: homeassistant
Source: custom_components/heatmiserneo/helpers.py:101
integration: Heatmiser Neo Climate ([documentation](https://github.com/MindrustUK/Heatmiser-for-home-assistant), [issues](https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues))
First occurred: 09:03:09 (2 occurrences)
Last logged: 09:03:39
Error doing job: Task exception was never retrieved (None)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 557, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/sensor.py", line 297, in native_value
    return self.entity_description.value_fn(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/heatmiserneo/sensor.py", line 224, in <lambda>
    value_fn=lambda device: _profile_current_temp(
                            ~~~~~~~~~~~~~~~~~~~~~^
        device.data.active_profile, device
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/heatmiserneo/sensor.py", line 334, in _profile_current_temp
    level = profile_level(profile_id, entity.data, entity.coordinator)
  File "/config/custom_components/heatmiserneo/helpers.py", line 182, in profile_level
    levels = _profile_levels(profile, current_day_key, levels_filter)
  File "/config/custom_components/heatmiserneo/helpers.py", line 101, in _profile_levels
    levels = getattr(info, key_val)
AttributeError: 'types.SimpleNamespace' object has no attribute 'tuesday'
```


```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:608
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 09:02:38 (12 occurrences)
Last logged: 09:02:38

    Error adding entity sensor.testneoair1_profile_next_temperature for domain sensor with platform heatmiserneo
    Error adding entity sensor.bathroom_profile_next_time for domain sensor with platform heatmiserneo
    Error adding entity sensor.heating_profile_next_time for domain sensor with platform heatmiserneo
    Error adding entity sensor.kitchen_profile_next_time for domain sensor with platform heatmiserneo
    Error adding entity sensor.testneoair1_profile_next_time for domain sensor with platform heatmiserneo

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 557, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/sensor.py", line 297, in native_value
    return self.entity_description.value_fn(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/heatmiserneo/sensor.py", line 224, in <lambda>
    value_fn=lambda device: _profile_current_temp(
                            ~~~~~~~~~~~~~~~~~~~~~^
        device.data.active_profile, device
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/heatmiserneo/sensor.py", line 334, in _profile_current_temp
    level = profile_level(profile_id, entity.data, entity.coordinator)
  File "/config/custom_components/heatmiserneo/helpers.py", line 182, in profile_level
    levels = _profile_levels(profile, current_day_key, levels_filter)
  File "/config/custom_components/heatmiserneo/helpers.py", line 101, in _profile_levels
    levels = getattr(info, key_val)
AttributeError: 'types.SimpleNamespace' object has no attribute 'tuesday'
```

**Comment by ocrease** [comment]
@PhillyGilly how is this looking on beta 10? Do you think anything else is needed or can this be closed?

**Comment by PhillyGilly** [comment]
I have just loaded it and the repeaters that were there have disappeared :-(
Curiously the connection still shows as on even when everything else is unavaiIable.
![image](https://github.com/user-attachments/assets/45bb0ab3-f9e4-49d2-b81e-06625e18eaf2)
If it helps I've include my diagnostics which do download.
[config_entry-heatmiserneo-01JFDFQA087AHVZE5CKREFMEY3.json](https://github.com/user-attachments/files/18187415/config_entry-heatmiserneo-01JFDFQA087AHVZE5CKREFMEY3.json)
Thank you

**Comment by ocrease** [comment]
@PhillyGilly The three sensors that are now greyed out were there due to a bug. They shouldn't be there. You can either remove them manually or delete and re-add the hub. 

The only things you will see for a repeater are the Connectivity sensor and the button. which I see doesn't have a name. That's actually a button to remove the repeater which is the "management" we discussed earlier in the thread. I will fix the button name

**Comment by ocrease** [comment]
@MindrustUK @PhillyGilly PR #228 to fix the name of the remove button

**Comment by MindrustUK** [comment]
Merged.

**Comment by ocrease** [comment]
@MindrustUK does beta 11 contain this merge? Looks like it doesn't?

**Comment by ocrease** [comment]
Never mind. I see you just released it again

**Comment by MindrustUK** [comment]
@ocrease Just re-releasing, I only noticed the first PR, I've pulled in the other two now and just re-released.

**Comment by PhillyGilly** [comment]
This is just for info/entertainment. I deleted my 'local' repeater so I can't see the remote repeater or the garden-studio neostat e.
My process for software updates is to delete the hub, update the software (now on Beta 11), restart HA and then add the hub back in.
![image](https://github.com/user-attachments/assets/4fd23e9e-2eca-4144-b3c6-e1494af5f2ae)
The remote repeater and not visible neostat are still in the devices list, the disconnected repeater is showing disconnected (which is true) but not consistent with the neostat where entities are shown as unavailable.
![image](https://github.com/user-attachments/assets/a9df30b0-9597-4b09-a5d7-4e8c4dab13fb)

**Comment by PhillyGilly** [comment]
Everything is as expected now with Beta10 running fine.
![image](https://github.com/user-attachments/assets/dde96cef-9bae-4030-95c4-b2071d2eba67)

**Comment by ocrease** [comment]
@PhillyGilly the neostats showing as Unavailable is expected. If you go to the device information page (where you can see all the sensors related to the same device) you would see that the Connectivity sensor shows as disconnected and all others are unavailable. Basically if the device is offline, everything will be unavailable except the connectivity sensor. For the repeater you see the same thing, the difference is that there is only one other entity on that device, eg the Remove button.

Regarding the remove button, I think in another thread you mentioned that you removed the repeater accidentally? I'm worried that others will also make this mistake. Maybe the Remove button should be disabled by default?

**Comment by PhillyGilly** [comment]
Hi. OK, I hadn't cross checked and I wasn't suggesting it was necessarily wrong but it was a bit counter intuitive as it appears to be giving a positive confirmation when in reality it is just showing that it's not connected. Yes, I removed a repeater when the button was labelled manage so it was user error. But I agree it should have a safety catch on it. Thanks.

**Comment by ocrease** [comment]
@MindrustUK @PhillyGilly PR #230 to disable the Remove button on repeaters by default

**Comment by MindrustUK** [comment]
@ocrease Confirmed behavior here, button not enabled by default on repeaters.

**Comment by PhillyGilly** [comment]
On Beta12 and everything looks good. Thanks for all the work and Happy Christmas 🎄🎄

**Comment by ocrease** [comment]
@MindrustUK I think this can be closed now, unless you can think of anything else?

**Comment by MindrustUK** [comment]
@ocrease Agreed, closing complete.
