### ISSUE TITLE
User experience when switching to away mode

### ISSUE THREAD

**Issue by ocrease** [MindrustUK/Heatmiser-for-home-assistant#206]
Thermostats now support three presets:

- Home (effectively Auto in the heatmiser app)
- Boost (sets Hold/Override for 30 minutes at +2 degrees from current target)
- Away (sets away mode on the hub. This means all connected thermostats/timers/plugs? are set to away)

![image](https://github.com/user-attachments/assets/1bddb0a7-ebee-4f7a-80c8-44be116ae325)

Unfortunately the user experience when setting away mode isn't great:

- The mode switches back to the previous mode soon after switching, and eventually switches back
  - We currently request an update from the hub after setting away mode, but the first update still says the devices are not away (or when turning off away mode, it still says away mode is on). Only the second update (eg 30 seconds later) picks up the updated information
- Only the thermostat where you made the change initially changes to away (then back due to the bug above). All the others don't change until the updated data is received from the hub
- The set temperature doesn't update until the updated data is received from the hub
- Timers (and plugs?) don't change "mode". The away sensor does pick up the change eventually

@MindrustUK I'm working on a PR to improve this. I would propose the following:

- Optimistically update the away flag on all thermostats/timers and set the temperature to the frost temperature on thermostats
- Don't request an immediate update from the hub. There is no point if the data hasn't updated yet
- Add an Away option to the Timers/Plug mode selection so that its easy to see that the timer is away without having to look at another sensor.

**Comment by MindrustUK** [comment]
Hi @ocrease given that the away mode change is merged do we need anything else on this ticket?

**Comment by ocrease** [comment]
@MindrustUK I think you can close it
