### ISSUE TITLE
Enable version selection on HACS

### ISSUE THREAD

**Issue by ocrease** [MindrustUK/Heatmiser-for-home-assistant#208]
I was looking at #165 and noticed this [comment](https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/165#issuecomment-2286363959) where they mention enabling beta versions in HACS. It looks like this works based on Github Releases, so it should be relatively easy to do:

HACS Docs - https://www.hacs.xyz/docs/publish/integration/
GitHub Docs - https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

It would make it a lot easier for users if they want to try out the dev branch.

Here is an example from a different integration:

Click on the menu and select Redownload:
![image](https://github.com/user-attachments/assets/eefe0247-458e-4652-bb4e-10233882eb4b)

You get a dialog to select the release:
![image](https://github.com/user-attachments/assets/65c3587f-992e-4e38-8edb-8f3253da084f)

And a list of releases, some of which can be marked as pre-release:
![image](https://github.com/user-attachments/assets/24c2611e-d4ab-4e81-82a6-35c38b36352c)

**Comment by MindrustUK** [comment]
Thanks for the heads up @ocrease I thought I'd end up having to setup multiple repositories last time I looked at this. If it's just releases that indeed is pretty easy. I'll take a look at this. I'm wondering if I should do something with GitHub automation rules for nightlies etc...

**Comment by MindrustUK** [comment]
Plus side, dev branch has a release now. Downside for some reason HACS is looping because it's retrieving the latest commit hash rather than the release, despite specifying the release version. I'm out of time today but will re-visit soon. I'll have to setup a nightly release to dev script or something too.

**Comment by ocrease** [comment]
@MindrustUK I think this might have to do with the tag/release name you are using. Try following the standard/recommended pattern:

![image](https://github.com/user-attachments/assets/b111e184-5a9f-469c-bc6f-337f55ff7ef8)

Eg v1.6.0 for the main branch
And v2.0.0-beta.1

(Or maybe  v3.0.0-beta.1 for the dev branch?). 

I don't think nightly releases are necessary or make sense unless there was a test suite to run. They'll just pollute the releases selection in HACS

**Comment by MindrustUK** [comment]
@ocrease Good suggestion on the naming. I'll give that a go and see if it resolves the issue.

I'd considered bumping a version 3 release given the entire re-written nature of the integration.

Hopefully I'll even remember to update the manifest json with the right version number this time! This is one of the points I considered for automation, as a human I'm terrible for missing things like this so handing it off to the machine maybe a good idea.

In a similar vein my plan with the pipeline was not necessarily nightlies but something more like "if last commit > 1 month package new dev" for those that truly want to sit on the bleeding edge.

I'd welcome commentary if you have any ideas on this one.

**Comment by MindrustUK** [comment]
@ocrease Best practices exist for a reason... That's fixed it. Thanks for the pointer. I'll get dev tagged appropriately and released.

**Comment by ocrease** [comment]
@MindrustUK the dev one is pointing to the wrong commit:

![image](https://github.com/user-attachments/assets/84fa95b9-340f-496f-9cf6-0da03c25870c)
 
That's the same commit as the Version_1.6 branch

**Comment by MindrustUK** [comment]
@ocrease :facepalm: fixed...

**Comment by ocrease** [comment]
@MindrustUK, added #211 for the manifest update and a couple of validators.

Other things that would be nice is adding pre-commit for linting, formatting etc. And tests eventually, but all that can be covered separately.

**Comment by MindrustUK** [comment]
Awesome, thanks once again @ocrease this should really improve things! I'll leave the ticket open until this is bedded in and well tested. We can pickup the other points you mentioned in further tickets. Pre-commit checking would be really nice to have down the line.

**Comment by ocrease** [comment]
@MindrustUK I've added some pre-commit hooks in #213. Take a look and see what you think.

**Comment by PhillyGilly** [comment]
This is great thanks. I'll have a look at v3.0.0-beta.1 now.

**Comment by MindrustUK** [comment]
Release process and improved github pipline work now complete. Closing complete.
