### ISSUE TITLE
NeoAir shows as Fan Only mode within integration (its not its Heat Only!!)

### ISSUE THREAD

**Issue by funks81** [MindrustUK/Heatmiser-for-home-assistant#210]
I have 4 NeoStats and 3 NeoAirs.  One of my NeoAirs shows in the integration as being fan only mode.  I've run the configure option a number of times for this - and selected Heat - but it always seems to revert back to Fan Only.  If you select from within the thermostat display - it says Fan Only - but selectable options are Heat and Off - if I select Heat - it sometimes changes to this - but within a minute or so reverts to fan only.  My other two NeoAirs work fine.  Integration doesn't raise this as an error - so not sure I've got any logs that would be helpful.

<img width="1440" alt="Screenshot 2024-11-04 at 10 55 14" src="https://github.com/user-attachments/assets/f836be1c-f973-4126-8955-f20465a34ddc">

**Comment by MindrustUK** [comment]
Hi @funks81 please provide the diagnostic logs from the integration for further investigation.

**Comment by ocrease** [comment]
@MindrustUK @funks81 This is fixed in the dev branch

**Comment by MindrustUK** [comment]
Thanks @ocrease !

@funks81 Try dev or wait for the next release (coming hopefully soon).

Closing as resolved for now.

**Comment by funks81** [comment]
Thanks!!
