### ISSUE TITLE
Incorrect Current Temps

### ISSUE THREAD

**Issue by nascot** [MindrustUK/Heatmiser-for-home-assistant#215]
Hi,

Thanks for the work so far on this integration!

I have a number of NeoStats... all appear to operate (change modes) OK via the HA plugin... issue is that none of them show the correct current temperature... they also don't seem to change.  E.g. stat on the wall will show 18.5, in home assistant it will be 20.3 (constantly).  Also note floor temp incorrect but I've not explored the previous issues yet for anything on that one.

In the native Neo app all the current temps etc. are correct.

Any ideas?  I just applied the recent update but was an issue before/after.

Thank you,

```
hvac_modes:
  - "off"
  - heat
min_temp: 7
max_temp: 35
target_temp_step: 0.5
current_temperature: 20.3
temperature: 16
hvac_action: idle
device_type: 12
low_battery: false
offline: false
standby: false
hold_on: false
hold_time: "0:00"
hold_temp: 21
floor_temperature: 127.5
preheat_active: false
hc_mode: HEATING
sensor_mode: BUILT_IN_AND_FLOOR
friendly_name: Hallway
supported_features: 385
```

**Comment by ocrease** [comment]
Hi @nascot, that's a weird one. In terms of ideas:

- could you download diagnostics from the integration and upload them here
- are there any errors in the home assistant logs? Eg could it be that HA is only able to communicate with the hub intermittently?
- Just to confirm, if you change the set temperature in HA, do you see the change in the Heatmiser App and/or the thermostat itself?
- You could try the dev branch (you should be able to get it through HACS now), although I can't think of any recent changes that would fix this.
- do you have a v1 or v2 hub?

**Comment by nascot** [comment]
Hi @ocrease, appreciate the prompt response...

- diagnostics... Is this debug logging? I tried clicking on the button to enable that in the Heatmiser integration and it starts downloading some huge log file (I stopped it at 2.4GB)
- Yes, error in HA log relating to a sensor which no longer exists... but I can't seem to delete that device anywhere in the integration or devices/entities screens (no longer on Neo app).  I have disabled the device but error keeps appearing.  Log below.  Looking at this it has occurred A LOT, so I've just disabled the integration.
- Yes, changing set temp in HA shows up on the physical stat and in the app.
- I have a V2 hub.

Thanks again.

```
Logger: homeassistant
Source: custom_components/heatmiserneo/button.py:66
integration: Heatmiser Neo Climate ([documentation](https://github.com/MindrustUK/Heatmiser-for-home-assistant))
First occurred: 30 October 2024 at 19:40:50 (25951 occurrences)
Last logged: 19:57:11

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in __async_calculate_state
    available = self.available  # only call self.available once per update cycle
                ^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/button.py", line 71, in available
    if self.data.offline:
       ^^^^^^^^^
  File "/config/custom_components/heatmiserneo/button.py", line 66, in data
    return neo_devices[self._neostat.name]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'Bedroom 1 Ensuite Sensor'
```

-

**Comment by ocrease** [comment]
@nascot Ok, that _might_ explain why the other sensors/devices are not updating. If its hitting that error, it might stop the whole update. In Settings -> Devices & Services -> Entities, if you filter by a status of `Not provided`, do you see anything?

![image](https://github.com/user-attachments/assets/936f59fe-fd8b-45cf-9f56-710ceb9c84be)

If not, maybe try deleting the hub and adding it again:

![image](https://github.com/user-attachments/assets/c96a5782-d1b3-4970-b0c0-58203935005d)

That screenshot also shows what I was talking about regarding diagnostics.

**Comment by nascot** [comment]
@ocrease ...

- Filtering by Not Provided - nothing was shown
- Deleted and reinstalled hub - temps now shown correctly (and also the background colour change (when heating) which I hadn't noticed wasn't showing).  The removed device no longer shown.
- Diagnostics - got it!

I suspect you are right; the error was looping and preventing the subsequent updating.

Hopefully that sorts that; if stats or whatever are added/removed in the future I shall uninstall and reinstall the hub.  I suppose issue could re-appear if one of the devices becomes unavailable for some other reason... but not sure what that would be.

Thanks for your assistance and enjoy the weekend.

**Comment by ocrease** [comment]
@nascot glad you got it working. Clearly there is scope for improvement for handling this situation.

I think if a device is still registered with the hub but can't communicate with the hub (say a battery powered device runs out of battery) the existing code should handle that. However if a device is removed from the hub, then I suspect we'll hit this issue. 

Had you recently removed the device and hadn't restarted HA? I suspect an HA restart would have solved your problem too.

I raised #216 to improve the handling.

**Comment by nascot** [comment]
@ocrease ... not certain, but sure that I've completed at least one HA restart since removing sensor.  It had been a couple of weeks and likely at least one HA update.  best of luck with the issue.
