### ISSUE TITLE
Wireless Air Sensor Issue

### ISSUE THREAD

**Issue by BNWEIN** [MindrustUK/Heatmiser-for-home-assistant#217]
Version 1.6.0.

![image](https://github.com/user-attachments/assets/4d3906aa-156a-4d75-a209-f1396372d8bf)

**Comment by ocrease** [comment]
Hi @BNWEIN I believe you moved from the dev/prerelease branch back to the release version 1.6. You'll have to either go back to the prerelease version or accept that you won't have long term statistics.

**Comment by ocrease** [comment]
Hi @BNWEIN did you try going back to the prerelease version? Is there a reason you went back to version 1.6?

**Comment by BNWEIN** [comment]
I went back to 1.6 because the hot water button worked better for me than it did in the pre release. (it didnt work at all in the pre release)

**Comment by ocrease** [comment]
@MindrustUK I think this can be closed
