### ISSUE TITLE
"cannot_connect"

### ISSUE THREAD

**Issue by adamsfarley** [MindrustUK/Heatmiser-for-home-assistant#233]
Hi,

I'm trying to connect my heatmiser v2 to HA - however getting the following error...

- Heatmiser-for-home-assistant v1.6.0
- Enabled "Legacy API"
- Able to ping device

![Screenshot 2024-12-28 140410](https://github.com/user-attachments/assets/728d7109-b6aa-4db8-a049-45590042a649)

Any help would be useful - Thanks

**Comment by ocrease** [comment]
Hi @adamsfarley, is this a new installation or an existing one that stopped working?

You could have a look at some of the suggestions in the FAQs - https://mindrustuk.github.io/Heatmiser-for-home-assistant/faqs.html

Is your hub on the same network/subnet/vlan as your Home Assistant instance?

**Comment by adamsfarley** [comment]
Hi,

It's a new installation now but it was working prior to this, I am connected via a mesh network in bridge mode from my router.

Gone through the troubleshooting guide, though not made any progress and everything comes as expected

**Comment by ocrease** [comment]
So this command worked as expected from your HA instance?

`printf '{"INFO":0}\0' | nc YOUR_DEVICE_IP_HERE 4242`

Maybe delete the integration entry and re-add it. Or did this happen when trying to add it?

Are you using the ip address or dns?

**Comment by adamsfarley** [comment]
Yes that command worked as expected and was able to ping the it.

I'll try deleting the integration again and add it back in.

When you say IP address do you mean for this `printf '{"INFO":0}\0' | nc YOUR_DEVICE_IP_HERE 4242`? If so, then yes.

**Comment by ocrease** [comment]
In that command, but also use the same ip when setting up the integration.

Can't think of much else, maybe you had an errant character (maybe an extra space if you copied it?)

**Comment by adamsfarley** [comment]
Do you mean here??

![image](https://github.com/user-attachments/assets/bac7cc47-8644-4fcd-b7f7-6ed947489621)

**Comment by ocrease** [comment]
Yeah exactly, you need to replace Neo-Hub with the IP address you used in the info command

**Comment by adamsfarley** [comment]
Amazing that’s worked - just read the guide again and had missed that bit off.

Thanks for your help on this.

**Comment by ocrease** [comment]
No problem, glad you got it working. I submitted PR #235 to add a small description underneath each field:

![image](https://github.com/user-attachments/assets/7ae08b8a-c94a-426d-a9a5-f07895162d75)
