### ISSUE TITLE
Add support for stats in Timer mode

### ISSUE THREAD

**Issue by leaskovski** [MindrustUK/Heatmiser-for-home-assistant#25]
Ok, so I thought I would start working on a crude switch type to implement a NeoStat running in timer mode.  I have the basic outline of the switch component with a basic on/off, and have it building the device up based off of the info JSON return.

What I would like to know is where you found out the JSON structures for the requests to be sent to the neohub.  How did you find them out, or what was the resource you used?

Thanks!

**Comment by MindrustUK** [comment]
If you mail support@heatmiser.com and ask for the API reference, Heatmiser will supply it. You'll probably need to sign an NDA first. That's what I did.

**Comment by leaskovski** [comment]
I managed to find a copy in someone else's git repo, so am using that.  Just making a couple of changes and will hopefully upload to my fork in the next couple of days.  Its probably really horribly done, but Python is not the language of my day job... but hey, if it works!  💃

**Comment by Trouble-51** [comment]
this was emailed to me by Heatmiser without an NDA or any restrictions

**Comment by PhillyGilly** [comment]
> I managed to find a copy in someone else's git repo, so am using that. Just making a couple of changes and will hopefully upload to my fork in the next couple of days. Its probably really horribly done, but Python is not the language of my day job... but hey, if it works! 💃

@leaskovski Thanks for this. I'll give it a run and let you know. I've got neo-stats running in "standard UFH mode", neo-stat E controlling electric UFH with air temperature sensors, and neo-stat HW providing timing signal(s) to my boiler for hot water. If I can figure out what you've don, I'll see if I can take it further.

**Comment by leaskovski** [comment]
@PhillyGilly I just updated my fork of the repo to change the component into its own platform so that switches load properly.  I migrated the repo over to a HACS format so that I could update and load in my changes easier with my system, so I haven't submitted a PR.  If I can figure out how to do that with the HACS and Switch separately, I will get them submitted.

At the moment things seem to be working properly, where I used the neo hub app to turn my hot water on and off, and could see the HASS web portal updating properly.  Its all been cobbled together, but it seems to work for what I need it for.  There might be some horrible issues in there that I haven't found, but for the most of it, its working.

**Comment by jchasey** [comment]
I've got 3 NeoStats doing underfloor heating and one NeoAir that handles radiators and also is a timer for the Hot Water.

With the latest version I get the following error at startup:

2020-11-23 18:49:41 ERROR (MainThread) [homeassistant.components.switch] Error while setting up heatmiserneo platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/heatmiserneo/switch.py", line 35, in async_setup_entry
for device in NeoHubJson['devices']:
TypeError: 'bool' object is not subscriptable

**Comment by DrTree** [comment]
> I've got 3 NeoStats doing underfloor heating and one NeoAir that handles radiators and also is a timer for the Hot Water.
> 
> With the latest version I get the following error at startup:
> 
> 2020-11-23 18:49:41 ERROR (MainThread) [homeassistant.components.switch] Error while setting up heatmiserneo platform for switch
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
> await asyncio.shield(task)
> File "/config/custom_components/heatmiserneo/switch.py", line 35, in async_setup_entry
> for device in NeoHubJson['devices']:
> TypeError: 'bool' object is not subscriptable

Do you have it configured in configuration.yml
If you do you should remove from there and add via the integrations flow (see readme).

I think we should create an issue to stop the integration freaking out when people still have the configuration in yml

**Comment by jchasey** [comment]
No I'd removed that previously and configured it all via the integration flow. Then upgraded to the latest version that supports the switches and got the error. Was working fine with previous build.

**Comment by DrTree** [comment]
So from a quick look at the code - it looks like the hub is either not available or is timing out.
Have you tried removing and re-adding? Possibly the IP address changed.

**Comment by jchasey** [comment]
No the hub is on a static IP address. The error is repeated - once for the climate entity, once for the switch. I presume both on the NeoAir. Previously it was configured as two climate entities - once for the heating, one for the hot water.

**Comment by DrTree** [comment]
I’d still advise you remove, restart then re-add the integration.
(Sorry in advance if you’ve done this, not totally clear from your previous comment)

**Comment by jchasey** [comment]
Ok, that did, has come up ok now, thanks for the help!

**Comment by PhillyGilly** [comment]
@leaskovski had a few moments to get back to this and I can't see how to get your fork from the integration, if I reinstall, it looks like its taking me back to the original  mindrust fork

**Comment by leaskovski** [comment]
@PhillyGilly not sure I understand what you are doing... sorry, its been a hectic past couple of weeks at work!  If you are referring  to HACS integration and adding it to HACs, then in theory the MindrustUK repo is in the correct format now, so you should just be able to use that.

**Comment by PhillyGilly** [comment]
I've got the Mindrust repo working, but I wanted to try your fork with the clock function, and I don't know if that is simply a matter of copying your .py file over his?

**Comment by leaskovski** [comment]
@PhillyGilly , the timer functionality should be in the Mindrust repo now as it was merged the other week.  If you are using HACs, then it should just be the case of updating the integration via the repo, otherwise you should pull another copy of the repo.  I think I am totally misunderstanding something here.

**Comment by PhillyGilly** [comment]
@leaskovski Thanks for your patience. I'm running HACS but the there's no obvious way to update there 
![image](https://user-images.githubusercontent.com/56273663/102074408-a8eba300-3dfc-11eb-87de-b1888efd4f10.png)
I alos tried uninstalled and reinstalled the integration without success,
However uninstalling, and deleting the custom configuration directory before reinstalling worked fine. 
I don't know if that's user error or a bug. Cheers.

**Comment by leaskovski** [comment]
@PhillyGilly's issue with adding the component to HACS is here, #57

**Comment by leaskovski** [comment]
Closed off as the PR for this is now merged.
