### ISSUE TITLE
Error while setting up heatmiserneo platform for climate

### ISSUE THREAD

**Issue by seanmccabe** [MindrustUK/Heatmiser-for-home-assistant#30]
Attempted to set this up today with this config:

```
climate:
  - platform: heatmiserneo
    host: 192.168.x.x
    port: 4242
```

But getting the following errors in Home Assistant (v 0.114.3):

First:

> Setup of climate platform heatmiserneo is taking over 10 seconds.

Then:

> Error while setting up heatmiserneo platform for climate

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/heatmiserneo/climate.py", line 73, in setup_platform
    for device in NeoHubJson['devices']:
TypeError: 'bool' object is not subscriptable`

The Neo hub is definately on that IP address, and I haven't found any other similar issues going on, so wondering if its just the Home Assistant version, or an error I've made in install, or perhaps it is a genuine bug?!

Let me know if you need any further info.

**Comment by PhillyGilly** [comment]
You can set it up using "integrations" see issue #34 above.

**Comment by MindrustUK** [comment]
Configuration has all changed. Closing this issue as behavior has changed.
