### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by stikonas** [MindrustUK/Heatmiser-for-home-assistant#32]
Hi, I'm working on a PR for this repo (adding/configuring via integrations UI page it's still WIP and will only be ready a bit later). But that got me thinking about the license of this component. I think there is a problem.

This component is released under GPL version 2 (often software is released under GPL version 2 or any later version but it does not seem to be the case there, there is no mention of "later" anywhere in the source).

Home Assistant is released under Apache 2.0 license which is incompatible with GPL2 (It is however compatible with GPL3).

So I think we need to change license to either "GPL 3", "GPL 3 or any later version" or "Apache 2.0". Probably the latter would be best if you ever hope of upstreaming this component. In any case this would need approval from previous contributors. Any thoughts?

@MindrustUK @jchasey  @mpredfearn @Mooseh81

**Comment by MindrustUK** [comment]
I'm happy enough to re-license my work if anyone wants to upstream it. As per your comments it would take all other contributes to agree before I can change the license. Your reasoning for Apache 2.0 makes sense. I guess we'll see if others reply.

**Comment by jchasey** [comment]
Likewise from me

**Comment by mpredfearn** [comment]
Yes, I'm fine with changing the license.

**Comment by stikonas** [comment]
Also ping @ntompson

**Comment by stikonas** [comment]
ping @PhillyGilly

**Comment by PhillyGilly** [comment]
Also fine by me. Sorry I was a bit slow on the uptake with the ping.

**Comment by DrTree** [comment]
Yes, fine by me.
