### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by PhillyGilly** [MindrustUK/Heatmiser-for-home-assistant#34]
Brilliant on the new Integration. Thanks.
Is it worth adding a bit to the read.me or Wiki to steer the innocent here?
![HowToIntegrate](https://user-images.githubusercontent.com/56273663/98438130-07c44b00-20e0-11eb-8895-166cb856643a.png)
![Config](https://user-images.githubusercontent.com/56273663/98438427-fb40f200-20e1-11eb-8437-a0288548082b.png)

Also "neo-hub" didn't work for me. I had to add the actual URL. That may be a neohub  gen1 issue?

**Comment by PhillyGilly** [comment]
If you are looking for an icon here is one I pulled from the Android app, that looks pretty good. 
![heatmiserneo](https://user-images.githubusercontent.com/56273663/98095109-0dbcf080-1e82-11eb-940e-f1a4dc2c7ae6.jpg)

**Comment by andriuss-xilinx** [comment]
Icon was already submitted, but it took time to propagate. Now it's there.  I don't think we can use icon from android app, probably due to licencing issues...

Regarding readme, feel free to update. My goal is to try to upstream this integration, so if you can help with readme and documentation that would be very helpful.

**Comment by stikonas** [comment]
Icon was already submitted, but it took time to propagate. Now it's there.  I don't think we can use icon from android app, probably due to licencing issues...

Regarding readme, feel free to update. My goal is to try to upstream this integration, so if you can help with readme and documentation that would be very helpful.

**Comment by PhillyGilly** [comment]
> Icon was already submitted, but it took time to propagate. Now it's there. I don't think we can use icon from android app, probably due to licencing issues...
> 
> Regarding readme, feel free to update. My goal is to try to upstream this integration, so if you can help with readme and documentation that would be very helpful.

Read.me update pull request there now.
I have a config error which I don't understand and doesn't appear to impact operation.
![image](https://user-images.githubusercontent.com/56273663/98443374-c7c28f80-2102-11eb-8ddd-5e978dc6e847.png)
Is this normal? in which case I will amend the read.me

**Comment by stikonas** [comment]
> > Icon was already submitted, but it took time to propagate. Now it's there. I don't think we can use icon from android app, probably due to licencing issues...
> > Regarding readme, feel free to update. My goal is to try to upstream this integration, so if you can help with readme and documentation that would be very helpful.
> 
> Read.me update pull request there now.
> I have a config error which I don't understand and doesn't appear to impact operation.
> ![image](https://user-images.githubusercontent.com/56273663/98443374-c7c28f80-2102-11eb-8ddd-5e978dc6e847.png)
> Is this normal? in which case I will amend the read.me

Hmm, not too sure. Do you still have old configuration entries in `configuration.yml` ?

**Comment by PhillyGilly** [comment]
Yes. I had the old stuff in my config.  I assumed that they were written in by the Integration. Like with automations. Doh!
Regarding the IP/hostname: I don't think all routers will resolve the host name hence my comments.
I've got quite a lot of kit running on an IOT network on a Ubiquity/Unifi system.
Not everything is well behaved so its all on Static IP but I'll see what happens if I "liberate" the neo-hub.

**Comment by stikonas** [comment]
Is there anything else left to do here or can this be closed? (Note I don't have permissions to close it.) 

@PhillyGilly also, can you leave a comment on https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/32 since you have now made a contribution.

**Comment by MindrustUK** [comment]
Merged in the readme and made a few edits so I'll close it off.

**Comment by Trouble-51** [comment]
I cannot find the integration, I on the latest version of HA. Any suggestion where it might be? I deleted the entry in the configuration file.

Thanks

**Comment by stikonas** [comment]
> I cannot find the integration, I on the latest version of HA. Any suggestion where it might be? I deleted the entry in the configuration file. Thanks

You still need to get latest git version of this plugin and put into the custom_components folder in your config folder. This plugin is not yet upstreamed into HA itself (and more changes are needed before this can even be attempted).

**Comment by Trouble-51** [comment]
OK, I put everything back and get the following error:

Invalid config for [climate.heatmiserneo]: [host] is an invalid option for [climate.heatmiserneo]. Check: climate.heatmiserneo->host. (See ?, line ?). 

this is the config entry:

climate:    
  - platform: heatmiserneo   
    host: 192.XXX.X.XX
    port: 4242

was there a change in using “host”?

**Comment by stikonas** [comment]
You don't need config entry now. I would suggest removing config entry for now and adding integration via GUI.

I can try to check if it's possible to import old configs. But not today....

**Comment by Trouble-51** [comment]
Thanks, it’s working using the integration!

**Comment by DrTree** [comment]
I think I'm missing something, I don't see this in the list.
Do I need to be on a pre-release version of HA?

**Comment by stikonas** [comment]
> I think I'm missing something, I don't see this in the list.
> Do I need to be on a pre-release version of HA?

No, nothing to do with HA version.

Have you installed this integration into custom_components folder (for now it's exactly the same as before my change).
