### ISSUE TITLE
Installation documentation?

### ISSUE THREAD

**Issue by haakonstorm** [MindrustUK/Heatmiser-for-home-assistant#4]
Thanks for the great work on this component.

I'm having issues getting the component configured in to my setup. 
Any chance for documentation?

I've downloaded the script to
config/custom_components/climate/heatmiserneo.py

I rename this to heatmiserneo/climate.py due to info from the logs.

Configuration.yaml:

climate:
  - platform: heatmiserneo
    host: a.b.c.d
    port: 4242

Had to investigate a bit to find out which IP was to the Heatmiser Neo. nmap -Pn and looking for port 4242 solved it (something for the docs?)

Both my neo-thermostats show up perfectly and I can set the temperature for both. Very nice.

* How do I set the "HOLD" function? When somebody comes home, or I'm going to sit in the study for couple of hours, I usually set the HOLD function to boost the temperature for some time. 
No big deal if this is not implemented, I'll figure a way to just reset it back to a regular temperature. Working on getting multiple subdomain nginx/caddy/traefik up and running so I can get node-red working, but that has proved really difficult to get working.

* Any chance of implementing the neoPlug? It's a Heatmiser 220v / 110v plug, that can be turned on and off. I got one for free. It shows up as a thermostat with 255 degrees. Tried to turn it off to see if that changed the degrees, but it didnt.

Keep up the great work!

**Comment by MindrustUK** [comment]
Thanks for opening an issue. I'll put some documentation together when I get some time.

Hold isn't implemented yet. I need to do further investigation into a variable time control for this. I'd like to put it all on the climate control, but I'm not sure how viable this will be in HASS. Watch this space.

NeoPlug support, good shout. I don't have one to test with, but it certainly shouldn't be appearing as a thermostat. I'll consider that a bug in this component and look to implementing a switch type component to support the NeoPlugs when I get round to it.

I can't promise any speed with the above due to other commitments. I'll drop a note as I get round to them. Have a second theromstat due in a week or two to do more testing with.

**Comment by MindrustUK** [comment]
@haakonstorm 

Can you please run the following:

```printf '{"INFO":0}\0' | nc <NEOHUBIP> 4242```

This should return a JSON string, can you paste that into this issue so I can look at adding NeoPlug support? As I don't have one of these I'll need example data.

**Comment by haakonstorm** [comment]
$ printf '{"INFO":0}\0' | nc 192.168.1.14 4242
{"devices":[{"AWAY":false,"COOLING":false,"COOLING_ENABLED":false,"COOLING_TEMPERATURE_IN_WHOLE_DEGREES":0,"COOL_INP":false,"COUNT_DOWN_TIME":"0:00","CRADLE_PAIRED_TO_REMOTE_SENSOR":false,"CRADLE_PAIRED_TO_STAT":false,"CURRENT_FLOOR_TEMPERATURE":127,"CURRENT_SET_TEMPERATURE":"21.0","CURRENT_TEMPERATURE":"22.8","DEMAND":false,"DEVICE_TYPE":1,"ENABLE_BOILER":false,"ENABLE_COOLING":false,"ENABLE_PUMP":false,"ENABLE_VALVE":false,"ENABLE_ZONE":false,"FAILSAFE_STATE":false,"FAIL_SAFE_ENABLED":false,"FLOOR_LIMIT":false,"FULL/PARTIAL_LOCK_AVAILABLE":false,"HEAT/COOL_MODE":false,"HEATING":false,"HOLD_TEMPERATURE":30,"HOLD_TIME":"0:00","HOLIDAY":false,"HOLIDAY_DAYS":0,"HUMIDITY":0,"LOCK":false,"LOCK_PIN_NUMBER":"0000","LOW_BATTERY":false,"MAX_TEMPERATURE":"30.0","MIN_TEMPERATURE":"23.0","MODULATION_LEVEL":0,"NEXT_ON_TIME":"6 days 08:00","OFFLINE":false,"OUPUT_DELAY":false,"OUTPUT_DELAY":0,"PREHEAT":false,"PREHEAT_TIME":"255:255","PROGRAM_MODE":"5DAY/2DAY","PUMP_DELAY":false,"RADIATORS_OR_UNDERFLOOR":false,"SENSOR_SELECTION":"BUILT_IN_AIR_SENSOR","SET_COUNTDOWN_TIME":0,"STANDBY":false,"STAT_MODE":{"4_HEAT_LEVELS":true,"MANUAL_OFF":true,"THERMOSTAT":true},"TEMPERATURE_FORMAT":false,"TEMP_HOLD":false,"TIMECLOCK_MODE":false,"TIMER":false,"TIME_CLOCK_OVERIDE_BIT":false,"ULTRA_VERSION":0,"VERSION_NUMBER":101,"WRITE_COUNT":113,"ZONE_1PAIRED_TO_MULTILINK":true,"ZONE_1_OR_2":false,"ZONE_2_PAIRED_TO_MULTILINK":false,"device":"Oppe"},{"AWAY":false,"COOLING":false,"COOLING_ENABLED":false,"COOLING_TEMPERATURE_IN_WHOLE_DEGREES":0,"COOL_INP":false,"COUNT_DOWN_TIME":"0:00","CRADLE_PAIRED_TO_REMOTE_SENSOR":false,"CRADLE_PAIRED_TO_STAT":false,"CURRENT_FLOOR_TEMPERATURE":127,"CURRENT_SET_TEMPERATURE":"0.0","CURRENT_TEMPERATURE":"255.255","DEMAND":false,"DEVICE_TYPE":6,"ENABLE_BOILER":false,"ENABLE_COOLING":false,"ENABLE_PUMP":false,"ENABLE_VALVE":false,"ENABLE_ZONE":false,"FAILSAFE_STATE":false,"FAIL_SAFE_ENABLED":false,"FLOOR_LIMIT":false,"FULL/PARTIAL_LOCK_AVAILABLE":false,"HEAT/COOL_MODE":false,"HEATING":false,"HOLD_TEMPERATURE":1,"HOLD_TIME":"0:00","HOLIDAY":false,"HOLIDAY_DAYS":0,"HUMIDITY":0,"LOCK":false,"LOCK_PIN_NUMBER":"0000","LOW_BATTERY":false,"MAX_TEMPERATURE":"255.255","MIN_TEMPERATURE":"255.255","MODULATION_LEVEL":0,"NEXT_ON_TIME":"255 days 255:255","OFFLINE":false,"OUPUT_DELAY":false,"OUTPUT_DELAY":0,"PREHEAT":false,"PREHEAT_TIME":"255:255","PROGRAM_MODE":"5DAY/2DAY","PUMP_DELAY":false,"RADIATORS_OR_UNDERFLOOR":false,"SENSOR_SELECTION":"BUILT_IN_AIR_SENSOR","SET_COUNTDOWN_TIME":0,"STANDBY":false,"STAT_MODE":{"4_HEAT_LEVELS":true,"MANUAL_ON":true,"TIMECLOCK":true},"TEMPERATURE_FORMAT":false,"TEMP_HOLD":false,"TIMECLOCK_MODE":false,"TIMER":false,"TIME_CLOCK_OVERIDE_BIT":false,"ULTRA_VERSION":0,"VERSION_NUMBER":79,"WRITE_COUNT":77,"ZONE_1PAIRED_TO_MULTILINK":true,"ZONE_1_OR_2":false,"ZONE_2_PAIRED_TO_MULTILINK":false,"device":"neoPlugg"},{"AWAY":false,"COOLING":false,"COOLING_ENABLED":false,"COOLING_TEMPERATURE_IN_WHOLE_DEGREES":0,"COOL_INP":false,"COUNT_DOWN_TIME":"0:00","CRADLE_PAIRED_TO_REMOTE_SENSOR":false,"CRADLE_PAIRED_TO_STAT":false,"CURRENT_FLOOR_TEMPERATURE":26,"CURRENT_SET_TEMPERATURE":"25.0","CURRENT_TEMPERATURE":"20.9","DEMAND":false,"DEVICE_TYPE":1,"ENABLE_BOILER":false,"ENABLE_COOLING":false,"ENABLE_PUMP":false,"ENABLE_VALVE":false,"ENABLE_ZONE":false,"FAILSAFE_STATE":false,"FAIL_SAFE_ENABLED":false,"FLOOR_LIMIT":false,"FULL/PARTIAL_LOCK_AVAILABLE":false,"HEAT/COOL_MODE":false,"HEATING":true,"HOLD_TEMPERATURE":22,"HOLD_TIME":"0:00","HOLIDAY":false,"HOLIDAY_DAYS":0,"HUMIDITY":0,"LOCK":false,"LOCK_PIN_NUMBER":"0000","LOW_BATTERY":false,"MAX_TEMPERATURE":"22.0","MIN_TEMPERATURE":"18.0","MODULATION_LEVEL":0,"NEXT_ON_TIME":"5 days 23:55","OFFLINE":false,"OUPUT_DELAY":false,"OUTPUT_DELAY":0,"PREHEAT":false,"PREHEAT_TIME":"255:255","PROGRAM_MODE":"5DAY/2DAY","PUMP_DELAY":false,"RADIATORS_OR_UNDERFLOOR":false,"SENSOR_SELECTION":"BUILT_IN_AND_FLOOR","SET_COUNTDOWN_TIME":0,"STANDBY":false,"STAT_MODE":{"4_HEAT_LEVELS":true,"MANUAL_OFF":true,"THERMOSTAT":true},"TEMPERATURE_FORMAT":false,"TEMP_HOLD":false,"TIMECLOCK_MODE":false,"TIMER":false,"TIME_CLOCK_OVERIDE_BIT":false,"ULTRA_VERSION":0,"VERSION_NUMBER":101,"WRITE_COUNT":51,"ZONE_1PAIRED_TO_MULTILINK":true,"ZONE_1_OR_2":false,"ZONE_2_PAIRED_TO_MULTILINK":false,"device":"Gangen"}]}

**Comment by MindrustUK** [comment]
That's great thanks!

I'll open a separate issue to exclude the NeoPlug from interfering. I'll also look into a separate project to add wider support for the Heatmiser system which would include the NeoPlug.

**Comment by haakonstorm** [comment]
Regarding your "TODO note to self" on the README.md on the front page,

this will show the IP for the Heatmiser NeoHub:
nmap -Pn  -p4242 -oG - 192.168.1.0/24 | grep 4242 | grep -i open

**Comment by MindrustUK** [comment]
Added your suggestion to the read me.

**Comment by MindrustUK** [comment]
Added documentation and opened seperate issues for Hold functionality and NeoPlug Support.

**Comment by haakonstorm** [comment]
https://www.heatmiser.com/en/2017/05/16/room-thermostat-with-remote-sensor/ 
I have one of these that I don't use, brand new, I could send it to you if you are interested.
Perhaps someone else can provide the hub, it doesn't work with mine and they refuse a return. (Heatmiser should provide you at least units, for your great work! If you include their most sold units perhaps you could get paid for your work.)

**Comment by MindrustUK** [comment]
@haakonstorm Thanks for the offer but I'm not sure it would aid in any of the dev work as it seems to be a stand alone device with no links to any networking.

I certainly woudln't turn down any donations of hardware to further this work if Heatmiser are reading ;)
