### ISSUE TITLE
Neoplug shows up as theromostat

### ISSUE THREAD

**Issue by DrTree** [MindrustUK/Heatmiser-for-home-assistant#40]
As the title suggests 😁

It looks like neostats also show as DEVICE_TYPE = 0

**Comment by MindrustUK** [comment]
@DrTree Thanks for the PR and your contribution to the project, This has been merged. Please also see on going discussion at: [https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/32](https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/32) with regards to licenses.
