### ISSUE TITLE
Splitting device specific code into a separate library

### ISSUE THREAD

**Issue by stikonas** [MindrustUK/Heatmiser-for-home-assistant#45]
While device specific code is very simple in this integration (just TCP and json) it would be best to split it into a seprate library.

In particular this is a Home Assistant rule: https://developers.home-assistant.io/docs/creating_platform_index/

> One Home Assistant rule is that the integration should never interface directly with devices. Instead, it should interact with a third-party Python 3 library. This way, Home Assistant can share code with the Python community and keep the project maintainable.

It might be possible to reuse something like https://gitlab.com/virchow-personal/neohubby/ but on the other hand, if we have a few interested people here in this project, creating our own project might be more flexible for us.

CC: @DrTree

**Comment by andriuss-xilinx** [comment]
@PhillyGilly let's move discussion here.

Yeah, that library  https://github.com/RJ/heatmiser-neohub.py is also nice.

**Comment by DrTree** [comment]
The same author has another repo here:
https://github.com/RJ/homeassistant-heatmiser-neohub-component

**Comment by andriuss-xilinx** [comment]
Yeah, probably worth contacting him and see if we can combine efforts.

One minor issue we need to clarify is licensing. His code does not seem to have any.

**Comment by PhillyGilly** [comment]
Not sure if this is the right place to mention this but in climate.py line 66 the call uses an "INFO " command. The API v2.6 says:  INFO command is deprecated and GET_LIVE_DATA should be used instead.

**Comment by stikonas** [comment]
> Not sure if this is the right place to mention this but in climate.py line 66 the call uses an "INFO " command. The API v2.6 says: INFO command is deprecated and GET_LIVE_DATA should be used instead.

Yeah, I saw that too...

**Comment by stikonas** [comment]
None of the upstreams seem to be responsive, so I've just started a new async library to talk to NeoHub2

For now I put it on my local server:
https://git.stikonas.eu/andrius/neohub2

There isn't much to look at yet, just added first function to get firmware version but hopefully I can expand it to be more complete.

**Comment by stikonas** [comment]
> Not sure if this is the right place to mention this but in climate.py line 66 the call uses an "INFO " command. The API v2.6 says: INFO command is deprecated and GET_LIVE_DATA should be used instead.

This is a bit strange. How do we read current temperature from `GET_LIVE_DATA`? There is `RECENT_TEMPS` array in it but I'm not sure if it has the latest data instead of just historic data.

**Comment by PhillyGilly** [comment]
I'm guessing that one of the recent values is the current value. It's not documented, is it? My guess is its either the first or the last. Perhaps run the INFO and GET_LIVE_DATA at the same time and compare output. If its not obvious I can ask Heatmiser directly.

**Comment by stikonas** [comment]
Actually, I somehow missed the current temperature in `GET_LIVE_DATA`. It's now called `ACTUAL_TEMP`... I'll try to implement it once I have some more time.

**Comment by PhillyGilly** [comment]
Python isn't my language but I had a quick attempt at writing a very short script to talk to the Neohub directly with a view to looking at Current & Actual data. (This would also help me manage my repeaters which you can't do at all using the app where you can add but not view or delete them.). I didn't get very far as I ran into buffers issues. It looks like these are handled by HA in the current apps, so I'll need to dig in there next.

**Comment by DrTree** [comment]
> For now I put it on my local server:
> https://git.stikonas.eu/andrius/neohubapi

Not sure how to contribute to private git server.
Is there any chance we could move it over to Github?

**Comment by stikonas** [comment]
> > For now I put it on my local server:
> > https://git.stikonas.eu/andrius/neohubapi
> 
> Not sure how to contribute to private git server.
> Is there any chance we could move it over to Github?

Yeah, I thought to move it later too, maybe next weekend (although, not sure if Githhub or Gitlab...). Note you can login to all of them (including git.stikonas.eu with your GH account).

**Comment by DrTree** [comment]
> Note you can login to all of them (including git.stikonas.eu with your GH account).
Ah, I didn't know that... That does make life easier!

**Comment by DrTree** [comment]
I've made a draft PR #53 
Removed quite a bit of code from the climate.py which is always a good sign 😁

**Comment by andriuss-xilinx** [comment]
> I've made a draft PR #53
> Removed quite a bit of code from the climate.py which is always a good sign grin

Oh, you already started porting :O.

I am still thinking how to properly unify GET_ZONES and GET_LIVE_DATA.
In neohubapi you can control thermostats with class returned by get_zones, but all info is in get_live_data...

**Comment by stikonas** [comment]
> I've made a draft PR #53
> Removed quite a bit of code from the climate.py which is always a good sign grin

Oh, you already started porting :O.

I am still thinking how to properly unify GET_ZONES and GET_LIVE_DATA.
In neohubapi you can control thermostats with class returned by get_zones, but all info is in get_live_data...

**Comment by DrTree** [comment]
> 
> Oh, you already started porting :O.
> 

I'm a big believer that you learn a lot more by having an end-to-end working skeleton.
I feel that is the case here :)

**Comment by stikonas** [comment]
> I'm a big believer that you learn a lot more by having an end-to-end working skeleton.
> I feel that is the case here :)

Oh I'm not complaining. I also thought that it might be good to have some feedback...
There are some things that I was/am not sure about without active library users...

E.g. most functions return True/False on success or failure, but maybe we need to return error messages too...

**Comment by stikonas** [comment]
I've published library candidate on https://pypi.org/project/neohubapi/

**Comment by stikonas** [comment]
This is now done.
