### ISSUE TITLE
Feature: Add service to sync NeoStat clocks

### ISSUE THREAD

**Issue by ntompson** [MindrustUK/Heatmiser-for-home-assistant#46]
I've noticed that my NeoStats lose time reasonably quickly (they seem to run slow). There are a couple of commands that can sync the stat clocks (and set DST). So it would be handy to have a custom service that could invoke the commands every so often (triggered by an HA automation). I'd do a PR, but I'm not too sure how to do custom services (and a little lazy).

Something like the following would work:

```py
def sync_clocks(dst_on = False):
    response = json_request({"MANUAL_DST": 1 if dst_on else 0})
    response = json_request({"NTP_ON": 0})
```

Interested in your thoughts.

**Comment by stikonas** [comment]
hmm, I just enabled NTP on my neohub (in fact I port forwarded NTP requests to my local NTP server). But I guess if you don't want NTP that would be fine...

**Comment by ntompson** [comment]
What I should have added is that enabling NTP seems to be temporary - it corrects the clock at the time the call is made, but the clock drifts from that point onwards. So I find that I need to call `NTP_ON` every so often (maybe weekly) to keep it in check.

**Comment by stikonas** [comment]
> So it's not that I don't want NTP, it seems that this is the method necessary to keep NTP working.

Hmm, interesting.... My experience was that time is not drifting away when NTP is enabled. If it happens on some hardware then something like this might make sense.

Maybe it's worth asking heatmiser support? They seem to be quite helpful.

**Comment by ntompson** [comment]
That's a good suggestion - I'll drop them a note. I've started looking more closely at this. I find that my stats are losing something in the order of 10 seconds per day. An inspection of `READ_DCB` confirms that NTP has stopped after a time (I'm not sure how long it takes). 

For example after two or three days:

```
$ date && python3 ./test-stat.py
Sat 21 Nov 17:04:35 AEDT 2020
json_request: {'READ_DCB': 100} 
json_response: {..., "DSTAUTO":false,"DSTON":false, ..., "NTP":"Stopped", ..., "TIME":"17:04:07","TIMEZONE":10.0,"TIMEZONESTR":"", ...} 
```

Then I run update DST and activate NTP, and it comes good:

```
date && python3 ./test-stat.py
Sat 21 Nov 17:05:22 AEDT 2020
json_request: {'MANUAL_DST': 1} 
json_response: {"result":"Updated time"} 
json_request: {'NTP_ON': 0} 
json_response: {"result":"ntp client started"} 
{'result': 'ntp client started'}
json_request: {'READ_DCB': 100} 
json_response: {..., "DSTAUTO":false,"DSTON":true, ... ,"NTP":"Running", ... ,"TIME":"17:05:04","TIMEZONE":10.0,"TIMEZONESTR":"", ...}
```

But a few days later, I will find NTP not running and the clocks starting to drift again. 

Anyway, I'll come back if / when I get a response.

**Comment by stikonas** [comment]
Maybe something was setting the time in the meantime?

Messing up with time (e.g. with `SET_TIME` call) sets NTP into "Stopped" state

**Comment by ntompson** [comment]
On this occasion, you're probably right - I had been stuffing around a bit, so it's likely that the most recent thing I did was set the time manually in the app. I'll keep an eye on it over the next couple of days. NTP is still running today, and there hasn't been any clock drift. Trick here will be to catch what causes NTP to stop running (apart from me interfering).

**Comment by ntompson** [comment]
Coming back to this, I think I've got a better idea of what's going on now. First some observations:

- If I touch nothing, NTP runs reliably - at least it has done for the last 2-3 weeks
- Any modification to time in the Heatmiser Neo app causes NTP to stop
- There is no way to restart NTP from the app
- The app provides no method to set / clear daylight savings
- It's possible to set / clear DST through the API and not break NTP

So for geographies with daylight savings, I think we need something in the integration to help manage daylight savings, as there is no way for an ordinary user to do this without breaking NTP (other than sending commands through the API).

My suggestion is to offer a custom service in the integration to set / clear daylight saving as a custom HA service. The HA user could then create an automation to set / clear DST using the custom service in the Heatmiser integration, triggered at the appropriate time.

If we wanted to go a bit further, we could also:

- Offer a custom service to set timezone (GMT offset) - anyone living outside the three app supported timezones is out of luck
- Offer a custom service to start NTP

A better option for the second point might be to start NTP as a hidden API call as part of the DST / timezone custom integration services.

Interested in your thoughts.

**Comment by stikonas** [comment]
Adding custom service sounds reasonable.

It seems that some other integrations also do that: https://github.com/home-assistant/core/blob/dev/homeassistant/components/ecobee/climate.py#L263

**Comment by ntompson** [comment]
Nice one - that's a perfect example.

**Comment by seanmccabe** [comment]
An ability to set the time would be awesome.
Whenever the thermostat loses connection to the hub, or the hub loses power, the time on the thermostat seems to reset to GST. 
Not helpful when I'm in NZ on DST.

Only way to reset it is to go into the app, set the clock to GST (as it still shows NZ in there), wait a few minutes and set it back to NZ again.

**Comment by ankohanse** [comment]
While this is not yet in the MindrustUK code, I used the following workaround. Added it here because it might be usefull for others.

in `configuration.yaml` add:
`shell_command: !include shell_commands.yaml`

in `shell_commands.yaml` add:
`neohub_sync_time: echo -e '{"NTP_ON":0}\x00\r' | nc 192.168.88.204 4242`

in `automations.yaml` add:
`- id: '1692600497550'
  alias: NeoHub Sync Time
  description: ''
  trigger:
  - platform: time_pattern
    hours: '00'
    minutes: '00'
    seconds: '00'
  condition: []
  action:
  - service: shell_command.neohub_sync_time
    data: {}
    response_variable: neohub_sync_time_response
  mode: single
`

**Comment by ocrease** [comment]
@MindrustUK I believe #221 should deliver everything being asked for in this thread.

- There is a switch to turn NTP on and off (an automation could be written to automatically turn it back on if it goes off for whatever reason)
- A select drop down allows setting the DST rules which I think just sets when the clocks go forward and back. Only UK, EU (same as UK I thought) and NZ are supported. For anyone outside those regions they can use the same select entity to turn DST on or off manually (via an automation for example)
- A select dropdown to set the timezone. This should be the non DST timezone. Eg UK would always be UTC. I think the hub gets the UTC time from NTP, then uses the timezone to add an offset and then DST to add a further +1 offset either automatically (via the UK, EU, NZ rules) or manually.

**Comment by MindrustUK** [comment]
@ocrease Thanks for the contribution as always. Merged, will release a beta once I've gone through other open tickets.

**Comment by ocrease** [comment]
I see @PhillyGilly gave this the thumbs up on the PR itself(#221). 

@MindrustUK do you think there is anything else to add here or can this be closed? Several other people contributed to the discussion, but most posts were a long time ago, not sure if we will get other feedback.

**Comment by MindrustUK** [comment]
@ocrease agreed, closing.
