### ISSUE TITLE
NorthBT document which may be useful to the project (NeoHub API)

### ISSUE THREAD

**Issue by rosscullen** [MindrustUK/Heatmiser-for-home-assistant#52]
@leaskovski @MindrustUK you may already be aware of this document but said I would let you know.

A UK company NorthBT have a product which interfaces with NeoHub https://www.northbt.com/products

Their reference document might contain some insights which may be useful to you
https://www.northbt.com/doc/driver/HeatmiserNeo%20Driver%20Manual.pdf

**Comment by stikonas** [comment]
I briefly looked at PDF, and I think Heatmiser's API documentation is more useful...
