### ISSUE TITLE
Replace deprecated API

### ISSUE THREAD

**Issue by robeving** [MindrustUK/Heatmiser-for-home-assistant#56]
According to Appendix B of the NeoHub API docs the INFO command is deprecated.

https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/18c00969edcbd271e99b7943b4b9a87a7a32fee7/custom_components/heatmiserneo/climate.py#L59

https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/18c00969edcbd271e99b7943b4b9a87a7a32fee7/custom_components/heatmiserneo/switch.py#L100

**Comment by PhillyGilly** [comment]
@robeving there was some discussion about this in #45 with @stikonas . I'm not sure how it concluded. I thought it had been implemented but with the move to HA integration (which I like but do not understand) I don't know how to see what .py my HA thinks it's running. BTW if you get a moment to comment on #57 that would be neat.

**Comment by stikonas** [comment]
Yes, in that library that I'm trying to write I have not used INFO at all. And there is some WIP PR (https://github.com/MindrustUK/Heatmiser-for-home-assistant/pull/53) by @DrTree that ports this integration to neohubapi.

https://git.stikonas.eu/andrius/neohubapi/

**Comment by stikonas** [comment]
Does anybody know if humidity data is available via `GET_LIVE_INFO`? It seems that the old `INFO` command had `HUMIDITY` field.

I can't see anything humidity related in `GET_LIVE_INFO` but then my devices are simple heating thermostats... Old info command was returning just `"HUMIDITY":0`.

I can't find anything in NeoHub API documentation either...

**Comment by stikonas** [comment]
Anyway, this is now done. We switched to neohubapi library that uses `GET_LIVE_INFO`. Maybe close this issue?

**Comment by MindrustUK** [comment]
Resolved by @stikonas Closing issue.
