### ISSUE TITLE
HA Integration broken

### ISSUE THREAD

**Issue by PhillyGilly** [MindrustUK/Heatmiser-for-home-assistant#57]
The integration with HA was working for me on 7th November.
I don't think the code on my HA updated in line with @leaskovski fork and I have resorted to attempting a reinstall of the Heatmiser Integration.
The instructions in the current readme.md are not working specifically at the point of adding the integration repository.
I'm running Home Assistant core 2012.12.0 on OS 5.8.
The readme.md says:
Step 1: Add to HACS
Open HACS Go to the Settings tab Add "https://github.com/MindrustUK/Heatmiser-for-home-assistant" as a repository as an "Integration" type. Go to the Integrations tab Search for "Heatmiser Neo Integration", select and install

There is no option in HACS to add a repository.
The Heatmiser Integration which used to sit alphabetically in this list isn't there anymore.
![image](https://user-images.githubusercontent.com/56273663/102781371-76f3b700-438f-11eb-8630-32e7fab2d1b8.png)

Compare this list with my previous screenshot in the readme.md
![image](https://user-images.githubusercontent.com/56273663/102781969-714aa100-4390-11eb-8305-cfd1ad0fcaca.png)

I have added repositories previously using the Supervisor Add-on function but the URL https://github.com/MindrustUK/Heatmiser-for-home-assistant isn't recognised as a repository, FWIW I would expect the URL to point to a file type *.git
![image](https://user-images.githubusercontent.com/56273663/102781709-0c8f4680-4390-11eb-9bb1-b10303f1ed67.png)

Can anybody advise?

**Comment by leaskovski** [comment]
@PhillyGilly sorry I didnt get around to replying to you before....  Anyway, hopefully these screens help...

The documentation for adding the repo to HACS can probably be written better, anyway this is where you add them from...
![image](https://user-images.githubusercontent.com/13252143/102904694-fc4b9a00-4469-11eb-83f8-ae4e226a0b72.png)
and then...
![image](https://user-images.githubusercontent.com/13252143/102904717-04a3d500-446a-11eb-9253-7f5c01446bc0.png)

**Comment by PhillyGilly** [comment]
@leaskovski Thank you. I can now see that it's a problem with my HACS which must have happened during an earliate. Hence the bizarre questions. I'll do a full reinstall of HACS shortly and make notes to update the readme.

**Comment by andriuss-xilinx** [comment]
By the way, you can still use it without HACS either... Just as before if you copy it into confit/custom_components manually it appears in the list.

**Comment by stikonas** [comment]
By the way, you can still use it without HACS either... Just as before if you copy it into confit/custom_components manually it appears in the list.

**Comment by PhillyGilly** [comment]
Thank you @leaskovski and @stikonas. I will update the readme.md to reflect this.
