### ISSUE TITLE
Update to neohubapi - thermostats no longer working

### ISSUE THREAD

**Issue by Unthred** [MindrustUK/Heatmiser-for-home-assistant#62]
Hi, the error in this seems different from https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/61 so I have logged a new bug.
I have been happily using this integration for a long time so thanks for all the hard work. I updated via HACS this morning and HA no longer connects to any thermostats

I get this error in the logs after I rebooted HA
```
2021-01-19 08:11:29 ERROR (MainThread) [homeassistant.components.climate] Error while setting up heatmiserneo platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/heatmiserneo/climate.py", line 56, in async_setup_entry
_, devices = await hub.get_live_data()
File "/usr/local/lib/python3.8/site-packages/neohubapi/neohub.py", line 343, in get_live_data
thermostats.append(NeoStat(self, thermostat))
File "/usr/local/lib/python3.8/site-packages/neohubapi/neostat.py", line 53, in __init__
self.prg_temp = self._data_.PRG_TEMP
AttributeError: 'types.SimpleNamespace' object has no attribute 'PRG_TEMP'
```

I get the same error for the switch.  
I am happy to provide any logs or more details to help diagnose the issue.

**Comment by gerrowadat** [comment]
This is possibly the same-ish issue (i.e. the neohub is fickle in what it returns and the spec isn't clear).

I've had a go at fixing this in neohubapi, if you wanted to merge this in and see if it works for you: https://gitlab.com/neohubapi/neohubapi/-/merge_requests/4/diffs?commit_id=0b307ad7671c8fbf0a1f33b64beaf8e3badf6649

**Comment by Unthred** [comment]
@gerrowadat that's amazing thanks very much. Sorry to be such a newbie but should I just take a copy of that file and drop it into my custom_comooments folder?

**Comment by gerrowadat** [comment]
@Unthred Nope, this is a patch for neohubapi which is a separate python package. It'll be in your PYTHONPATH somewhere. I wouldn't advise going and patching your installed python libraries just yet, I'd say give it a wee while so the neohubapi maintainers can consider the change and do a release.

**Comment by Unthred** [comment]
Ahhhhh ok will just wait then.... So does that mean it's a ha core update then not the HACS package

**Comment by gerrowadat** [comment]
Dislcaimer: I am not a developer on any of these projects, I am just guessing -- but I suspect this will be a change in [neohubapi](https://gitlab.com/neohubapi/neohubapi)

**Comment by stikonas** [comment]
@Unthred it's not in ha core yet. Some of the contributors are looking at what needs to be done to send it upstream.

One of the required things is that all device specific communication has to be via external python library. This is now done but as you can see there is a little bit of fallout. I guess that's a bit expected, not many people are willing to test PRs :(.

Once I do a new neohubapi release (soon), I hope HA will notice it and update (possibly after one or two restarts).

**Comment by DrTree** [comment]
You could Push the new package and then bump the min version in the manifest?

**Comment by stikonas** [comment]
Yes, we can bump min version. But the question is will it upgrade to latest without bumping min version? That I don't know but it is easily testable after neohubapi. If it doesn't upgrade, then we bump the min version.

**Comment by Unthred** [comment]
> @Unthred it's not in ha core yet. Some of the contributors are looking at what needs to be done to send it upstream.
> 
> One of the required things is that all device specific communication has to be via external python library. This is now done but as you can see there is a little bit of fallout. I guess that's a bit expected, not many people are willing to test PRs :(.
> 
> Once I do a new neohubapi release (soon), I hope HA will notice it and update (possibly after one or two restarts).

I will happily test for you 😀

**Comment by gerrowadat** [comment]
My guess is it won't do it for existing installs where the requirement is still satisfied with 0.3 but will for new installs (where you get latest).

Probably no harm updating the manifest since we know 0.3 causes issues (will, did for me at least :-))

**Comment by stikonas** [comment]
Should work now that #63 is merged.

**Comment by gerrowadat** [comment]
@Unthred if you update via hacs (i.e. hit 'update information' in the 3-dots menu on the integration and update/restart) this will hopefully be fixed.

**Comment by Unthred** [comment]
Amazing! Updated via HACS and I can see the thermostats again!

Thanks soooooo much for your help / work

**Comment by stikonas** [comment]
@Unthred can you close this issue then?

**Comment by Unthred** [comment]
Answered and fixed super fast! Kudos to the guys working on this thanks sooooo much
