### ISSUE TITLE
No ‘version’ key in the manifest file 

### ISSUE THREAD

**Issue by p4mr** [MindrustUK/Heatmiser-for-home-assistant#68]
Following error appears in the Logs during startup

WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'heatmiserneo'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'heatmiserneo'

**Comment by stikonas** [comment]
@p4mr Are you up for making a PR? You just need to add version key here: https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/master/custom_components/heatmiserneo/manifest.json

**Comment by p4mr** [comment]
Closed with "version" added to the manifest.json
