### ISSUE TITLE
Add states for lovelace card

### ISSUE THREAD

**Issue by MindrustUK** [MindrustUK/Heatmiser-for-home-assistant#7]
@mindtrustUK: I hardly dare ask as I know that you don't have much time to work on the .py file, but I do it anyway: I am using lovelace card "simple thermostat" which should show buttons but doesn't 

<img width="481" alt="Screenshot 2019-03-24 at 08 38 48" src="https://user-images.githubusercontent.com/26715092/54877013-006c0300-4e11-11e9-8972-02d94929de86.png">

I also have Mitsubishi air conditioners which uses Melcloud (climate.py) and the do show buttons in the same simple thermostat card:

<img width="481" alt="Screenshot 2019-03-24 at 08 38 02" src="https://user-images.githubusercontent.com/26715092/54877024-3610ec00-4e11-11e9-8fdf-0aeaf752169e.png">

my question is whether it would be possible to add buttons for heatmiserneo? 

The Melcloud "states" have the following information:

<img width="475" alt="Screenshot 2019-03-24 at 08 48 47" src="https://user-images.githubusercontent.com/26715092/54877069-aa4b8f80-4e11-11e9-864c-46f81aebebfc.png">

I guess the "operation mode" and "operation list" does the trick.

Could the applicable options be included in the climate.py file of the Neo?

_Originally posted by @Trouble-51 in https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/3#issuecomment-475940334_

**Comment by MindrustUK** [comment]
I've reviewed this and it's "operation_list" as suggested. I've had a quick bash at this and it's not showing up in states for some odd reason. Should be a quick fix once I work out why it's not returning.

**Comment by MindrustUK** [comment]
@Trouble-51 I've done a few changes that should meet your needs. Please test and feedback.

**Comment by Trouble-51** [comment]
First of all thanks very much for taking the time to implement these changes, very much appreciated.

I did some tests and the results are:

1) I made four screen shots:

-  the first one of a room where heating is on and you see the rectangle, 
-  the second one where heating is on idle, but the rectangle is not moving to that icon 
-  the third one of a room that is not being used and is in away mode, rectangle not moving, but the away mode is not one of the icons
-  the last one shows the states

2) away mode in not shown as an icon

3) it would be better to have the icon that is “active” shown in another color

4) I don’t think that there is a cooling mode

5) when I press the icons I get the following message (and nothing happens): Failed to call service climate/set_operation_mode














I hope this helps

Good luck with all the requests I see going your way!

Best regards,

Jos

**Comment by MindrustUK** [comment]
Closing this ticket, please test against the development branch if this is still live and feel free to open further tickets as required. Time has past and much development has been done, hopefully some of this was caught in the improvements. I know hvac_actions and hvac_modes are now correctly reflected.
