### ISSUE TITLE
Entity Count

### ISSUE THREAD

**Issue by PhillyGilly** [MindrustUK/Heatmiser-for-home-assistant#71]
I have 19 heatmiser devices in operation: 9 Neostats, 3 Neostat-E, 5 Neostat-HW and 2 repeaters.
These are all picked up and their json data is visible in my HA log file and all the Neostats are working in HA.
However I notice that only the Neostats and Neostat-E are shown under the Configuration Integration and Entities grouped by "Heatmiser Neo Climate":
![image](https://user-images.githubusercontent.com/56273663/113126337-73ce5980-920f-11eb-9a9b-b699dc822a98.png)
![image](https://user-images.githubusercontent.com/56273663/113126075-2e119100-920f-11eb-9b8c-fd3053b64ed6.png)

The Neostat-HW switches and repeaters are reported as Entities as from the integration Switches:
![image](https://user-images.githubusercontent.com/56273663/113127249-72e9f780-9210-11eb-9145-b8b193e1ecc1.png)

It would be neat if the reported devices was reported accurately for an at-a-glance check and all entities were shown as being grouped under "Heatmiser Neo". I can see that the integration name is pulled from the manifest.json name field for the climate entities.

**Comment by stikonas** [comment]
Agreed, we should properly implement devices in this integration, not just entities. I had a brief go at it but didn't get it to work. (Need to read up a bit more on home assistant API).

**Comment by PhillyGilly** [comment]
We are making good progress and my switches now show as Entities

![image](https://user-images.githubusercontent.com/56273663/117583331-8edd9480-b0fe-11eb-9bbd-68d69b5802da.png)
 However the Repeaters have disappeared from HA.
I was wondering if a simple ELIF in switch.py will bring them back? i.e.

    for device in NeoHubJson['devices']:
        if ((device['DEVICE_TYPE'] != 6) and ('TIMECLOCK' in device['STAT_MODE'])) or (device['DEVICE_TYPE'] == 6) or (device['DEVICE_TYPE'] == 10)):
            name = device['device']
            
            if (device['DEVICE_TYPE'] == 6):
                _LOGGER.info("Neoplug Named: %s " % name)
                switch_type = NEO_PLUG
            elif (device['DEVICE_TYPE'] == 10):
                _LOGGER.info("Repeater Named: %s " % name)
                switch_type = REPEATER
            else:
                _LOGGER.info("Thermostat as Switch Named: %s " % name)
                switch_type = NEO_STAT

Even if that works, it's not the whole answer as what I need to know is that the Neohub can "see" the repeaters in real time. The best answer I have to that is to create another entity which piggy backs on the repeater entity and shows it presence by changing icon.

- platform: template
  switches:
    repeater_node_26183:
      friendly_name: "Node 1"
      value_template: "{{ is_state('switch.repeaternode26183', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.repeaternode26183
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.repeaternode26183
      icon_template: >-
        {% if is_state('switch.repeaternode26183', 'unavailable') %}
          mdi:access-point-off
        {% else %}
          mdi:access-point
        {% endif %}

**Comment by PhillyGilly** [comment]
Just upgraded my hub to Gen2, so I will look forward to a new release too. Thanks

**Comment by PhillyGilly** [comment]
I have two new devices which I assume are the repeaters, but there shown as unnamed instead of having the repeater_number as previously:
![image](https://user-images.githubusercontent.com/56273663/132513734-4d3de2f7-8171-47e1-9305-0ebd46749d05.png)

**Comment by PhillyGilly** [comment]
Is it possible to get these unnamed devices a) named and b) Shown as part of the Heatmiser Neo Climate? Thanks

**Comment by ribbal** [comment]
@PhillyGilly, does the latest update resolve this device/entity count issue?  It seems to work for me with Neostats and a Neostat-HW (I don't have any Neostat-E or repeaters).

**Comment by PhillyGilly** [comment]
HI @ribbal Under the version I'm running d2bb05d  I get 12 devices without duplication
![image](https://user-images.githubusercontent.com/56273663/147832084-76e6802d-c8b5-4171-ba2e-13da8461a3d3.png)
but I also get two more entities which are the repeaters 
![image](https://user-images.githubusercontent.com/56273663/147832216-67050507-98e0-48ba-91d7-17745de43dd0.png)
I will try the latest version and get back, but I feat that I will lose the repeaters even if the duplicates are resolved (see#94).

**Comment by PhillyGilly** [comment]
OK, I've just upgraed to the latest available and I get the duplication again.
![image](https://user-images.githubusercontent.com/56273663/147833938-a37649c3-7bef-412e-8380-1997cdf1361d.png)
One of the unnamed devices has disappeared which suggests that the link between my two repeaters is down. Checking in the Heatmiser app confirms that the Neostat which is connected via the two repeaters is off-line. However in HA the unavailable  neostat-e is still showing as active.
![image](https://user-images.githubusercontent.com/56273663/147834459-98395c46-e1d8-4ce4-9f2c-30631d04fa9e.png)

**Comment by ribbal** [comment]
What is in the list of '29 devices'?

**Comment by PhillyGilly** [comment]
![image](https://user-images.githubusercontent.com/56273663/147835140-d8b4cb15-8e85-47e3-90c8-0a7f236d43db.png)
![image](https://user-images.githubusercontent.com/56273663/147835169-d859545c-d4e2-4280-8ece-535c3540f27e.png)

**Comment by ribbal** [comment]
Are you able to select any of those duplicate devices and 'remove' them?

**Comment by stikonas** [comment]
> Are you able to select any of those duplicate devices and remove them?

I don't see any delete button in the device list (although I don't have any duplicate devices myself, not sure what's going on here). In some other integrations (e.g. Tasmota) I can delete devices. So I guess there is some HA API that we need to hook into for deletion to work.

**Comment by ribbal** [comment]
No, I don't see any delete option either, but I don't have any duplicate devices either.  If I recall correctly, I had to manually delete the duplicate 'floor temperature sensor' devices that roscoegray had introduced in Oct 2021 (that no longer exist now).

I suspect that HA is caching some data (perhaps in the database) that may disappear over time.  In this scenario, I wonder if the delete option is available.

**Comment by ribbal** [comment]
@PhillyGilly, can I suggest you try to 'Delete' the Heatmiser Neo Climate integration and re-add it?  I've done this previously without affecting any data/automations, etc..

**Comment by ribbal** [comment]
Yep, this definitely looks like it's related to those 'floor temperature sensors' that no longer exist in the integration (based on  screenshots above):

![image](https://user-images.githubusercontent.com/30695106/147838220-4affea58-5bbe-4033-9150-82494ebbb951.png)

**Comment by PhillyGilly** [comment]
That worked, thank you.
![image](https://user-images.githubusercontent.com/56273663/147855633-ae29ab71-e9dc-49c9-906f-8c30b70ab177.png)
And my repeaters are hanging in there as unnamed devices.
Now all I need is if(device['DEVICE_TYPE'] == 10) : switch_type = REPEATER and I will be vey happy.

**Comment by ribbal** [comment]
@PhillyGilly, I believe that the 'Entity Count' issue has been resolved and you should see the 9 Neostats, 3 Neostat-E, 5 Neostat-HW devices that you have.  The remaining issue appears to be that your repeaters are 'unnamed'.

As the message trail on this issue is quite long (and confusing), please could I ask that you close it and open a separate targeted issue related to the 'unnamed' repeaters?  I believe that fixing the naming issue will result in the repeaters appearing in the device/entity list (in your last screenshot above).

**Comment by PhillyGilly** [comment]
@ribbal OK. See new issue #96
