### ISSUE TITLE
Thermostat's _hvac_action slow to update

### ISSUE THREAD

**Issue by robcos** [MindrustUK/Heatmiser-for-home-assistant#77]
Say your temperature is  20 and you change your target temperature to 25, the hardware thermostat updates almost immediately. However, the home assistant thermostat will show _Idle_ until the next execution of async_update which could happen much later

What is the right way of dealing with it? One way could be that when the target temperature is changes, we call async_update explicitly. Any issue with it? 
If we fix https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/76 I would hope that it would make the change almost instantaneous

**Comment by ribbal** [comment]
@robcos, I believe this has now been resolved in the latest version following the fix for https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/76.  Please could you test and close this issue if you are happy with the results?
