### ISSUE TITLE
Add support for NeoPlug devices

### ISSUE THREAD

**Issue by MindrustUK** [MindrustUK/Heatmiser-for-home-assistant#8]
Add support for NeoPlug devices.
These behave as time clocks and present with ID6. Need to add a "Switch" component for HASS.

**Comment by MindrustUK** [comment]
Early Neoplug support over here: https://github.com/MindrustUK/Neoplug-for-home-assistant/

**Comment by haakonstorm** [comment]
Works perfectly here with the one plug I have! Awesome! :)

**Comment by haakonstorm** [comment]
Oops! After reboot - it turns on, then turns off again automatically after either 10 seconds or a few minutes. Maybe something with the state remembered being wrong? (on/off/toggle). How to fix that?

**Comment by MindrustUK** [comment]
@haakonstorm please raise a bug against the Neoplug project and I'll have a look. Cheers.
