### ISSUE TITLE
Separate devices are created for under floor temperature sensors.

### ISSUE THREAD

**Issue by jamespreedy** [MindrustUK/Heatmiser-for-home-assistant#94]
Hiya, thanks for all your great work on this HACS component.
I'm getting the below error when I startup Home Assistant.

`Logger: custom_components.heatmiserneo.sensor
Source: custom_components/heatmiserneo/sensor.py:52 
Integration: Heatmiser Neo Climate (documentation) 
First occurred: 8:28:47 am (13 occurrences) 
Last logged: 8:28:47 am

You are using an OBSOLETE sensor integration (heatmiserneo Bedroom 2 Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Bedroom 2 climate entity (e.g. state_attr('climate.bedroom 2', 'floor_temperature')).
You are using an OBSOLETE sensor integration (heatmiserneo Bedroom 1 Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Bedroom 1 climate entity (e.g. state_attr('climate.bedroom 1', 'floor_temperature')).
You are using an OBSOLETE sensor integration (heatmiserneo Annex Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Annex climate entity (e.g. state_attr('climate.annex', 'floor_temperature')).
You are using an OBSOLETE sensor integration (heatmiserneo Kitchenette Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Kitchenette climate entity (e.g. state_attr('climate.kitchenette', 'floor_temperature')).
You are using an OBSOLETE sensor integration (heatmiserneo Bedroom 3 Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Bedroom 3 climate entity (e.g. state_attr('climate.bedroom 3', 'floor_temperature')).`

I'm able to use the state attribute without issue ... state_attr('climate.bedroom 3', 'floor_temperature') ... so it seems that the heatmiserneo Bedroom 3 Floor Temperature is no longer needed.

Please let me know if you need any more information, or if I can help at all?
Thanks!

**Comment by PhillyGilly** [comment]
![image](https://user-images.githubusercontent.com/56273663/147386902-e71f2dc0-3f73-42fe-903a-5ea1cedfba82.png)
I rolled this back after the multiple sensors issue.

**Comment by jamespreedy** [comment]
Just to bump this gently due to the timings ...

I'm still seeing the below in my logs on boot.

`This error originated from a custom integration.

Logger: custom_components.heatmiserneo.sensor
Source: custom_components/heatmiserneo/sensor.py:52 
Integration: Heatmiser Neo Climate (documentation) 
First occurred: 9:31:53 am (13 occurrences) 
Last logged: 9:31:53 am

You are using an OBSOLETE sensor integration (heatmiserneo Bedroom 2 Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Bedroom 2 climate entity (e.g. state_attr('climate.bedroom 2', 'floor_temperature')).
You are using an OBSOLETE sensor integration (heatmiserneo Bedroom 1 Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Bedroom 1 climate entity (e.g. state_attr('climate.bedroom 1', 'floor_temperature')).
You are using an OBSOLETE sensor integration (heatmiserneo Annex Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Annex climate entity (e.g. state_attr('climate.annex', 'floor_temperature')).
You are using an OBSOLETE sensor integration (heatmiserneo Kitchenette Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Kitchenette climate entity (e.g. state_attr('climate.kitchenette', 'floor_temperature')).
You are using an OBSOLETE sensor integration (heatmiserneo Bedroom 3 Floor Temperature), which will be removed after 31st December 2021. Instead, please use the new 'floor_temperature' state attribute on the standard heatmiserneo Bedroom 3 climate entity (e.g. state_attr('climate.bedroom 3', 'floor_temperature')).
`

It's the "which will be removed after 31st December 2021" that got me to add this report as an update - thanks in advance!

**Comment by ribbal** [comment]
Hi @jamespreedy, this has been on my radar for a couple of months now.  I was waiting until **after** 31st December 2021 (as stated in the log message) to complete this task.  Anyway, I've created https://github.com/MindrustUK/Heatmiser-for-home-assistant/pull/97 a little early, which will resolve this.  This is awaiting a merge.

**Comment by jamespreedy** [comment]
Ah great news - you're way ahead of me!

Thanks as always for your support - fantastic add on! 😎🍺🙌🏻

**Comment by stikonas** [comment]
I guess this can be closed now

**Comment by MindrustUK** [comment]
Will review in 30 days and close if there's nothing further.

**Comment by albarlow** [comment]
I still have additional devices for floor temperatures.  Should they go away automatically or do I have to remove and re-add the integration?

**Comment by ribbal** [comment]
> 

You will need to remove and re-add the integration for the additional floor temperature devices to disappear.

**Comment by albarlow** [comment]
Brilliant, that removed the extra devices.

**Comment by MindrustUK** [comment]
Closing: resolved.
