### ISSUE TITLE
Unnamed devices

### ISSUE THREAD

**Issue by PhillyGilly** [MindrustUK/Heatmiser-for-home-assistant#99]
I use Heatmiser repeaters to extend the Zigbee network coverage. 
These are detected by HA as unnamed entities e.g.
![image](https://user-images.githubusercontent.com/56273663/148364313-ede843a8-425a-4cac-a24d-8d11d10804db.png)
As I want to monitor the health of the network, I would like these entities to be reported.
This would require the discovered devices to include if(device['DEVICE_TYPE'] == 10) : switch_type = REPEATER.
(see also closed issue #71)

**Comment by ribbal** [comment]
Hi @PhillyGilly, I don't have any repeaters.  Are you able to post the debug logs here please (just the logs for the repeaters should suffice)?

**Comment by PhillyGilly** [comment]
This is an extract from my 20210331 log:
{'AWAY': False, 'COOLING': False, 'COOLING_ENABLED': False, 'COOLING_TEMPERATURE_IN_WHOLE_DEGREES': 0, 'COOL_INP': False, 'COUNT_DOWN_TIME': '0:00', 'CRADLE_PAIRED_TO_REMOTE_SENSOR': False, 'CRADLE_PAIRED_TO_STAT': False, 'CURRENT_FLOOR_TEMPERATURE': 127, 'CURRENT_SET_TEMPERATURE': '0.0', 'CURRENT_TEMPERATURE': '255.255', 'DEMAND': False, 'DEVICE_TYPE': 10, 'ENABLE_BOILER': False, 'ENABLE_COOLING': False, 'ENABLE_PUMP': False, 'ENABLE_VALVE': False, 'ENABLE_ZONE': False, 'FAILSAFE_STATE': False, 'FAIL_SAFE_ENABLED': False, 'FLOOR_LIMIT': False, 'FULL/PARTIAL_LOCK_AVAILABLE': False, 'HEAT/COOL_MODE': False, 'HEATING': False, 'HOLD_TEMPERATURE': 0, 'HOLD_TIME': '0:00', 'HOLIDAY': False, 'HOLIDAY_DAYS': 0, 'HUMIDITY': 0, 'LOCK': False, 'LOCK_PIN_NUMBER': '0000', 'LOW_BATTERY': False, 'MAX_TEMPERATURE': '255.255', 'MIN_TEMPERATURE': '255.255', 'MODULATION_LEVEL': 0, 'NEXT_ON_TIME': '255 days 255:255', 'OFFLINE': False, 'OUPUT_DELAY': False, 'OUTPUT_DELAY': 0, 'PREHEAT': False, 'PREHEAT_TIME': '255:255', 'PROGRAM_MODE': '5DAY/2DAY', 'PUMP_DELAY': False, 'RADIATORS_OR_UNDERFLOOR': False, 'SENSOR_SELECTION': 'BUILT_IN_AIR_SENSOR', 'SET_COUNTDOWN_TIME': 0, 'STANDBY': False, 'STAT_MODE': {'4_HEAT_LEVELS': True, 'MANUAL_OFF': True, 'TIMECLOCK': True}, 'TEMPERATURE_FORMAT': False, 'TEMP_HOLD': False, 'TIMECLOCK_MODE': False, 'TIMER': False, 'TIME_CLOCK_OVERIDE_BIT': False, 'ULTRA_VERSION': 0, 'VERSION_NUMBER': 69, 'WRITE_COUNT': 0, 'ZONE_1PAIRED_TO_MULTILINK': True, 'ZONE_1_OR_2': False, 'ZONE_2_PAIRED_TO_MULTILINK': False, 'device': 'repeaternode26183'}
This is what I see today:
2022-01-06 15:14:12 DEBUG (MainThread) [custom_components.heatmiserneo.switch] Creating HeatMiser NeoStat (None):
- active_level: 0
- active_profile: 0
- available_modes: ['heat']
- away: False
- cool_on: False
- cool_temp: 0
- current_floor_temperature: 127.5
- date: sunday
- device_id: None
- fan_control: Automatic
- fan_speed: Off
- floor_limit: None
- hc_mode: VENT
- heat_mode: True
- heat_on: False
- hold_cool: 78.5
- hold_off: True
- hold_on: False
- hold_temp: 0
- hold_time: 0:00:00
- holiday: False
- lock: False
- low_battery: False
- manual_off: True
- modelock: False
- modulation_level: 0
- name: None
- offline: True
- pin_number: 0
- preheat_active: 0
- prg_temp: 72
- prg_timer: False
- rate_of_change: <AwaitableOnly "NeoStat.rate_of_change">
- standby: False
- switch_delay_left: 0:00:00
- target_temperature: 0.0
- temperature: 255.255
- temporary_set_flag: False
- time: 0:00:00
- timer_on: False
- weekday: Weekday.SUNDAY
- window_open: False
- write_count: 0

**Comment by ribbal** [comment]
@PhillyGilly, yes this is what I was looking for; thanks.

If you check this output from any of your other devices you will see that they each have a 'zone_name' attribute, which the repeaters (above) don't have.  This is the root cause of the issue.

**Comment by ribbal** [comment]
@PhillyGilly, it's the logs that begin with the following line that I was looking for: 

2022-01-06 17:20:37 DEBUG (MainThread) [custom_components.heatmiserneo] **devices_data**:

**Comment by PhillyGilly** [comment]
@ribbal here is the whole log

[log20220106.txt](https://github.com/MindrustUK/Heatmiser-for-home-assistant/files/7823696/log20220106.txt)

**Comment by PhillyGilly** [comment]
@ribbal that would be great.
Here is a bit of log from March 2021
{'AWAY': False, 'COOLING': False, 'COOLING_ENABLED': False, 'COOLING_TEMPERATURE_IN_WHOLE_DEGREES': 111, 'COOL_INP': False, 'COUNT_DOWN_TIME': '0:00', 'CRADLE_PAIRED_TO_REMOTE_SENSOR': False, 'CRADLE_PAIRED_TO_STAT': False, 'CURRENT_FLOOR_TEMPERATURE': 127, 'CURRENT_SET_TEMPERATURE': '239.5', 'CURRENT_TEMPERATURE': '29.0', 'DEMAND': False, 'DEVICE_TYPE': 12, 'ENABLE_BOILER': False, 'ENABLE_COOLING': False, 'ENABLE_PUMP': False, 'ENABLE_VALVE': False, 'ENABLE_ZONE': False, 'FAILSAFE_STATE': False, 'FAIL_SAFE_ENABLED': False, 'FLOOR_LIMIT': False, 'FULL/PARTIAL_LOCK_AVAILABLE': False, 'HEAT/COOL_MODE': False, 'HEATING': False, 'HOLD_TEMPERATURE': 0, 'HOLD_TIME': '0:00', 'HOLIDAY': False, 'HOLIDAY_DAYS': 0, 'HUMIDITY': 0, 'LOCK': False, 'LOCK_PIN_NUMBER': '0000', 'LOW_BATTERY': False, 'MAX_TEMPERATURE': '255.255', 'MIN_TEMPERATURE': '255.255', 'MODULATION_LEVEL': 0, 'NEXT_ON_TIME': '1 days 20:00', 'OFFLINE': False, 'OUPUT_DELAY': False, 'OUTPUT_DELAY': 0, 'PREHEAT': False, 'PREHEAT_TIME': '255:255', 'PROGRAM_MODE': '5DAY/2DAY', 'PUMP_DELAY': False, 'RADIATORS_OR_UNDERFLOOR': False, 'SENSOR_SELECTION': 'BUILT_IN_AIR_SENSOR', 'SET_COUNTDOWN_TIME': 0, 'STANDBY': False, 'STAT_MODE': {'4_HEAT_LEVELS': True, 'MANUAL_OFF': True, 'TIMECLOCK': True}, 'TEMPERATURE_FORMAT': False, 'TEMP_HOLD': False, 'TIMECLOCK_MODE': False, 'TIMER': True, 'TIME_CLOCK_OVERIDE_BIT': False, 'ULTRA_VERSION': 0, 'VERSION_NUMBER': 22, 'WRITE_COUNT': 4, 'ZONE_1PAIRED_TO_MULTILINK': True, 'ZONE_1_OR_2': False, 'ZONE_2_PAIRED_TO_MULTILINK': False, 'device': 'Hot Water 2'}
{'AWAY': False, 'COOLING': False, 'COOLING_ENABLED': False, 'COOLING_TEMPERATURE_IN_WHOLE_DEGREES': 0, 'COOL_INP': False, 'COUNT_DOWN_TIME': '0:00', 'CRADLE_PAIRED_TO_REMOTE_SENSOR': False, 'CRADLE_PAIRED_TO_STAT': False, 'CURRENT_FLOOR_TEMPERATURE': 127, 'CURRENT_SET_TEMPERATURE': '0.0', 'CURRENT_TEMPERATURE': '255.255', 'DEMAND': False, 'DEVICE_TYPE': 10, 'ENABLE_BOILER': False, 'ENABLE_COOLING': False, 'ENABLE_PUMP': False, 'ENABLE_VALVE': False, 'ENABLE_ZONE': False, 'FAILSAFE_STATE': False, 'FAIL_SAFE_ENABLED': False, 'FLOOR_LIMIT': False, 'FULL/PARTIAL_LOCK_AVAILABLE': False, 'HEAT/COOL_MODE': False, 'HEATING': False, 'HOLD_TEMPERATURE': 0, 'HOLD_TIME': '0:00', 'HOLIDAY': False, 'HOLIDAY_DAYS': 0, 'HUMIDITY': 0, 'LOCK': False, 'LOCK_PIN_NUMBER': '0000', 'LOW_BATTERY': False, 'MAX_TEMPERATURE': '255.255', 'MIN_TEMPERATURE': '255.255', 'MODULATION_LEVEL': 0, 'NEXT_ON_TIME': '255 days 255:255', 'OFFLINE': False, 'OUPUT_DELAY': False, 'OUTPUT_DELAY': 0, 'PREHEAT': False, 'PREHEAT_TIME': '255:255', 'PROGRAM_MODE': '5DAY/2DAY', 'PUMP_DELAY': False, 'RADIATORS_OR_UNDERFLOOR': False, 'SENSOR_SELECTION': 'BUILT_IN_AIR_SENSOR', 'SET_COUNTDOWN_TIME': 0, 'STANDBY': False, 'STAT_MODE': {'4_HEAT_LEVELS': True, 'MANUAL_OFF': True, 'TIMECLOCK': True}, 'TEMPERATURE_FORMAT': False, 'TEMP_HOLD': False, 'TIMECLOCK_MODE': False, 'TIMER': False, 'TIME_CLOCK_OVERIDE_BIT': False, 'ULTRA_VERSION': 0, 'VERSION_NUMBER': 69, 'WRITE_COUNT': 0, 'ZONE_1PAIRED_TO_MULTILINK': True, 'ZONE_1_OR_2': False, 'ZONE_2_PAIRED_TO_MULTILINK': False, 'device': 'repeaternode26183'}
Where the time clock and repeater seem to be treated more equally, so there must have been a reason for the change.
I don't think Heatmiser actually like customers to use repeaters and in fact you can get the same range extending function by adding neo-plugs. The repeaters are "invisible" in the App and you can add the same repeater multiple times and you get multiple duplicates with different device names. I have no idea what the numbers mean. I would have thought "repeaternode001" etc would be more sensible.,

**Comment by ribbal** [comment]
Fixed in neohub api.  Created https://github.com/MindrustUK/Heatmiser-for-home-assistant/pull/100 to increment minimum neohub api version number.

**Comment by ribbal** [comment]
@PhillyGilly, have you tried the latest release that includes the above fix?  And, does it resolve the problem of unnamed repeaters?

**Comment by PhillyGilly** [comment]
Hi @ribbal. Not yet. Will I get a nudge from HACS, or do I need to download the files here and install them in custom - components?

**Comment by ribbal** [comment]
I got a nudge from HACS; but, I've got a sensor/alert to inform me.  If you go into HACS, I guess you will see an update.

**Comment by PhillyGilly** [comment]
![image](https://user-images.githubusercontent.com/56273663/148594387-d3a960ce-fd71-4db5-b13e-99bdca943d21.png)

Perfect. All I need to do is check/correct my HA rework code for the dummy sensors that change icon based on the is available of the unnamed repeaters. Thank you

**Comment by ribbal** [comment]
@PhillyGilly, I'm pleased that this has worked for you.  Also, to let you know that I've made further changes that adds an 'offline' attribute.  It's literally been released 'just now', so you may have missed it (check in HACS for any further updates).  This 'offline' attribute should give you exactly what you need to determine if a device is offline.

It works for my devices, but I don't have repeaters or any HC devices.  Hope it works for you?  Please let me know.

**Comment by PhillyGilly** [comment]
@ribbal This is how it looks with Repeater 2 powered down
![image](https://user-images.githubusercontent.com/56273663/148616237-8d52a009-4ef4-4dcd-a953-9ccfaf8c8e53.png)
Switch.yaml contains:
- platform: template
  switches:
    repeater_node_1:
      friendly_name: "Rpt 1"
      value_template: "{{ state_attr('switch.repeaternode44138', 'offline') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.repeaternode44138
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.repeaternode44138
      icon_template: >-
        {% if state_attr('switch.repeaternode44138', 'offline') %}
          mdi:access-point-off
        {% else %}
          mdi:access-point
        {% endif %}
Many, many thanks!
